/*
SMS

Testing EmailToSmsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package clicksend

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/ClickSend/clicksend-go-v2"
)

func Test_clicksend_EmailToSmsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EmailToSmsAPIService AddAllowedEmail", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EmailToSmsAPI.AddAllowedEmail(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailToSmsAPIService CreateStrippedStringRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EmailToSmsAPI.CreateStrippedStringRule(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailToSmsAPIService DeleteStrippedStringRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ruleId string

		resp, httpRes, err := apiClient.EmailToSmsAPI.DeleteStrippedStringRule(context.Background(), ruleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailToSmsAPIService UpdateStrippedStringRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ruleId string

		resp, httpRes, err := apiClient.EmailToSmsAPI.UpdateStrippedStringRule(context.Background(), ruleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailToSmsAPIService ViewAllowedEmails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EmailToSmsAPI.ViewAllowedEmails(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailToSmsAPIService ViewStrippedStringRule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ruleId string

		resp, httpRes, err := apiClient.EmailToSmsAPI.ViewStrippedStringRule(context.Background(), ruleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailToSmsAPIService ViewStrippedStringRules", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EmailToSmsAPI.ViewStrippedStringRules(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
