/*
SMS

Testing AlphaTagsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package clicksend

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/ClickSend/clicksend-go-v2"
)

func Test_clicksend_AlphaTagsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AlphaTagsAPIService DeleteAlphaTag", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alphaTagId string

		httpRes, err := apiClient.AlphaTagsAPI.DeleteAlphaTag(context.Background(), alphaTagId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlphaTagsAPIService GetAlphaTag", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var alphaTagId string

		resp, httpRes, err := apiClient.AlphaTagsAPI.GetAlphaTag(context.Background(), alphaTagId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlphaTagsAPIService ListAlphaTags", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AlphaTagsAPI.ListAlphaTags(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AlphaTagsAPIService RequestAlphaTag", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AlphaTagsAPI.RequestAlphaTag(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
