/*
SMS

Testing MmsCampaignsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package clicksend

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_clicksend_MmsCampaignsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MmsCampaignsAPIService CalculateMmsCampaignPrice", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MmsCampaignsAPI.CalculateMmsCampaignPrice(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MmsCampaignsAPIService CancelMmsCampaign", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var mmsCampaignId string

		resp, httpRes, err := apiClient.MmsCampaignsAPI.CancelMmsCampaign(context.Background(), mmsCampaignId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MmsCampaignsAPIService SendMmsCampaign", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MmsCampaignsAPI.SendMmsCampaign(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MmsCampaignsAPIService UpdateMmsCampaign", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var mmsCampaignId string

		resp, httpRes, err := apiClient.MmsCampaignsAPI.UpdateMmsCampaign(context.Background(), mmsCampaignId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MmsCampaignsAPIService ViewAllMmsCampaigns", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MmsCampaignsAPI.ViewAllMmsCampaigns(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MmsCampaignsAPIService ViewMmsCampaign", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var mmsCampaignId string

		resp, httpRes, err := apiClient.MmsCampaignsAPI.ViewMmsCampaign(context.Background(), mmsCampaignId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
