/*
SMS

Testing ContactsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package clicksend

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/ClickSend/clicksend-go-v2"
)

func Test_clicksend_ContactsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContactsAPIService DeleteContact", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var listId string
		var contactId string

		resp, httpRes, err := apiClient.ContactsAPI.DeleteContact(context.Background(), listId, contactId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContactsAPIService GetSpecificContact", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var listId string
		var contactId string

		resp, httpRes, err := apiClient.ContactsAPI.GetSpecificContact(context.Background(), listId, contactId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContactsAPIService UpdateContact", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var listId string
		var contactId string

		resp, httpRes, err := apiClient.ContactsAPI.UpdateContact(context.Background(), listId, contactId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
