/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the CalculateSmsPriceDataSummaryCountriesInnerCountry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalculateSmsPriceDataSummaryCountriesInnerCountry{}

// CalculateSmsPriceDataSummaryCountriesInnerCountry The country of the receipient in two-letter format (e.g. US, UK, AU, NZ, etc).
type CalculateSmsPriceDataSummaryCountriesInnerCountry struct {
	// The global sending requirement for this country. It can be one of the following:  - **0:** No number or account registration required.      - **1:** Number registration required. You can purchase a registered number from ClickSend. Examples: US and CA.      - **2:** Account registration required. You can register your company details or business details to register your account. Examples: NZ, SG and UAE.  <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note:</h4>   <p>This parameter is fixed and can't be changed based on your settings.</p> </div>
	RegistrationType *int32 `json:"registration_type,omitempty"`
	// The number of messages you are sending to this country. The system can count up to 1000 messages.
	ReceipientCount *int32 `json:"receipient_count,omitempty"`
	// Indicates whether you have a usable ***Sender ID** for this country:  - **True:** A **Sender ID** is available for you to use.      - **False:** No **Sender ID** is available for you to use.  <div class=\"info-box\">     <h4><i class=\"fas fa-info-circle\"></i> Note:</h4>     <p>Countries with <em>registration_type</em> set to <strong>0</strong> will have the <em>usable_sender_id</em> set as <strong>True</strong>, and messages will be sent from shared numbers.</p> </div>
	UsableSenderId *bool `json:"usable_sender_id,omitempty"`
	// Indicates whether you have enabled the global sending for this country:  - **True:** You have selected this country for global sending and can send messages here.      - **False:** You haven’t selected this country for global sending and can’t send messages here.
	Selected *bool `json:"selected,omitempty"`
	// The name of the country.
	Name *string `json:"name,omitempty"`
	Regulation *CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation `json:"regulation,omitempty"`
	// Your current registration status for this country. This parameter is used by the internal team to track the status of your registration.
	RegistrationStatusId *int32 `json:"registration_status_id,omitempty"`
	// The global sending requirement for this country. It can be one of the following:  - **0:** No number or account registration required.      - **1:** Number registration required. You can purchase a registered number from ClickSend. Examples: US and CA.      - **2:** Account registration required. You can register your company details or business details to register your account. Examples: NZ, SG and UAE.    This parameter is a duplicate of registration_type. It determines which form you need for the global sending registration process.  <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note:</h4>   <p>This parameter is static. Its value can’t change based on your settings.</p> </div>
	RegistrationEntityId *int32 `json:"registration_entity_id,omitempty"`
	// The Jotform identifier for your account. It’s used to track the global sending registration form. If it is **null**, no Jotform is assigned to you. It is used only for number and account registration.
	JotformId *int32 `json:"jotform_id,omitempty"`
}

// NewCalculateSmsPriceDataSummaryCountriesInnerCountry instantiates a new CalculateSmsPriceDataSummaryCountriesInnerCountry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalculateSmsPriceDataSummaryCountriesInnerCountry() *CalculateSmsPriceDataSummaryCountriesInnerCountry {
	this := CalculateSmsPriceDataSummaryCountriesInnerCountry{}
	return &this
}

// NewCalculateSmsPriceDataSummaryCountriesInnerCountryWithDefaults instantiates a new CalculateSmsPriceDataSummaryCountriesInnerCountry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalculateSmsPriceDataSummaryCountriesInnerCountryWithDefaults() *CalculateSmsPriceDataSummaryCountriesInnerCountry {
	this := CalculateSmsPriceDataSummaryCountriesInnerCountry{}
	return &this
}

// GetRegistrationType returns the RegistrationType field value if set, zero value otherwise.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetRegistrationType() int32 {
	if o == nil || IsNil(o.RegistrationType) {
		var ret int32
		return ret
	}
	return *o.RegistrationType
}

// GetRegistrationTypeOk returns a tuple with the RegistrationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetRegistrationTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.RegistrationType) {
		return nil, false
	}
	return o.RegistrationType, true
}

// HasRegistrationType returns a boolean if a field has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) HasRegistrationType() bool {
	if o != nil && !IsNil(o.RegistrationType) {
		return true
	}

	return false
}

// SetRegistrationType gets a reference to the given int32 and assigns it to the RegistrationType field.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) SetRegistrationType(v int32) {
	o.RegistrationType = &v
}

// GetReceipientCount returns the ReceipientCount field value if set, zero value otherwise.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetReceipientCount() int32 {
	if o == nil || IsNil(o.ReceipientCount) {
		var ret int32
		return ret
	}
	return *o.ReceipientCount
}

// GetReceipientCountOk returns a tuple with the ReceipientCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetReceipientCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ReceipientCount) {
		return nil, false
	}
	return o.ReceipientCount, true
}

// HasReceipientCount returns a boolean if a field has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) HasReceipientCount() bool {
	if o != nil && !IsNil(o.ReceipientCount) {
		return true
	}

	return false
}

// SetReceipientCount gets a reference to the given int32 and assigns it to the ReceipientCount field.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) SetReceipientCount(v int32) {
	o.ReceipientCount = &v
}

// GetUsableSenderId returns the UsableSenderId field value if set, zero value otherwise.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetUsableSenderId() bool {
	if o == nil || IsNil(o.UsableSenderId) {
		var ret bool
		return ret
	}
	return *o.UsableSenderId
}

// GetUsableSenderIdOk returns a tuple with the UsableSenderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetUsableSenderIdOk() (*bool, bool) {
	if o == nil || IsNil(o.UsableSenderId) {
		return nil, false
	}
	return o.UsableSenderId, true
}

// HasUsableSenderId returns a boolean if a field has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) HasUsableSenderId() bool {
	if o != nil && !IsNil(o.UsableSenderId) {
		return true
	}

	return false
}

// SetUsableSenderId gets a reference to the given bool and assigns it to the UsableSenderId field.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) SetUsableSenderId(v bool) {
	o.UsableSenderId = &v
}

// GetSelected returns the Selected field value if set, zero value otherwise.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetSelected() bool {
	if o == nil || IsNil(o.Selected) {
		var ret bool
		return ret
	}
	return *o.Selected
}

// GetSelectedOk returns a tuple with the Selected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetSelectedOk() (*bool, bool) {
	if o == nil || IsNil(o.Selected) {
		return nil, false
	}
	return o.Selected, true
}

// HasSelected returns a boolean if a field has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) HasSelected() bool {
	if o != nil && !IsNil(o.Selected) {
		return true
	}

	return false
}

// SetSelected gets a reference to the given bool and assigns it to the Selected field.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) SetSelected(v bool) {
	o.Selected = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) SetName(v string) {
	o.Name = &v
}

// GetRegulation returns the Regulation field value if set, zero value otherwise.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetRegulation() CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation {
	if o == nil || IsNil(o.Regulation) {
		var ret CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation
		return ret
	}
	return *o.Regulation
}

// GetRegulationOk returns a tuple with the Regulation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetRegulationOk() (*CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation, bool) {
	if o == nil || IsNil(o.Regulation) {
		return nil, false
	}
	return o.Regulation, true
}

// HasRegulation returns a boolean if a field has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) HasRegulation() bool {
	if o != nil && !IsNil(o.Regulation) {
		return true
	}

	return false
}

// SetRegulation gets a reference to the given CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation and assigns it to the Regulation field.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) SetRegulation(v CalculateSmsPriceDataSummaryCountriesInnerCountryRegulation) {
	o.Regulation = &v
}

// GetRegistrationStatusId returns the RegistrationStatusId field value if set, zero value otherwise.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetRegistrationStatusId() int32 {
	if o == nil || IsNil(o.RegistrationStatusId) {
		var ret int32
		return ret
	}
	return *o.RegistrationStatusId
}

// GetRegistrationStatusIdOk returns a tuple with the RegistrationStatusId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetRegistrationStatusIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RegistrationStatusId) {
		return nil, false
	}
	return o.RegistrationStatusId, true
}

// HasRegistrationStatusId returns a boolean if a field has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) HasRegistrationStatusId() bool {
	if o != nil && !IsNil(o.RegistrationStatusId) {
		return true
	}

	return false
}

// SetRegistrationStatusId gets a reference to the given int32 and assigns it to the RegistrationStatusId field.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) SetRegistrationStatusId(v int32) {
	o.RegistrationStatusId = &v
}

// GetRegistrationEntityId returns the RegistrationEntityId field value if set, zero value otherwise.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetRegistrationEntityId() int32 {
	if o == nil || IsNil(o.RegistrationEntityId) {
		var ret int32
		return ret
	}
	return *o.RegistrationEntityId
}

// GetRegistrationEntityIdOk returns a tuple with the RegistrationEntityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetRegistrationEntityIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RegistrationEntityId) {
		return nil, false
	}
	return o.RegistrationEntityId, true
}

// HasRegistrationEntityId returns a boolean if a field has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) HasRegistrationEntityId() bool {
	if o != nil && !IsNil(o.RegistrationEntityId) {
		return true
	}

	return false
}

// SetRegistrationEntityId gets a reference to the given int32 and assigns it to the RegistrationEntityId field.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) SetRegistrationEntityId(v int32) {
	o.RegistrationEntityId = &v
}

// GetJotformId returns the JotformId field value if set, zero value otherwise.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetJotformId() int32 {
	if o == nil || IsNil(o.JotformId) {
		var ret int32
		return ret
	}
	return *o.JotformId
}

// GetJotformIdOk returns a tuple with the JotformId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) GetJotformIdOk() (*int32, bool) {
	if o == nil || IsNil(o.JotformId) {
		return nil, false
	}
	return o.JotformId, true
}

// HasJotformId returns a boolean if a field has been set.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) HasJotformId() bool {
	if o != nil && !IsNil(o.JotformId) {
		return true
	}

	return false
}

// SetJotformId gets a reference to the given int32 and assigns it to the JotformId field.
func (o *CalculateSmsPriceDataSummaryCountriesInnerCountry) SetJotformId(v int32) {
	o.JotformId = &v
}

func (o CalculateSmsPriceDataSummaryCountriesInnerCountry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalculateSmsPriceDataSummaryCountriesInnerCountry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RegistrationType) {
		toSerialize["registration_type"] = o.RegistrationType
	}
	if !IsNil(o.ReceipientCount) {
		toSerialize["receipient_count"] = o.ReceipientCount
	}
	if !IsNil(o.UsableSenderId) {
		toSerialize["usable_sender_id"] = o.UsableSenderId
	}
	if !IsNil(o.Selected) {
		toSerialize["selected"] = o.Selected
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Regulation) {
		toSerialize["regulation"] = o.Regulation
	}
	if !IsNil(o.RegistrationStatusId) {
		toSerialize["registration_status_id"] = o.RegistrationStatusId
	}
	if !IsNil(o.RegistrationEntityId) {
		toSerialize["registration_entity_id"] = o.RegistrationEntityId
	}
	if !IsNil(o.JotformId) {
		toSerialize["jotform_id"] = o.JotformId
	}
	return toSerialize, nil
}

type NullableCalculateSmsPriceDataSummaryCountriesInnerCountry struct {
	value *CalculateSmsPriceDataSummaryCountriesInnerCountry
	isSet bool
}

func (v NullableCalculateSmsPriceDataSummaryCountriesInnerCountry) Get() *CalculateSmsPriceDataSummaryCountriesInnerCountry {
	return v.value
}

func (v *NullableCalculateSmsPriceDataSummaryCountriesInnerCountry) Set(val *CalculateSmsPriceDataSummaryCountriesInnerCountry) {
	v.value = val
	v.isSet = true
}

func (v NullableCalculateSmsPriceDataSummaryCountriesInnerCountry) IsSet() bool {
	return v.isSet
}

func (v *NullableCalculateSmsPriceDataSummaryCountriesInnerCountry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalculateSmsPriceDataSummaryCountriesInnerCountry(val *CalculateSmsPriceDataSummaryCountriesInnerCountry) *NullableCalculateSmsPriceDataSummaryCountriesInnerCountry {
	return &NullableCalculateSmsPriceDataSummaryCountriesInnerCountry{value: val, isSet: true}
}

func (v NullableCalculateSmsPriceDataSummaryCountriesInnerCountry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalculateSmsPriceDataSummaryCountriesInnerCountry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


