/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the CalculateEmailCampaignPriceDataData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalculateEmailCampaignPriceDataData{}

// CalculateEmailCampaignPriceDataData struct for CalculateEmailCampaignPriceDataData
type CalculateEmailCampaignPriceDataData struct {
	// Name.
	Name *string `json:"name,omitempty"`
	// Your template subject.
	Subject *string `json:"subject,omitempty"`
	// The allowed email address id.
	FromEmailAddressId *float32 `json:"from_email_address_id,omitempty"`
	// Your sender name.
	FromName *string `json:"from_name,omitempty"`
	// Your message.
	Body *string `json:"body,omitempty"`
	// Your list id.
	ListId *float32 `json:"list_id,omitempty"`
}

// NewCalculateEmailCampaignPriceDataData instantiates a new CalculateEmailCampaignPriceDataData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalculateEmailCampaignPriceDataData() *CalculateEmailCampaignPriceDataData {
	this := CalculateEmailCampaignPriceDataData{}
	return &this
}

// NewCalculateEmailCampaignPriceDataDataWithDefaults instantiates a new CalculateEmailCampaignPriceDataData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalculateEmailCampaignPriceDataDataWithDefaults() *CalculateEmailCampaignPriceDataData {
	this := CalculateEmailCampaignPriceDataData{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CalculateEmailCampaignPriceDataData) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateEmailCampaignPriceDataData) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CalculateEmailCampaignPriceDataData) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CalculateEmailCampaignPriceDataData) SetName(v string) {
	o.Name = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *CalculateEmailCampaignPriceDataData) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateEmailCampaignPriceDataData) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *CalculateEmailCampaignPriceDataData) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *CalculateEmailCampaignPriceDataData) SetSubject(v string) {
	o.Subject = &v
}

// GetFromEmailAddressId returns the FromEmailAddressId field value if set, zero value otherwise.
func (o *CalculateEmailCampaignPriceDataData) GetFromEmailAddressId() float32 {
	if o == nil || IsNil(o.FromEmailAddressId) {
		var ret float32
		return ret
	}
	return *o.FromEmailAddressId
}

// GetFromEmailAddressIdOk returns a tuple with the FromEmailAddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateEmailCampaignPriceDataData) GetFromEmailAddressIdOk() (*float32, bool) {
	if o == nil || IsNil(o.FromEmailAddressId) {
		return nil, false
	}
	return o.FromEmailAddressId, true
}

// HasFromEmailAddressId returns a boolean if a field has been set.
func (o *CalculateEmailCampaignPriceDataData) HasFromEmailAddressId() bool {
	if o != nil && !IsNil(o.FromEmailAddressId) {
		return true
	}

	return false
}

// SetFromEmailAddressId gets a reference to the given float32 and assigns it to the FromEmailAddressId field.
func (o *CalculateEmailCampaignPriceDataData) SetFromEmailAddressId(v float32) {
	o.FromEmailAddressId = &v
}

// GetFromName returns the FromName field value if set, zero value otherwise.
func (o *CalculateEmailCampaignPriceDataData) GetFromName() string {
	if o == nil || IsNil(o.FromName) {
		var ret string
		return ret
	}
	return *o.FromName
}

// GetFromNameOk returns a tuple with the FromName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateEmailCampaignPriceDataData) GetFromNameOk() (*string, bool) {
	if o == nil || IsNil(o.FromName) {
		return nil, false
	}
	return o.FromName, true
}

// HasFromName returns a boolean if a field has been set.
func (o *CalculateEmailCampaignPriceDataData) HasFromName() bool {
	if o != nil && !IsNil(o.FromName) {
		return true
	}

	return false
}

// SetFromName gets a reference to the given string and assigns it to the FromName field.
func (o *CalculateEmailCampaignPriceDataData) SetFromName(v string) {
	o.FromName = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *CalculateEmailCampaignPriceDataData) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateEmailCampaignPriceDataData) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *CalculateEmailCampaignPriceDataData) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *CalculateEmailCampaignPriceDataData) SetBody(v string) {
	o.Body = &v
}

// GetListId returns the ListId field value if set, zero value otherwise.
func (o *CalculateEmailCampaignPriceDataData) GetListId() float32 {
	if o == nil || IsNil(o.ListId) {
		var ret float32
		return ret
	}
	return *o.ListId
}

// GetListIdOk returns a tuple with the ListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateEmailCampaignPriceDataData) GetListIdOk() (*float32, bool) {
	if o == nil || IsNil(o.ListId) {
		return nil, false
	}
	return o.ListId, true
}

// HasListId returns a boolean if a field has been set.
func (o *CalculateEmailCampaignPriceDataData) HasListId() bool {
	if o != nil && !IsNil(o.ListId) {
		return true
	}

	return false
}

// SetListId gets a reference to the given float32 and assigns it to the ListId field.
func (o *CalculateEmailCampaignPriceDataData) SetListId(v float32) {
	o.ListId = &v
}

func (o CalculateEmailCampaignPriceDataData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalculateEmailCampaignPriceDataData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.FromEmailAddressId) {
		toSerialize["from_email_address_id"] = o.FromEmailAddressId
	}
	if !IsNil(o.FromName) {
		toSerialize["from_name"] = o.FromName
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.ListId) {
		toSerialize["list_id"] = o.ListId
	}
	return toSerialize, nil
}

type NullableCalculateEmailCampaignPriceDataData struct {
	value *CalculateEmailCampaignPriceDataData
	isSet bool
}

func (v NullableCalculateEmailCampaignPriceDataData) Get() *CalculateEmailCampaignPriceDataData {
	return v.value
}

func (v *NullableCalculateEmailCampaignPriceDataData) Set(val *CalculateEmailCampaignPriceDataData) {
	v.value = val
	v.isSet = true
}

func (v NullableCalculateEmailCampaignPriceDataData) IsSet() bool {
	return v.isSet
}

func (v *NullableCalculateEmailCampaignPriceDataData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalculateEmailCampaignPriceDataData(val *CalculateEmailCampaignPriceDataData) *NullableCalculateEmailCampaignPriceDataData {
	return &NullableCalculateEmailCampaignPriceDataData{value: val, isSet: true}
}

func (v NullableCalculateEmailCampaignPriceDataData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalculateEmailCampaignPriceDataData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


