/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the SmsDeliveryReceiptRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SmsDeliveryReceiptRule{}

// SmsDeliveryReceiptRule struct for SmsDeliveryReceiptRule
type SmsDeliveryReceiptRule struct {
	// The ID of the receipt rule.
	ReceiptRuleId *int32 `json:"receipt_rule_id,omitempty"`
	// The name of the receipt rule.
	RuleName *string `json:"rule_name,omitempty"`
	// The type of match.
	MatchType *int32 `json:"match_type,omitempty"`
	// The type of action.
	Action *string `json:"action,omitempty"`
	// The address associated with the action.
	ActionAddress *string `json:"action_address,omitempty"`
	// Indicates whether the rule is enabled.
	Enabled *int32 `json:"enabled,omitempty"`
}

// NewSmsDeliveryReceiptRule instantiates a new SmsDeliveryReceiptRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmsDeliveryReceiptRule() *SmsDeliveryReceiptRule {
	this := SmsDeliveryReceiptRule{}
	return &this
}

// NewSmsDeliveryReceiptRuleWithDefaults instantiates a new SmsDeliveryReceiptRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmsDeliveryReceiptRuleWithDefaults() *SmsDeliveryReceiptRule {
	this := SmsDeliveryReceiptRule{}
	return &this
}

// GetReceiptRuleId returns the ReceiptRuleId field value if set, zero value otherwise.
func (o *SmsDeliveryReceiptRule) GetReceiptRuleId() int32 {
	if o == nil || IsNil(o.ReceiptRuleId) {
		var ret int32
		return ret
	}
	return *o.ReceiptRuleId
}

// GetReceiptRuleIdOk returns a tuple with the ReceiptRuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsDeliveryReceiptRule) GetReceiptRuleIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ReceiptRuleId) {
		return nil, false
	}
	return o.ReceiptRuleId, true
}

// HasReceiptRuleId returns a boolean if a field has been set.
func (o *SmsDeliveryReceiptRule) HasReceiptRuleId() bool {
	if o != nil && !IsNil(o.ReceiptRuleId) {
		return true
	}

	return false
}

// SetReceiptRuleId gets a reference to the given int32 and assigns it to the ReceiptRuleId field.
func (o *SmsDeliveryReceiptRule) SetReceiptRuleId(v int32) {
	o.ReceiptRuleId = &v
}

// GetRuleName returns the RuleName field value if set, zero value otherwise.
func (o *SmsDeliveryReceiptRule) GetRuleName() string {
	if o == nil || IsNil(o.RuleName) {
		var ret string
		return ret
	}
	return *o.RuleName
}

// GetRuleNameOk returns a tuple with the RuleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsDeliveryReceiptRule) GetRuleNameOk() (*string, bool) {
	if o == nil || IsNil(o.RuleName) {
		return nil, false
	}
	return o.RuleName, true
}

// HasRuleName returns a boolean if a field has been set.
func (o *SmsDeliveryReceiptRule) HasRuleName() bool {
	if o != nil && !IsNil(o.RuleName) {
		return true
	}

	return false
}

// SetRuleName gets a reference to the given string and assigns it to the RuleName field.
func (o *SmsDeliveryReceiptRule) SetRuleName(v string) {
	o.RuleName = &v
}

// GetMatchType returns the MatchType field value if set, zero value otherwise.
func (o *SmsDeliveryReceiptRule) GetMatchType() int32 {
	if o == nil || IsNil(o.MatchType) {
		var ret int32
		return ret
	}
	return *o.MatchType
}

// GetMatchTypeOk returns a tuple with the MatchType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsDeliveryReceiptRule) GetMatchTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.MatchType) {
		return nil, false
	}
	return o.MatchType, true
}

// HasMatchType returns a boolean if a field has been set.
func (o *SmsDeliveryReceiptRule) HasMatchType() bool {
	if o != nil && !IsNil(o.MatchType) {
		return true
	}

	return false
}

// SetMatchType gets a reference to the given int32 and assigns it to the MatchType field.
func (o *SmsDeliveryReceiptRule) SetMatchType(v int32) {
	o.MatchType = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *SmsDeliveryReceiptRule) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsDeliveryReceiptRule) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *SmsDeliveryReceiptRule) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *SmsDeliveryReceiptRule) SetAction(v string) {
	o.Action = &v
}

// GetActionAddress returns the ActionAddress field value if set, zero value otherwise.
func (o *SmsDeliveryReceiptRule) GetActionAddress() string {
	if o == nil || IsNil(o.ActionAddress) {
		var ret string
		return ret
	}
	return *o.ActionAddress
}

// GetActionAddressOk returns a tuple with the ActionAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsDeliveryReceiptRule) GetActionAddressOk() (*string, bool) {
	if o == nil || IsNil(o.ActionAddress) {
		return nil, false
	}
	return o.ActionAddress, true
}

// HasActionAddress returns a boolean if a field has been set.
func (o *SmsDeliveryReceiptRule) HasActionAddress() bool {
	if o != nil && !IsNil(o.ActionAddress) {
		return true
	}

	return false
}

// SetActionAddress gets a reference to the given string and assigns it to the ActionAddress field.
func (o *SmsDeliveryReceiptRule) SetActionAddress(v string) {
	o.ActionAddress = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *SmsDeliveryReceiptRule) GetEnabled() int32 {
	if o == nil || IsNil(o.Enabled) {
		var ret int32
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsDeliveryReceiptRule) GetEnabledOk() (*int32, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *SmsDeliveryReceiptRule) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given int32 and assigns it to the Enabled field.
func (o *SmsDeliveryReceiptRule) SetEnabled(v int32) {
	o.Enabled = &v
}

func (o SmsDeliveryReceiptRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SmsDeliveryReceiptRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ReceiptRuleId) {
		toSerialize["receipt_rule_id"] = o.ReceiptRuleId
	}
	if !IsNil(o.RuleName) {
		toSerialize["rule_name"] = o.RuleName
	}
	if !IsNil(o.MatchType) {
		toSerialize["match_type"] = o.MatchType
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.ActionAddress) {
		toSerialize["action_address"] = o.ActionAddress
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableSmsDeliveryReceiptRule struct {
	value *SmsDeliveryReceiptRule
	isSet bool
}

func (v NullableSmsDeliveryReceiptRule) Get() *SmsDeliveryReceiptRule {
	return v.value
}

func (v *NullableSmsDeliveryReceiptRule) Set(val *SmsDeliveryReceiptRule) {
	v.value = val
	v.isSet = true
}

func (v NullableSmsDeliveryReceiptRule) IsSet() bool {
	return v.isSet
}

func (v *NullableSmsDeliveryReceiptRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmsDeliveryReceiptRule(val *SmsDeliveryReceiptRule) *NullableSmsDeliveryReceiptRule {
	return &NullableSmsDeliveryReceiptRule{value: val, isSet: true}
}

func (v NullableSmsDeliveryReceiptRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmsDeliveryReceiptRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


