/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the PurchaseDedicatedNumberData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PurchaseDedicatedNumberData{}

// PurchaseDedicatedNumberData struct for PurchaseDedicatedNumberData
type PurchaseDedicatedNumberData struct {
	// The new dedicated number.
	DedicatedNumber *string `json:"dedicated_number,omitempty"`
	// The country code of the new dedicated number.
	Country *string `json:"country,omitempty"`
	// The total price of the new dedicated number.
	PriceTotal *string `json:"price_total,omitempty"`
	// The setup price of the new dedicated number.
	PriceSetup *string `json:"_price_setup,omitempty"`
	// The monthly price of the new dedicated number.
	PriceMonthly *string `json:"_price_monthly,omitempty"`
	Currency *Currency `json:"_currency,omitempty"`
}

// NewPurchaseDedicatedNumberData instantiates a new PurchaseDedicatedNumberData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPurchaseDedicatedNumberData() *PurchaseDedicatedNumberData {
	this := PurchaseDedicatedNumberData{}
	return &this
}

// NewPurchaseDedicatedNumberDataWithDefaults instantiates a new PurchaseDedicatedNumberData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPurchaseDedicatedNumberDataWithDefaults() *PurchaseDedicatedNumberData {
	this := PurchaseDedicatedNumberData{}
	return &this
}

// GetDedicatedNumber returns the DedicatedNumber field value if set, zero value otherwise.
func (o *PurchaseDedicatedNumberData) GetDedicatedNumber() string {
	if o == nil || IsNil(o.DedicatedNumber) {
		var ret string
		return ret
	}
	return *o.DedicatedNumber
}

// GetDedicatedNumberOk returns a tuple with the DedicatedNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseDedicatedNumberData) GetDedicatedNumberOk() (*string, bool) {
	if o == nil || IsNil(o.DedicatedNumber) {
		return nil, false
	}
	return o.DedicatedNumber, true
}

// HasDedicatedNumber returns a boolean if a field has been set.
func (o *PurchaseDedicatedNumberData) HasDedicatedNumber() bool {
	if o != nil && !IsNil(o.DedicatedNumber) {
		return true
	}

	return false
}

// SetDedicatedNumber gets a reference to the given string and assigns it to the DedicatedNumber field.
func (o *PurchaseDedicatedNumberData) SetDedicatedNumber(v string) {
	o.DedicatedNumber = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *PurchaseDedicatedNumberData) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseDedicatedNumberData) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *PurchaseDedicatedNumberData) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *PurchaseDedicatedNumberData) SetCountry(v string) {
	o.Country = &v
}

// GetPriceTotal returns the PriceTotal field value if set, zero value otherwise.
func (o *PurchaseDedicatedNumberData) GetPriceTotal() string {
	if o == nil || IsNil(o.PriceTotal) {
		var ret string
		return ret
	}
	return *o.PriceTotal
}

// GetPriceTotalOk returns a tuple with the PriceTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseDedicatedNumberData) GetPriceTotalOk() (*string, bool) {
	if o == nil || IsNil(o.PriceTotal) {
		return nil, false
	}
	return o.PriceTotal, true
}

// HasPriceTotal returns a boolean if a field has been set.
func (o *PurchaseDedicatedNumberData) HasPriceTotal() bool {
	if o != nil && !IsNil(o.PriceTotal) {
		return true
	}

	return false
}

// SetPriceTotal gets a reference to the given string and assigns it to the PriceTotal field.
func (o *PurchaseDedicatedNumberData) SetPriceTotal(v string) {
	o.PriceTotal = &v
}

// GetPriceSetup returns the PriceSetup field value if set, zero value otherwise.
func (o *PurchaseDedicatedNumberData) GetPriceSetup() string {
	if o == nil || IsNil(o.PriceSetup) {
		var ret string
		return ret
	}
	return *o.PriceSetup
}

// GetPriceSetupOk returns a tuple with the PriceSetup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseDedicatedNumberData) GetPriceSetupOk() (*string, bool) {
	if o == nil || IsNil(o.PriceSetup) {
		return nil, false
	}
	return o.PriceSetup, true
}

// HasPriceSetup returns a boolean if a field has been set.
func (o *PurchaseDedicatedNumberData) HasPriceSetup() bool {
	if o != nil && !IsNil(o.PriceSetup) {
		return true
	}

	return false
}

// SetPriceSetup gets a reference to the given string and assigns it to the PriceSetup field.
func (o *PurchaseDedicatedNumberData) SetPriceSetup(v string) {
	o.PriceSetup = &v
}

// GetPriceMonthly returns the PriceMonthly field value if set, zero value otherwise.
func (o *PurchaseDedicatedNumberData) GetPriceMonthly() string {
	if o == nil || IsNil(o.PriceMonthly) {
		var ret string
		return ret
	}
	return *o.PriceMonthly
}

// GetPriceMonthlyOk returns a tuple with the PriceMonthly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseDedicatedNumberData) GetPriceMonthlyOk() (*string, bool) {
	if o == nil || IsNil(o.PriceMonthly) {
		return nil, false
	}
	return o.PriceMonthly, true
}

// HasPriceMonthly returns a boolean if a field has been set.
func (o *PurchaseDedicatedNumberData) HasPriceMonthly() bool {
	if o != nil && !IsNil(o.PriceMonthly) {
		return true
	}

	return false
}

// SetPriceMonthly gets a reference to the given string and assigns it to the PriceMonthly field.
func (o *PurchaseDedicatedNumberData) SetPriceMonthly(v string) {
	o.PriceMonthly = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *PurchaseDedicatedNumberData) GetCurrency() Currency {
	if o == nil || IsNil(o.Currency) {
		var ret Currency
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseDedicatedNumberData) GetCurrencyOk() (*Currency, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *PurchaseDedicatedNumberData) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given Currency and assigns it to the Currency field.
func (o *PurchaseDedicatedNumberData) SetCurrency(v Currency) {
	o.Currency = &v
}

func (o PurchaseDedicatedNumberData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PurchaseDedicatedNumberData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DedicatedNumber) {
		toSerialize["dedicated_number"] = o.DedicatedNumber
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.PriceTotal) {
		toSerialize["price_total"] = o.PriceTotal
	}
	if !IsNil(o.PriceSetup) {
		toSerialize["_price_setup"] = o.PriceSetup
	}
	if !IsNil(o.PriceMonthly) {
		toSerialize["_price_monthly"] = o.PriceMonthly
	}
	if !IsNil(o.Currency) {
		toSerialize["_currency"] = o.Currency
	}
	return toSerialize, nil
}

type NullablePurchaseDedicatedNumberData struct {
	value *PurchaseDedicatedNumberData
	isSet bool
}

func (v NullablePurchaseDedicatedNumberData) Get() *PurchaseDedicatedNumberData {
	return v.value
}

func (v *NullablePurchaseDedicatedNumberData) Set(val *PurchaseDedicatedNumberData) {
	v.value = val
	v.isSet = true
}

func (v NullablePurchaseDedicatedNumberData) IsSet() bool {
	return v.isSet
}

func (v *NullablePurchaseDedicatedNumberData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurchaseDedicatedNumberData(val *PurchaseDedicatedNumberData) *NullablePurchaseDedicatedNumberData {
	return &NullablePurchaseDedicatedNumberData{value: val, isSet: true}
}

func (v NullablePurchaseDedicatedNumberData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurchaseDedicatedNumberData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


