/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestAlphaTagRequestBusinessesInnerBusinessInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestAlphaTagRequestBusinessesInnerBusinessInfo{}

// RequestAlphaTagRequestBusinessesInnerBusinessInfo struct for RequestAlphaTagRequestBusinessesInnerBusinessInfo
type RequestAlphaTagRequestBusinessesInnerBusinessInfo struct {
	// Business website URL
	Website string `json:"website"`
	// E.164 or local format
	PhoneNumber string `json:"phone_number"`
}

type _RequestAlphaTagRequestBusinessesInnerBusinessInfo RequestAlphaTagRequestBusinessesInnerBusinessInfo

// NewRequestAlphaTagRequestBusinessesInnerBusinessInfo instantiates a new RequestAlphaTagRequestBusinessesInnerBusinessInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestAlphaTagRequestBusinessesInnerBusinessInfo(website string, phoneNumber string) *RequestAlphaTagRequestBusinessesInnerBusinessInfo {
	this := RequestAlphaTagRequestBusinessesInnerBusinessInfo{}
	this.Website = website
	this.PhoneNumber = phoneNumber
	return &this
}

// NewRequestAlphaTagRequestBusinessesInnerBusinessInfoWithDefaults instantiates a new RequestAlphaTagRequestBusinessesInnerBusinessInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestAlphaTagRequestBusinessesInnerBusinessInfoWithDefaults() *RequestAlphaTagRequestBusinessesInnerBusinessInfo {
	this := RequestAlphaTagRequestBusinessesInnerBusinessInfo{}
	return &this
}

// GetWebsite returns the Website field value
func (o *RequestAlphaTagRequestBusinessesInnerBusinessInfo) GetWebsite() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Website
}

// GetWebsiteOk returns a tuple with the Website field value
// and a boolean to check if the value has been set.
func (o *RequestAlphaTagRequestBusinessesInnerBusinessInfo) GetWebsiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Website, true
}

// SetWebsite sets field value
func (o *RequestAlphaTagRequestBusinessesInnerBusinessInfo) SetWebsite(v string) {
	o.Website = v
}

// GetPhoneNumber returns the PhoneNumber field value
func (o *RequestAlphaTagRequestBusinessesInnerBusinessInfo) GetPhoneNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
func (o *RequestAlphaTagRequestBusinessesInnerBusinessInfo) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// SetPhoneNumber sets field value
func (o *RequestAlphaTagRequestBusinessesInnerBusinessInfo) SetPhoneNumber(v string) {
	o.PhoneNumber = v
}

func (o RequestAlphaTagRequestBusinessesInnerBusinessInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestAlphaTagRequestBusinessesInnerBusinessInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["website"] = o.Website
	toSerialize["phone_number"] = o.PhoneNumber
	return toSerialize, nil
}

func (o *RequestAlphaTagRequestBusinessesInnerBusinessInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"website",
		"phone_number",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestAlphaTagRequestBusinessesInnerBusinessInfo := _RequestAlphaTagRequestBusinessesInnerBusinessInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestAlphaTagRequestBusinessesInnerBusinessInfo)

	if err != nil {
		return err
	}

	*o = RequestAlphaTagRequestBusinessesInnerBusinessInfo(varRequestAlphaTagRequestBusinessesInnerBusinessInfo)

	return err
}

type NullableRequestAlphaTagRequestBusinessesInnerBusinessInfo struct {
	value *RequestAlphaTagRequestBusinessesInnerBusinessInfo
	isSet bool
}

func (v NullableRequestAlphaTagRequestBusinessesInnerBusinessInfo) Get() *RequestAlphaTagRequestBusinessesInnerBusinessInfo {
	return v.value
}

func (v *NullableRequestAlphaTagRequestBusinessesInnerBusinessInfo) Set(val *RequestAlphaTagRequestBusinessesInnerBusinessInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestAlphaTagRequestBusinessesInnerBusinessInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestAlphaTagRequestBusinessesInnerBusinessInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestAlphaTagRequestBusinessesInnerBusinessInfo(val *RequestAlphaTagRequestBusinessesInnerBusinessInfo) *NullableRequestAlphaTagRequestBusinessesInnerBusinessInfo {
	return &NullableRequestAlphaTagRequestBusinessesInnerBusinessInfo{value: val, isSet: true}
}

func (v NullableRequestAlphaTagRequestBusinessesInnerBusinessInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestAlphaTagRequestBusinessesInnerBusinessInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


