/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the SendMmsRequestMessagesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendMmsRequestMessagesInner{}

// SendMmsRequestMessagesInner struct for SendMmsRequestMessagesInner
type SendMmsRequestMessagesInner struct {
	Source *string `json:"source,omitempty"`
	To *string `json:"to,omitempty"`
	From *string `json:"from,omitempty"`
	Subject *string `json:"subject,omitempty"`
	Body *string `json:"body,omitempty"`
	Schedule *int32 `json:"schedule,omitempty"`
}

// NewSendMmsRequestMessagesInner instantiates a new SendMmsRequestMessagesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendMmsRequestMessagesInner() *SendMmsRequestMessagesInner {
	this := SendMmsRequestMessagesInner{}
	var source string = "sdk-go"
	this.Source = &source
	return &this
}

// NewSendMmsRequestMessagesInnerWithDefaults instantiates a new SendMmsRequestMessagesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendMmsRequestMessagesInnerWithDefaults() *SendMmsRequestMessagesInner {
	this := SendMmsRequestMessagesInner{}
	var source string = "sdk-go"
	this.Source = &source
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *SendMmsRequestMessagesInner) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendMmsRequestMessagesInner) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *SendMmsRequestMessagesInner) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *SendMmsRequestMessagesInner) SetSource(v string) {
	o.Source = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *SendMmsRequestMessagesInner) GetTo() string {
	if o == nil || IsNil(o.To) {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendMmsRequestMessagesInner) GetToOk() (*string, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *SendMmsRequestMessagesInner) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *SendMmsRequestMessagesInner) SetTo(v string) {
	o.To = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *SendMmsRequestMessagesInner) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendMmsRequestMessagesInner) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *SendMmsRequestMessagesInner) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *SendMmsRequestMessagesInner) SetFrom(v string) {
	o.From = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *SendMmsRequestMessagesInner) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendMmsRequestMessagesInner) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *SendMmsRequestMessagesInner) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *SendMmsRequestMessagesInner) SetSubject(v string) {
	o.Subject = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *SendMmsRequestMessagesInner) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendMmsRequestMessagesInner) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *SendMmsRequestMessagesInner) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *SendMmsRequestMessagesInner) SetBody(v string) {
	o.Body = &v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *SendMmsRequestMessagesInner) GetSchedule() int32 {
	if o == nil || IsNil(o.Schedule) {
		var ret int32
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendMmsRequestMessagesInner) GetScheduleOk() (*int32, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *SendMmsRequestMessagesInner) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given int32 and assigns it to the Schedule field.
func (o *SendMmsRequestMessagesInner) SetSchedule(v int32) {
	o.Schedule = &v
}

func (o SendMmsRequestMessagesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendMmsRequestMessagesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	return toSerialize, nil
}

type NullableSendMmsRequestMessagesInner struct {
	value *SendMmsRequestMessagesInner
	isSet bool
}

func (v NullableSendMmsRequestMessagesInner) Get() *SendMmsRequestMessagesInner {
	return v.value
}

func (v *NullableSendMmsRequestMessagesInner) Set(val *SendMmsRequestMessagesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSendMmsRequestMessagesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSendMmsRequestMessagesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendMmsRequestMessagesInner(val *SendMmsRequestMessagesInner) *NullableSendMmsRequestMessagesInner {
	return &NullableSendMmsRequestMessagesInner{value: val, isSet: true}
}

func (v NullableSendMmsRequestMessagesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendMmsRequestMessagesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


