/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the GetTracking type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTracking{}

// GetTracking struct for GetTracking
type GetTracking struct {
	// Total number of short URLs associated with the long URL ID
	Total *float32 `json:"total,omitempty"`
	// The limit of tracking data per page
	PerPage *float32 `json:"per_page,omitempty"`
	// The number of data in the current page
	CurrentPageSize *float32 `json:"current_page_size,omitempty"`
	// Link to the previous page. This attribute will not be present if there is no previous page.
	PrevPageUrl *string `json:"prev_page_url,omitempty"`
	// Link to the next page. This attribute will not be present if there is no next page.
	NextPageUrl *string `json:"next_page_url,omitempty"`
	// Tracking data of the short URLs associated with the specified long URL ID. Note that only the data from the most recent click of the recipient (country, region, device, browser, and os) is recorded.
	Data []GetTrackingDataInner `json:"data,omitempty"`
}

// NewGetTracking instantiates a new GetTracking object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTracking() *GetTracking {
	this := GetTracking{}
	return &this
}

// NewGetTrackingWithDefaults instantiates a new GetTracking object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTrackingWithDefaults() *GetTracking {
	this := GetTracking{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetTracking) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTracking) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetTracking) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *GetTracking) SetTotal(v float32) {
	o.Total = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *GetTracking) GetPerPage() float32 {
	if o == nil || IsNil(o.PerPage) {
		var ret float32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTracking) GetPerPageOk() (*float32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *GetTracking) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given float32 and assigns it to the PerPage field.
func (o *GetTracking) SetPerPage(v float32) {
	o.PerPage = &v
}

// GetCurrentPageSize returns the CurrentPageSize field value if set, zero value otherwise.
func (o *GetTracking) GetCurrentPageSize() float32 {
	if o == nil || IsNil(o.CurrentPageSize) {
		var ret float32
		return ret
	}
	return *o.CurrentPageSize
}

// GetCurrentPageSizeOk returns a tuple with the CurrentPageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTracking) GetCurrentPageSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.CurrentPageSize) {
		return nil, false
	}
	return o.CurrentPageSize, true
}

// HasCurrentPageSize returns a boolean if a field has been set.
func (o *GetTracking) HasCurrentPageSize() bool {
	if o != nil && !IsNil(o.CurrentPageSize) {
		return true
	}

	return false
}

// SetCurrentPageSize gets a reference to the given float32 and assigns it to the CurrentPageSize field.
func (o *GetTracking) SetCurrentPageSize(v float32) {
	o.CurrentPageSize = &v
}

// GetPrevPageUrl returns the PrevPageUrl field value if set, zero value otherwise.
func (o *GetTracking) GetPrevPageUrl() string {
	if o == nil || IsNil(o.PrevPageUrl) {
		var ret string
		return ret
	}
	return *o.PrevPageUrl
}

// GetPrevPageUrlOk returns a tuple with the PrevPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTracking) GetPrevPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PrevPageUrl) {
		return nil, false
	}
	return o.PrevPageUrl, true
}

// HasPrevPageUrl returns a boolean if a field has been set.
func (o *GetTracking) HasPrevPageUrl() bool {
	if o != nil && !IsNil(o.PrevPageUrl) {
		return true
	}

	return false
}

// SetPrevPageUrl gets a reference to the given string and assigns it to the PrevPageUrl field.
func (o *GetTracking) SetPrevPageUrl(v string) {
	o.PrevPageUrl = &v
}

// GetNextPageUrl returns the NextPageUrl field value if set, zero value otherwise.
func (o *GetTracking) GetNextPageUrl() string {
	if o == nil || IsNil(o.NextPageUrl) {
		var ret string
		return ret
	}
	return *o.NextPageUrl
}

// GetNextPageUrlOk returns a tuple with the NextPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTracking) GetNextPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageUrl) {
		return nil, false
	}
	return o.NextPageUrl, true
}

// HasNextPageUrl returns a boolean if a field has been set.
func (o *GetTracking) HasNextPageUrl() bool {
	if o != nil && !IsNil(o.NextPageUrl) {
		return true
	}

	return false
}

// SetNextPageUrl gets a reference to the given string and assigns it to the NextPageUrl field.
func (o *GetTracking) SetNextPageUrl(v string) {
	o.NextPageUrl = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetTracking) GetData() []GetTrackingDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetTrackingDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTracking) GetDataOk() ([]GetTrackingDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetTracking) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetTrackingDataInner and assigns it to the Data field.
func (o *GetTracking) SetData(v []GetTrackingDataInner) {
	o.Data = v
}

func (o GetTracking) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTracking) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	if !IsNil(o.CurrentPageSize) {
		toSerialize["current_page_size"] = o.CurrentPageSize
	}
	if !IsNil(o.PrevPageUrl) {
		toSerialize["prev_page_url"] = o.PrevPageUrl
	}
	if !IsNil(o.NextPageUrl) {
		toSerialize["next_page_url"] = o.NextPageUrl
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetTracking struct {
	value *GetTracking
	isSet bool
}

func (v NullableGetTracking) Get() *GetTracking {
	return v.value
}

func (v *NullableGetTracking) Set(val *GetTracking) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTracking) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTracking) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTracking(val *GetTracking) *NullableGetTracking {
	return &NullableGetTracking{value: val, isSet: true}
}

func (v NullableGetTracking) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTracking) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


