/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the ViewSmsStatisticsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewSmsStatisticsData{}

// ViewSmsStatisticsData struct for ViewSmsStatisticsData
type ViewSmsStatisticsData struct {
	Total *ViewSmsStatisticsDataTotal `json:"total,omitempty"`
	Stats []ViewSmsStatisticsDataStatsInner `json:"stats,omitempty"`
	Currency *Currency `json:"_currency,omitempty"`
}

// NewViewSmsStatisticsData instantiates a new ViewSmsStatisticsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewSmsStatisticsData() *ViewSmsStatisticsData {
	this := ViewSmsStatisticsData{}
	return &this
}

// NewViewSmsStatisticsDataWithDefaults instantiates a new ViewSmsStatisticsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewSmsStatisticsDataWithDefaults() *ViewSmsStatisticsData {
	this := ViewSmsStatisticsData{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ViewSmsStatisticsData) GetTotal() ViewSmsStatisticsDataTotal {
	if o == nil || IsNil(o.Total) {
		var ret ViewSmsStatisticsDataTotal
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewSmsStatisticsData) GetTotalOk() (*ViewSmsStatisticsDataTotal, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ViewSmsStatisticsData) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given ViewSmsStatisticsDataTotal and assigns it to the Total field.
func (o *ViewSmsStatisticsData) SetTotal(v ViewSmsStatisticsDataTotal) {
	o.Total = &v
}

// GetStats returns the Stats field value if set, zero value otherwise.
func (o *ViewSmsStatisticsData) GetStats() []ViewSmsStatisticsDataStatsInner {
	if o == nil || IsNil(o.Stats) {
		var ret []ViewSmsStatisticsDataStatsInner
		return ret
	}
	return o.Stats
}

// GetStatsOk returns a tuple with the Stats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewSmsStatisticsData) GetStatsOk() ([]ViewSmsStatisticsDataStatsInner, bool) {
	if o == nil || IsNil(o.Stats) {
		return nil, false
	}
	return o.Stats, true
}

// HasStats returns a boolean if a field has been set.
func (o *ViewSmsStatisticsData) HasStats() bool {
	if o != nil && !IsNil(o.Stats) {
		return true
	}

	return false
}

// SetStats gets a reference to the given []ViewSmsStatisticsDataStatsInner and assigns it to the Stats field.
func (o *ViewSmsStatisticsData) SetStats(v []ViewSmsStatisticsDataStatsInner) {
	o.Stats = v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ViewSmsStatisticsData) GetCurrency() Currency {
	if o == nil || IsNil(o.Currency) {
		var ret Currency
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewSmsStatisticsData) GetCurrencyOk() (*Currency, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ViewSmsStatisticsData) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given Currency and assigns it to the Currency field.
func (o *ViewSmsStatisticsData) SetCurrency(v Currency) {
	o.Currency = &v
}

func (o ViewSmsStatisticsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewSmsStatisticsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Stats) {
		toSerialize["stats"] = o.Stats
	}
	if !IsNil(o.Currency) {
		toSerialize["_currency"] = o.Currency
	}
	return toSerialize, nil
}

type NullableViewSmsStatisticsData struct {
	value *ViewSmsStatisticsData
	isSet bool
}

func (v NullableViewSmsStatisticsData) Get() *ViewSmsStatisticsData {
	return v.value
}

func (v *NullableViewSmsStatisticsData) Set(val *ViewSmsStatisticsData) {
	v.value = val
	v.isSet = true
}

func (v NullableViewSmsStatisticsData) IsSet() bool {
	return v.isSet
}

func (v *NullableViewSmsStatisticsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewSmsStatisticsData(val *ViewSmsStatisticsData) *NullableViewSmsStatisticsData {
	return &NullableViewSmsStatisticsData{value: val, isSet: true}
}

func (v NullableViewSmsStatisticsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewSmsStatisticsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


