/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the VoiceMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoiceMessage{}

// VoiceMessage struct for VoiceMessage
type VoiceMessage struct {
	// The date.
	Date *float32 `json:"date,omitempty"`
	// The recipient's phone number.
	To *string `json:"to,omitempty"`
	// The type of recipient.
	ToType *string `json:"to_type,omitempty"`
	// The body of the message.
	Body *string `json:"body,omitempty"`
	// The sender's phone number.
	From NullableString `json:"from,omitempty"`
	// The language of the message.
	Lang *string `json:"lang,omitempty"`
	// The voice of the message.
	Voice *string `json:"voice,omitempty"`
	// The timestamp when the message should be sent.
	Schedule *int32 `json:"schedule,omitempty"`
	// The ID of the message.
	MessageId *string `json:"message_id,omitempty"`
	// The number of parts in the message.
	MessageParts *int32 `json:"message_parts,omitempty"`
	// The price of the message.
	MessagePrice *string `json:"message_price,omitempty"`
	// The custom string of the message.
	CustomString *string `json:"custom_string,omitempty"`
	// The ID of the user.
	UserId *float32 `json:"user_id,omitempty"`
	// The ID of the subaccount.
	SubaccountId *float32 `json:"subaccount_id,omitempty"`
	// The country code of the message.
	Country *string `json:"country,omitempty"`
	// The require input of the message.
	RequireInput *float32 `json:"require_input,omitempty"`
	// The machine detection of the message.
	MachineDetection *float32 `json:"machine_detection,omitempty"`
	// The status of the message.
	Status *string `json:"status,omitempty"`
}

// NewVoiceMessage instantiates a new VoiceMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoiceMessage() *VoiceMessage {
	this := VoiceMessage{}
	return &this
}

// NewVoiceMessageWithDefaults instantiates a new VoiceMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoiceMessageWithDefaults() *VoiceMessage {
	this := VoiceMessage{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *VoiceMessage) GetDate() float32 {
	if o == nil || IsNil(o.Date) {
		var ret float32
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetDateOk() (*float32, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *VoiceMessage) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given float32 and assigns it to the Date field.
func (o *VoiceMessage) SetDate(v float32) {
	o.Date = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *VoiceMessage) GetTo() string {
	if o == nil || IsNil(o.To) {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetToOk() (*string, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *VoiceMessage) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *VoiceMessage) SetTo(v string) {
	o.To = &v
}

// GetToType returns the ToType field value if set, zero value otherwise.
func (o *VoiceMessage) GetToType() string {
	if o == nil || IsNil(o.ToType) {
		var ret string
		return ret
	}
	return *o.ToType
}

// GetToTypeOk returns a tuple with the ToType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetToTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ToType) {
		return nil, false
	}
	return o.ToType, true
}

// HasToType returns a boolean if a field has been set.
func (o *VoiceMessage) HasToType() bool {
	if o != nil && !IsNil(o.ToType) {
		return true
	}

	return false
}

// SetToType gets a reference to the given string and assigns it to the ToType field.
func (o *VoiceMessage) SetToType(v string) {
	o.ToType = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *VoiceMessage) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *VoiceMessage) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *VoiceMessage) SetBody(v string) {
	o.Body = &v
}

// GetFrom returns the From field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VoiceMessage) GetFrom() string {
	if o == nil || IsNil(o.From.Get()) {
		var ret string
		return ret
	}
	return *o.From.Get()
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VoiceMessage) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.From.Get(), o.From.IsSet()
}

// HasFrom returns a boolean if a field has been set.
func (o *VoiceMessage) HasFrom() bool {
	if o != nil && o.From.IsSet() {
		return true
	}

	return false
}

// SetFrom gets a reference to the given NullableString and assigns it to the From field.
func (o *VoiceMessage) SetFrom(v string) {
	o.From.Set(&v)
}
// SetFromNil sets the value for From to be an explicit nil
func (o *VoiceMessage) SetFromNil() {
	o.From.Set(nil)
}

// UnsetFrom ensures that no value is present for From, not even an explicit nil
func (o *VoiceMessage) UnsetFrom() {
	o.From.Unset()
}

// GetLang returns the Lang field value if set, zero value otherwise.
func (o *VoiceMessage) GetLang() string {
	if o == nil || IsNil(o.Lang) {
		var ret string
		return ret
	}
	return *o.Lang
}

// GetLangOk returns a tuple with the Lang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetLangOk() (*string, bool) {
	if o == nil || IsNil(o.Lang) {
		return nil, false
	}
	return o.Lang, true
}

// HasLang returns a boolean if a field has been set.
func (o *VoiceMessage) HasLang() bool {
	if o != nil && !IsNil(o.Lang) {
		return true
	}

	return false
}

// SetLang gets a reference to the given string and assigns it to the Lang field.
func (o *VoiceMessage) SetLang(v string) {
	o.Lang = &v
}

// GetVoice returns the Voice field value if set, zero value otherwise.
func (o *VoiceMessage) GetVoice() string {
	if o == nil || IsNil(o.Voice) {
		var ret string
		return ret
	}
	return *o.Voice
}

// GetVoiceOk returns a tuple with the Voice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetVoiceOk() (*string, bool) {
	if o == nil || IsNil(o.Voice) {
		return nil, false
	}
	return o.Voice, true
}

// HasVoice returns a boolean if a field has been set.
func (o *VoiceMessage) HasVoice() bool {
	if o != nil && !IsNil(o.Voice) {
		return true
	}

	return false
}

// SetVoice gets a reference to the given string and assigns it to the Voice field.
func (o *VoiceMessage) SetVoice(v string) {
	o.Voice = &v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *VoiceMessage) GetSchedule() int32 {
	if o == nil || IsNil(o.Schedule) {
		var ret int32
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetScheduleOk() (*int32, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *VoiceMessage) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given int32 and assigns it to the Schedule field.
func (o *VoiceMessage) SetSchedule(v int32) {
	o.Schedule = &v
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *VoiceMessage) GetMessageId() string {
	if o == nil || IsNil(o.MessageId) {
		var ret string
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetMessageIdOk() (*string, bool) {
	if o == nil || IsNil(o.MessageId) {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *VoiceMessage) HasMessageId() bool {
	if o != nil && !IsNil(o.MessageId) {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given string and assigns it to the MessageId field.
func (o *VoiceMessage) SetMessageId(v string) {
	o.MessageId = &v
}

// GetMessageParts returns the MessageParts field value if set, zero value otherwise.
func (o *VoiceMessage) GetMessageParts() int32 {
	if o == nil || IsNil(o.MessageParts) {
		var ret int32
		return ret
	}
	return *o.MessageParts
}

// GetMessagePartsOk returns a tuple with the MessageParts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetMessagePartsOk() (*int32, bool) {
	if o == nil || IsNil(o.MessageParts) {
		return nil, false
	}
	return o.MessageParts, true
}

// HasMessageParts returns a boolean if a field has been set.
func (o *VoiceMessage) HasMessageParts() bool {
	if o != nil && !IsNil(o.MessageParts) {
		return true
	}

	return false
}

// SetMessageParts gets a reference to the given int32 and assigns it to the MessageParts field.
func (o *VoiceMessage) SetMessageParts(v int32) {
	o.MessageParts = &v
}

// GetMessagePrice returns the MessagePrice field value if set, zero value otherwise.
func (o *VoiceMessage) GetMessagePrice() string {
	if o == nil || IsNil(o.MessagePrice) {
		var ret string
		return ret
	}
	return *o.MessagePrice
}

// GetMessagePriceOk returns a tuple with the MessagePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetMessagePriceOk() (*string, bool) {
	if o == nil || IsNil(o.MessagePrice) {
		return nil, false
	}
	return o.MessagePrice, true
}

// HasMessagePrice returns a boolean if a field has been set.
func (o *VoiceMessage) HasMessagePrice() bool {
	if o != nil && !IsNil(o.MessagePrice) {
		return true
	}

	return false
}

// SetMessagePrice gets a reference to the given string and assigns it to the MessagePrice field.
func (o *VoiceMessage) SetMessagePrice(v string) {
	o.MessagePrice = &v
}

// GetCustomString returns the CustomString field value if set, zero value otherwise.
func (o *VoiceMessage) GetCustomString() string {
	if o == nil || IsNil(o.CustomString) {
		var ret string
		return ret
	}
	return *o.CustomString
}

// GetCustomStringOk returns a tuple with the CustomString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetCustomStringOk() (*string, bool) {
	if o == nil || IsNil(o.CustomString) {
		return nil, false
	}
	return o.CustomString, true
}

// HasCustomString returns a boolean if a field has been set.
func (o *VoiceMessage) HasCustomString() bool {
	if o != nil && !IsNil(o.CustomString) {
		return true
	}

	return false
}

// SetCustomString gets a reference to the given string and assigns it to the CustomString field.
func (o *VoiceMessage) SetCustomString(v string) {
	o.CustomString = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *VoiceMessage) GetUserId() float32 {
	if o == nil || IsNil(o.UserId) {
		var ret float32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetUserIdOk() (*float32, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *VoiceMessage) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given float32 and assigns it to the UserId field.
func (o *VoiceMessage) SetUserId(v float32) {
	o.UserId = &v
}

// GetSubaccountId returns the SubaccountId field value if set, zero value otherwise.
func (o *VoiceMessage) GetSubaccountId() float32 {
	if o == nil || IsNil(o.SubaccountId) {
		var ret float32
		return ret
	}
	return *o.SubaccountId
}

// GetSubaccountIdOk returns a tuple with the SubaccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetSubaccountIdOk() (*float32, bool) {
	if o == nil || IsNil(o.SubaccountId) {
		return nil, false
	}
	return o.SubaccountId, true
}

// HasSubaccountId returns a boolean if a field has been set.
func (o *VoiceMessage) HasSubaccountId() bool {
	if o != nil && !IsNil(o.SubaccountId) {
		return true
	}

	return false
}

// SetSubaccountId gets a reference to the given float32 and assigns it to the SubaccountId field.
func (o *VoiceMessage) SetSubaccountId(v float32) {
	o.SubaccountId = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *VoiceMessage) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *VoiceMessage) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *VoiceMessage) SetCountry(v string) {
	o.Country = &v
}

// GetRequireInput returns the RequireInput field value if set, zero value otherwise.
func (o *VoiceMessage) GetRequireInput() float32 {
	if o == nil || IsNil(o.RequireInput) {
		var ret float32
		return ret
	}
	return *o.RequireInput
}

// GetRequireInputOk returns a tuple with the RequireInput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetRequireInputOk() (*float32, bool) {
	if o == nil || IsNil(o.RequireInput) {
		return nil, false
	}
	return o.RequireInput, true
}

// HasRequireInput returns a boolean if a field has been set.
func (o *VoiceMessage) HasRequireInput() bool {
	if o != nil && !IsNil(o.RequireInput) {
		return true
	}

	return false
}

// SetRequireInput gets a reference to the given float32 and assigns it to the RequireInput field.
func (o *VoiceMessage) SetRequireInput(v float32) {
	o.RequireInput = &v
}

// GetMachineDetection returns the MachineDetection field value if set, zero value otherwise.
func (o *VoiceMessage) GetMachineDetection() float32 {
	if o == nil || IsNil(o.MachineDetection) {
		var ret float32
		return ret
	}
	return *o.MachineDetection
}

// GetMachineDetectionOk returns a tuple with the MachineDetection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetMachineDetectionOk() (*float32, bool) {
	if o == nil || IsNil(o.MachineDetection) {
		return nil, false
	}
	return o.MachineDetection, true
}

// HasMachineDetection returns a boolean if a field has been set.
func (o *VoiceMessage) HasMachineDetection() bool {
	if o != nil && !IsNil(o.MachineDetection) {
		return true
	}

	return false
}

// SetMachineDetection gets a reference to the given float32 and assigns it to the MachineDetection field.
func (o *VoiceMessage) SetMachineDetection(v float32) {
	o.MachineDetection = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *VoiceMessage) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceMessage) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *VoiceMessage) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *VoiceMessage) SetStatus(v string) {
	o.Status = &v
}

func (o VoiceMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoiceMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.ToType) {
		toSerialize["to_type"] = o.ToType
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if o.From.IsSet() {
		toSerialize["from"] = o.From.Get()
	}
	if !IsNil(o.Lang) {
		toSerialize["lang"] = o.Lang
	}
	if !IsNil(o.Voice) {
		toSerialize["voice"] = o.Voice
	}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	if !IsNil(o.MessageId) {
		toSerialize["message_id"] = o.MessageId
	}
	if !IsNil(o.MessageParts) {
		toSerialize["message_parts"] = o.MessageParts
	}
	if !IsNil(o.MessagePrice) {
		toSerialize["message_price"] = o.MessagePrice
	}
	if !IsNil(o.CustomString) {
		toSerialize["custom_string"] = o.CustomString
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.SubaccountId) {
		toSerialize["subaccount_id"] = o.SubaccountId
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.RequireInput) {
		toSerialize["require_input"] = o.RequireInput
	}
	if !IsNil(o.MachineDetection) {
		toSerialize["machine_detection"] = o.MachineDetection
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableVoiceMessage struct {
	value *VoiceMessage
	isSet bool
}

func (v NullableVoiceMessage) Get() *VoiceMessage {
	return v.value
}

func (v *NullableVoiceMessage) Set(val *VoiceMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableVoiceMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableVoiceMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoiceMessage(val *VoiceMessage) *NullableVoiceMessage {
	return &NullableVoiceMessage{value: val, isSet: true}
}

func (v NullableVoiceMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoiceMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


