/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the RemoveOptedOutContactsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveOptedOutContactsData{}

// RemoveOptedOutContactsData struct for RemoveOptedOutContactsData
type RemoveOptedOutContactsData struct {
	// The number of contacts deleted.
	Deleted *float32 `json:"deleted,omitempty"`
}

// NewRemoveOptedOutContactsData instantiates a new RemoveOptedOutContactsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveOptedOutContactsData() *RemoveOptedOutContactsData {
	this := RemoveOptedOutContactsData{}
	return &this
}

// NewRemoveOptedOutContactsDataWithDefaults instantiates a new RemoveOptedOutContactsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveOptedOutContactsDataWithDefaults() *RemoveOptedOutContactsData {
	this := RemoveOptedOutContactsData{}
	return &this
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *RemoveOptedOutContactsData) GetDeleted() float32 {
	if o == nil || IsNil(o.Deleted) {
		var ret float32
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoveOptedOutContactsData) GetDeletedOk() (*float32, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *RemoveOptedOutContactsData) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given float32 and assigns it to the Deleted field.
func (o *RemoveOptedOutContactsData) SetDeleted(v float32) {
	o.Deleted = &v
}

func (o RemoveOptedOutContactsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveOptedOutContactsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	return toSerialize, nil
}

type NullableRemoveOptedOutContactsData struct {
	value *RemoveOptedOutContactsData
	isSet bool
}

func (v NullableRemoveOptedOutContactsData) Get() *RemoveOptedOutContactsData {
	return v.value
}

func (v *NullableRemoveOptedOutContactsData) Set(val *RemoveOptedOutContactsData) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveOptedOutContactsData) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveOptedOutContactsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveOptedOutContactsData(val *RemoveOptedOutContactsData) *NullableRemoveOptedOutContactsData {
	return &NullableRemoveOptedOutContactsData{value: val, isSet: true}
}

func (v NullableRemoveOptedOutContactsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveOptedOutContactsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


