/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the MarkSpecificInboundSmsMessageAsRead type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MarkSpecificInboundSmsMessageAsRead{}

// MarkSpecificInboundSmsMessageAsRead struct for MarkSpecificInboundSmsMessageAsRead
type MarkSpecificInboundSmsMessageAsRead struct {
	// The HTTP code of the response. Visit [this page](/#status-codes) for more information.
	HttpCode *int32 `json:"http_code,omitempty"`
	// The response code of the operation. Visit [this page](/#status-codes) for more information.
	ResponseCode *string `json:"response_code,omitempty"`
	// A message describing the outcome of the operation.
	ResponseMsg *string `json:"response_msg,omitempty"`
	// The number of SMS marked as read.  If you have multiple inbound rules set to POLL, you will receive the inbound message multiple times. Reading it will mark all those messages as read.
	Data *int32 `json:"data,omitempty"`
}

// NewMarkSpecificInboundSmsMessageAsRead instantiates a new MarkSpecificInboundSmsMessageAsRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarkSpecificInboundSmsMessageAsRead() *MarkSpecificInboundSmsMessageAsRead {
	this := MarkSpecificInboundSmsMessageAsRead{}
	return &this
}

// NewMarkSpecificInboundSmsMessageAsReadWithDefaults instantiates a new MarkSpecificInboundSmsMessageAsRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarkSpecificInboundSmsMessageAsReadWithDefaults() *MarkSpecificInboundSmsMessageAsRead {
	this := MarkSpecificInboundSmsMessageAsRead{}
	return &this
}

// GetHttpCode returns the HttpCode field value if set, zero value otherwise.
func (o *MarkSpecificInboundSmsMessageAsRead) GetHttpCode() int32 {
	if o == nil || IsNil(o.HttpCode) {
		var ret int32
		return ret
	}
	return *o.HttpCode
}

// GetHttpCodeOk returns a tuple with the HttpCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarkSpecificInboundSmsMessageAsRead) GetHttpCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.HttpCode) {
		return nil, false
	}
	return o.HttpCode, true
}

// HasHttpCode returns a boolean if a field has been set.
func (o *MarkSpecificInboundSmsMessageAsRead) HasHttpCode() bool {
	if o != nil && !IsNil(o.HttpCode) {
		return true
	}

	return false
}

// SetHttpCode gets a reference to the given int32 and assigns it to the HttpCode field.
func (o *MarkSpecificInboundSmsMessageAsRead) SetHttpCode(v int32) {
	o.HttpCode = &v
}

// GetResponseCode returns the ResponseCode field value if set, zero value otherwise.
func (o *MarkSpecificInboundSmsMessageAsRead) GetResponseCode() string {
	if o == nil || IsNil(o.ResponseCode) {
		var ret string
		return ret
	}
	return *o.ResponseCode
}

// GetResponseCodeOk returns a tuple with the ResponseCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarkSpecificInboundSmsMessageAsRead) GetResponseCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseCode) {
		return nil, false
	}
	return o.ResponseCode, true
}

// HasResponseCode returns a boolean if a field has been set.
func (o *MarkSpecificInboundSmsMessageAsRead) HasResponseCode() bool {
	if o != nil && !IsNil(o.ResponseCode) {
		return true
	}

	return false
}

// SetResponseCode gets a reference to the given string and assigns it to the ResponseCode field.
func (o *MarkSpecificInboundSmsMessageAsRead) SetResponseCode(v string) {
	o.ResponseCode = &v
}

// GetResponseMsg returns the ResponseMsg field value if set, zero value otherwise.
func (o *MarkSpecificInboundSmsMessageAsRead) GetResponseMsg() string {
	if o == nil || IsNil(o.ResponseMsg) {
		var ret string
		return ret
	}
	return *o.ResponseMsg
}

// GetResponseMsgOk returns a tuple with the ResponseMsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarkSpecificInboundSmsMessageAsRead) GetResponseMsgOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseMsg) {
		return nil, false
	}
	return o.ResponseMsg, true
}

// HasResponseMsg returns a boolean if a field has been set.
func (o *MarkSpecificInboundSmsMessageAsRead) HasResponseMsg() bool {
	if o != nil && !IsNil(o.ResponseMsg) {
		return true
	}

	return false
}

// SetResponseMsg gets a reference to the given string and assigns it to the ResponseMsg field.
func (o *MarkSpecificInboundSmsMessageAsRead) SetResponseMsg(v string) {
	o.ResponseMsg = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *MarkSpecificInboundSmsMessageAsRead) GetData() int32 {
	if o == nil || IsNil(o.Data) {
		var ret int32
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarkSpecificInboundSmsMessageAsRead) GetDataOk() (*int32, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *MarkSpecificInboundSmsMessageAsRead) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given int32 and assigns it to the Data field.
func (o *MarkSpecificInboundSmsMessageAsRead) SetData(v int32) {
	o.Data = &v
}

func (o MarkSpecificInboundSmsMessageAsRead) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MarkSpecificInboundSmsMessageAsRead) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HttpCode) {
		toSerialize["http_code"] = o.HttpCode
	}
	if !IsNil(o.ResponseCode) {
		toSerialize["response_code"] = o.ResponseCode
	}
	if !IsNil(o.ResponseMsg) {
		toSerialize["response_msg"] = o.ResponseMsg
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableMarkSpecificInboundSmsMessageAsRead struct {
	value *MarkSpecificInboundSmsMessageAsRead
	isSet bool
}

func (v NullableMarkSpecificInboundSmsMessageAsRead) Get() *MarkSpecificInboundSmsMessageAsRead {
	return v.value
}

func (v *NullableMarkSpecificInboundSmsMessageAsRead) Set(val *MarkSpecificInboundSmsMessageAsRead) {
	v.value = val
	v.isSet = true
}

func (v NullableMarkSpecificInboundSmsMessageAsRead) IsSet() bool {
	return v.isSet
}

func (v *NullableMarkSpecificInboundSmsMessageAsRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarkSpecificInboundSmsMessageAsRead(val *MarkSpecificInboundSmsMessageAsRead) *NullableMarkSpecificInboundSmsMessageAsRead {
	return &NullableMarkSpecificInboundSmsMessageAsRead{value: val, isSet: true}
}

func (v NullableMarkSpecificInboundSmsMessageAsRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarkSpecificInboundSmsMessageAsRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


