/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the FaxReceipt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FaxReceipt{}

// FaxReceipt struct for FaxReceipt
type FaxReceipt struct {
	// The timestamp when the message was sent.
	TimestampSend *string `json:"timestamp_send,omitempty"`
	// The timestamp associated with the message.
	Timestamp *string `json:"timestamp,omitempty"`
	// The ID of the message.
	MessageId *string `json:"message_id,omitempty"`
	// The status code of the message.
	StatusCode *string `json:"status_code,omitempty"`
	// The status text of the message.
	StatusText *string `json:"status_text,omitempty"`
	// The error code associated with the message.
	ErrorCode *string `json:"error_code,omitempty"`
	// The error text associated with the message.
	ErrorText *string `json:"error_text,omitempty"`
	// A custom string associated with the message.
	CustomString *string `json:"custom_string,omitempty"`
	// The ID of the subaccount.
	SubaccountId *int32 `json:"subaccount_id,omitempty"`
	// The type of message.
	MessageType *string `json:"message_type,omitempty"`
}

// NewFaxReceipt instantiates a new FaxReceipt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFaxReceipt() *FaxReceipt {
	this := FaxReceipt{}
	return &this
}

// NewFaxReceiptWithDefaults instantiates a new FaxReceipt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFaxReceiptWithDefaults() *FaxReceipt {
	this := FaxReceipt{}
	return &this
}

// GetTimestampSend returns the TimestampSend field value if set, zero value otherwise.
func (o *FaxReceipt) GetTimestampSend() string {
	if o == nil || IsNil(o.TimestampSend) {
		var ret string
		return ret
	}
	return *o.TimestampSend
}

// GetTimestampSendOk returns a tuple with the TimestampSend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaxReceipt) GetTimestampSendOk() (*string, bool) {
	if o == nil || IsNil(o.TimestampSend) {
		return nil, false
	}
	return o.TimestampSend, true
}

// HasTimestampSend returns a boolean if a field has been set.
func (o *FaxReceipt) HasTimestampSend() bool {
	if o != nil && !IsNil(o.TimestampSend) {
		return true
	}

	return false
}

// SetTimestampSend gets a reference to the given string and assigns it to the TimestampSend field.
func (o *FaxReceipt) SetTimestampSend(v string) {
	o.TimestampSend = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *FaxReceipt) GetTimestamp() string {
	if o == nil || IsNil(o.Timestamp) {
		var ret string
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaxReceipt) GetTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *FaxReceipt) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given string and assigns it to the Timestamp field.
func (o *FaxReceipt) SetTimestamp(v string) {
	o.Timestamp = &v
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *FaxReceipt) GetMessageId() string {
	if o == nil || IsNil(o.MessageId) {
		var ret string
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaxReceipt) GetMessageIdOk() (*string, bool) {
	if o == nil || IsNil(o.MessageId) {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *FaxReceipt) HasMessageId() bool {
	if o != nil && !IsNil(o.MessageId) {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given string and assigns it to the MessageId field.
func (o *FaxReceipt) SetMessageId(v string) {
	o.MessageId = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *FaxReceipt) GetStatusCode() string {
	if o == nil || IsNil(o.StatusCode) {
		var ret string
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaxReceipt) GetStatusCodeOk() (*string, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *FaxReceipt) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given string and assigns it to the StatusCode field.
func (o *FaxReceipt) SetStatusCode(v string) {
	o.StatusCode = &v
}

// GetStatusText returns the StatusText field value if set, zero value otherwise.
func (o *FaxReceipt) GetStatusText() string {
	if o == nil || IsNil(o.StatusText) {
		var ret string
		return ret
	}
	return *o.StatusText
}

// GetStatusTextOk returns a tuple with the StatusText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaxReceipt) GetStatusTextOk() (*string, bool) {
	if o == nil || IsNil(o.StatusText) {
		return nil, false
	}
	return o.StatusText, true
}

// HasStatusText returns a boolean if a field has been set.
func (o *FaxReceipt) HasStatusText() bool {
	if o != nil && !IsNil(o.StatusText) {
		return true
	}

	return false
}

// SetStatusText gets a reference to the given string and assigns it to the StatusText field.
func (o *FaxReceipt) SetStatusText(v string) {
	o.StatusText = &v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *FaxReceipt) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode) {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaxReceipt) GetErrorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *FaxReceipt) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *FaxReceipt) SetErrorCode(v string) {
	o.ErrorCode = &v
}

// GetErrorText returns the ErrorText field value if set, zero value otherwise.
func (o *FaxReceipt) GetErrorText() string {
	if o == nil || IsNil(o.ErrorText) {
		var ret string
		return ret
	}
	return *o.ErrorText
}

// GetErrorTextOk returns a tuple with the ErrorText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaxReceipt) GetErrorTextOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorText) {
		return nil, false
	}
	return o.ErrorText, true
}

// HasErrorText returns a boolean if a field has been set.
func (o *FaxReceipt) HasErrorText() bool {
	if o != nil && !IsNil(o.ErrorText) {
		return true
	}

	return false
}

// SetErrorText gets a reference to the given string and assigns it to the ErrorText field.
func (o *FaxReceipt) SetErrorText(v string) {
	o.ErrorText = &v
}

// GetCustomString returns the CustomString field value if set, zero value otherwise.
func (o *FaxReceipt) GetCustomString() string {
	if o == nil || IsNil(o.CustomString) {
		var ret string
		return ret
	}
	return *o.CustomString
}

// GetCustomStringOk returns a tuple with the CustomString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaxReceipt) GetCustomStringOk() (*string, bool) {
	if o == nil || IsNil(o.CustomString) {
		return nil, false
	}
	return o.CustomString, true
}

// HasCustomString returns a boolean if a field has been set.
func (o *FaxReceipt) HasCustomString() bool {
	if o != nil && !IsNil(o.CustomString) {
		return true
	}

	return false
}

// SetCustomString gets a reference to the given string and assigns it to the CustomString field.
func (o *FaxReceipt) SetCustomString(v string) {
	o.CustomString = &v
}

// GetSubaccountId returns the SubaccountId field value if set, zero value otherwise.
func (o *FaxReceipt) GetSubaccountId() int32 {
	if o == nil || IsNil(o.SubaccountId) {
		var ret int32
		return ret
	}
	return *o.SubaccountId
}

// GetSubaccountIdOk returns a tuple with the SubaccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaxReceipt) GetSubaccountIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SubaccountId) {
		return nil, false
	}
	return o.SubaccountId, true
}

// HasSubaccountId returns a boolean if a field has been set.
func (o *FaxReceipt) HasSubaccountId() bool {
	if o != nil && !IsNil(o.SubaccountId) {
		return true
	}

	return false
}

// SetSubaccountId gets a reference to the given int32 and assigns it to the SubaccountId field.
func (o *FaxReceipt) SetSubaccountId(v int32) {
	o.SubaccountId = &v
}

// GetMessageType returns the MessageType field value if set, zero value otherwise.
func (o *FaxReceipt) GetMessageType() string {
	if o == nil || IsNil(o.MessageType) {
		var ret string
		return ret
	}
	return *o.MessageType
}

// GetMessageTypeOk returns a tuple with the MessageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FaxReceipt) GetMessageTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MessageType) {
		return nil, false
	}
	return o.MessageType, true
}

// HasMessageType returns a boolean if a field has been set.
func (o *FaxReceipt) HasMessageType() bool {
	if o != nil && !IsNil(o.MessageType) {
		return true
	}

	return false
}

// SetMessageType gets a reference to the given string and assigns it to the MessageType field.
func (o *FaxReceipt) SetMessageType(v string) {
	o.MessageType = &v
}

func (o FaxReceipt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FaxReceipt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimestampSend) {
		toSerialize["timestamp_send"] = o.TimestampSend
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.MessageId) {
		toSerialize["message_id"] = o.MessageId
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	if !IsNil(o.StatusText) {
		toSerialize["status_text"] = o.StatusText
	}
	if !IsNil(o.ErrorCode) {
		toSerialize["error_code"] = o.ErrorCode
	}
	if !IsNil(o.ErrorText) {
		toSerialize["error_text"] = o.ErrorText
	}
	if !IsNil(o.CustomString) {
		toSerialize["custom_string"] = o.CustomString
	}
	if !IsNil(o.SubaccountId) {
		toSerialize["subaccount_id"] = o.SubaccountId
	}
	if !IsNil(o.MessageType) {
		toSerialize["message_type"] = o.MessageType
	}
	return toSerialize, nil
}

type NullableFaxReceipt struct {
	value *FaxReceipt
	isSet bool
}

func (v NullableFaxReceipt) Get() *FaxReceipt {
	return v.value
}

func (v *NullableFaxReceipt) Set(val *FaxReceipt) {
	v.value = val
	v.isSet = true
}

func (v NullableFaxReceipt) IsSet() bool {
	return v.isSet
}

func (v *NullableFaxReceipt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFaxReceipt(val *FaxReceipt) *NullableFaxReceipt {
	return &NullableFaxReceipt{value: val, isSet: true}
}

func (v NullableFaxReceipt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFaxReceipt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


