/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the ViewAvailableNumbersData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewAvailableNumbersData{}

// ViewAvailableNumbersData struct for ViewAvailableNumbersData
type ViewAvailableNumbersData struct {
	// The total number of items available for viewing.
	Total *int32 `json:"total,omitempty"`
	// The number of items returned per page. This is specified in the limit parameter. You can have 100 items at maximum, and 15 at minimum.
	PerPage *int32 `json:"per_page,omitempty"`
	// The current page number.
	CurrentPage *int32 `json:"current_page,omitempty"`
	// The last page number.
	LastPage *int32 `json:"last_page,omitempty"`
	// A URL of the next page. It will return **null** if there’s no next page.
	NextPageUrl NullableString `json:"next_page_url,omitempty"`
	// A URL of the previous page. It will return **null** if there’s no previous page.
	PrevPageUrl NullableString `json:"prev_page_url,omitempty"`
	// The number of the first result in the current page.
	From *int32 `json:"from,omitempty"`
	// The number of the last result in the current page.
	To *int32 `json:"to,omitempty"`
	Data []ViewAvailableNumbersDataAllOfDataInner `json:"data,omitempty"`
	Currency *Currency `json:"_currency,omitempty"`
}

// NewViewAvailableNumbersData instantiates a new ViewAvailableNumbersData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewAvailableNumbersData() *ViewAvailableNumbersData {
	this := ViewAvailableNumbersData{}
	return &this
}

// NewViewAvailableNumbersDataWithDefaults instantiates a new ViewAvailableNumbersData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewAvailableNumbersDataWithDefaults() *ViewAvailableNumbersData {
	this := ViewAvailableNumbersData{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ViewAvailableNumbersData) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewAvailableNumbersData) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ViewAvailableNumbersData) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ViewAvailableNumbersData) SetTotal(v int32) {
	o.Total = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *ViewAvailableNumbersData) GetPerPage() int32 {
	if o == nil || IsNil(o.PerPage) {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewAvailableNumbersData) GetPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *ViewAvailableNumbersData) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *ViewAvailableNumbersData) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetCurrentPage returns the CurrentPage field value if set, zero value otherwise.
func (o *ViewAvailableNumbersData) GetCurrentPage() int32 {
	if o == nil || IsNil(o.CurrentPage) {
		var ret int32
		return ret
	}
	return *o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewAvailableNumbersData) GetCurrentPageOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentPage) {
		return nil, false
	}
	return o.CurrentPage, true
}

// HasCurrentPage returns a boolean if a field has been set.
func (o *ViewAvailableNumbersData) HasCurrentPage() bool {
	if o != nil && !IsNil(o.CurrentPage) {
		return true
	}

	return false
}

// SetCurrentPage gets a reference to the given int32 and assigns it to the CurrentPage field.
func (o *ViewAvailableNumbersData) SetCurrentPage(v int32) {
	o.CurrentPage = &v
}

// GetLastPage returns the LastPage field value if set, zero value otherwise.
func (o *ViewAvailableNumbersData) GetLastPage() int32 {
	if o == nil || IsNil(o.LastPage) {
		var ret int32
		return ret
	}
	return *o.LastPage
}

// GetLastPageOk returns a tuple with the LastPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewAvailableNumbersData) GetLastPageOk() (*int32, bool) {
	if o == nil || IsNil(o.LastPage) {
		return nil, false
	}
	return o.LastPage, true
}

// HasLastPage returns a boolean if a field has been set.
func (o *ViewAvailableNumbersData) HasLastPage() bool {
	if o != nil && !IsNil(o.LastPage) {
		return true
	}

	return false
}

// SetLastPage gets a reference to the given int32 and assigns it to the LastPage field.
func (o *ViewAvailableNumbersData) SetLastPage(v int32) {
	o.LastPage = &v
}

// GetNextPageUrl returns the NextPageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ViewAvailableNumbersData) GetNextPageUrl() string {
	if o == nil || IsNil(o.NextPageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.NextPageUrl.Get()
}

// GetNextPageUrlOk returns a tuple with the NextPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ViewAvailableNumbersData) GetNextPageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextPageUrl.Get(), o.NextPageUrl.IsSet()
}

// HasNextPageUrl returns a boolean if a field has been set.
func (o *ViewAvailableNumbersData) HasNextPageUrl() bool {
	if o != nil && o.NextPageUrl.IsSet() {
		return true
	}

	return false
}

// SetNextPageUrl gets a reference to the given NullableString and assigns it to the NextPageUrl field.
func (o *ViewAvailableNumbersData) SetNextPageUrl(v string) {
	o.NextPageUrl.Set(&v)
}
// SetNextPageUrlNil sets the value for NextPageUrl to be an explicit nil
func (o *ViewAvailableNumbersData) SetNextPageUrlNil() {
	o.NextPageUrl.Set(nil)
}

// UnsetNextPageUrl ensures that no value is present for NextPageUrl, not even an explicit nil
func (o *ViewAvailableNumbersData) UnsetNextPageUrl() {
	o.NextPageUrl.Unset()
}

// GetPrevPageUrl returns the PrevPageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ViewAvailableNumbersData) GetPrevPageUrl() string {
	if o == nil || IsNil(o.PrevPageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.PrevPageUrl.Get()
}

// GetPrevPageUrlOk returns a tuple with the PrevPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ViewAvailableNumbersData) GetPrevPageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrevPageUrl.Get(), o.PrevPageUrl.IsSet()
}

// HasPrevPageUrl returns a boolean if a field has been set.
func (o *ViewAvailableNumbersData) HasPrevPageUrl() bool {
	if o != nil && o.PrevPageUrl.IsSet() {
		return true
	}

	return false
}

// SetPrevPageUrl gets a reference to the given NullableString and assigns it to the PrevPageUrl field.
func (o *ViewAvailableNumbersData) SetPrevPageUrl(v string) {
	o.PrevPageUrl.Set(&v)
}
// SetPrevPageUrlNil sets the value for PrevPageUrl to be an explicit nil
func (o *ViewAvailableNumbersData) SetPrevPageUrlNil() {
	o.PrevPageUrl.Set(nil)
}

// UnsetPrevPageUrl ensures that no value is present for PrevPageUrl, not even an explicit nil
func (o *ViewAvailableNumbersData) UnsetPrevPageUrl() {
	o.PrevPageUrl.Unset()
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *ViewAvailableNumbersData) GetFrom() int32 {
	if o == nil || IsNil(o.From) {
		var ret int32
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewAvailableNumbersData) GetFromOk() (*int32, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *ViewAvailableNumbersData) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given int32 and assigns it to the From field.
func (o *ViewAvailableNumbersData) SetFrom(v int32) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *ViewAvailableNumbersData) GetTo() int32 {
	if o == nil || IsNil(o.To) {
		var ret int32
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewAvailableNumbersData) GetToOk() (*int32, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *ViewAvailableNumbersData) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given int32 and assigns it to the To field.
func (o *ViewAvailableNumbersData) SetTo(v int32) {
	o.To = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ViewAvailableNumbersData) GetData() []ViewAvailableNumbersDataAllOfDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []ViewAvailableNumbersDataAllOfDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewAvailableNumbersData) GetDataOk() ([]ViewAvailableNumbersDataAllOfDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ViewAvailableNumbersData) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ViewAvailableNumbersDataAllOfDataInner and assigns it to the Data field.
func (o *ViewAvailableNumbersData) SetData(v []ViewAvailableNumbersDataAllOfDataInner) {
	o.Data = v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ViewAvailableNumbersData) GetCurrency() Currency {
	if o == nil || IsNil(o.Currency) {
		var ret Currency
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewAvailableNumbersData) GetCurrencyOk() (*Currency, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ViewAvailableNumbersData) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given Currency and assigns it to the Currency field.
func (o *ViewAvailableNumbersData) SetCurrency(v Currency) {
	o.Currency = &v
}

func (o ViewAvailableNumbersData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewAvailableNumbersData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	if !IsNil(o.CurrentPage) {
		toSerialize["current_page"] = o.CurrentPage
	}
	if !IsNil(o.LastPage) {
		toSerialize["last_page"] = o.LastPage
	}
	if o.NextPageUrl.IsSet() {
		toSerialize["next_page_url"] = o.NextPageUrl.Get()
	}
	if o.PrevPageUrl.IsSet() {
		toSerialize["prev_page_url"] = o.PrevPageUrl.Get()
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Currency) {
		toSerialize["_currency"] = o.Currency
	}
	return toSerialize, nil
}

type NullableViewAvailableNumbersData struct {
	value *ViewAvailableNumbersData
	isSet bool
}

func (v NullableViewAvailableNumbersData) Get() *ViewAvailableNumbersData {
	return v.value
}

func (v *NullableViewAvailableNumbersData) Set(val *ViewAvailableNumbersData) {
	v.value = val
	v.isSet = true
}

func (v NullableViewAvailableNumbersData) IsSet() bool {
	return v.isSet
}

func (v *NullableViewAvailableNumbersData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewAvailableNumbersData(val *ViewAvailableNumbersData) *NullableViewAvailableNumbersData {
	return &NullableViewAvailableNumbersData{value: val, isSet: true}
}

func (v NullableViewAvailableNumbersData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewAvailableNumbersData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


