/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the DetectAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DetectAddress{}

// DetectAddress struct for DetectAddress
type DetectAddress struct {
	// The HTTP status code of the response.
	HttpCode *int32 `json:"http_code,omitempty"`
	// The response code indicating the status of the operation.
	ResponseCode *string `json:"response_code,omitempty"`
	// A message describing the outcome of the operation.
	ResponseMsg *string `json:"response_msg,omitempty"`
	Data *DetectAddressData `json:"data,omitempty"`
}

// NewDetectAddress instantiates a new DetectAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetectAddress() *DetectAddress {
	this := DetectAddress{}
	return &this
}

// NewDetectAddressWithDefaults instantiates a new DetectAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetectAddressWithDefaults() *DetectAddress {
	this := DetectAddress{}
	return &this
}

// GetHttpCode returns the HttpCode field value if set, zero value otherwise.
func (o *DetectAddress) GetHttpCode() int32 {
	if o == nil || IsNil(o.HttpCode) {
		var ret int32
		return ret
	}
	return *o.HttpCode
}

// GetHttpCodeOk returns a tuple with the HttpCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetectAddress) GetHttpCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.HttpCode) {
		return nil, false
	}
	return o.HttpCode, true
}

// HasHttpCode returns a boolean if a field has been set.
func (o *DetectAddress) HasHttpCode() bool {
	if o != nil && !IsNil(o.HttpCode) {
		return true
	}

	return false
}

// SetHttpCode gets a reference to the given int32 and assigns it to the HttpCode field.
func (o *DetectAddress) SetHttpCode(v int32) {
	o.HttpCode = &v
}

// GetResponseCode returns the ResponseCode field value if set, zero value otherwise.
func (o *DetectAddress) GetResponseCode() string {
	if o == nil || IsNil(o.ResponseCode) {
		var ret string
		return ret
	}
	return *o.ResponseCode
}

// GetResponseCodeOk returns a tuple with the ResponseCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetectAddress) GetResponseCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseCode) {
		return nil, false
	}
	return o.ResponseCode, true
}

// HasResponseCode returns a boolean if a field has been set.
func (o *DetectAddress) HasResponseCode() bool {
	if o != nil && !IsNil(o.ResponseCode) {
		return true
	}

	return false
}

// SetResponseCode gets a reference to the given string and assigns it to the ResponseCode field.
func (o *DetectAddress) SetResponseCode(v string) {
	o.ResponseCode = &v
}

// GetResponseMsg returns the ResponseMsg field value if set, zero value otherwise.
func (o *DetectAddress) GetResponseMsg() string {
	if o == nil || IsNil(o.ResponseMsg) {
		var ret string
		return ret
	}
	return *o.ResponseMsg
}

// GetResponseMsgOk returns a tuple with the ResponseMsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetectAddress) GetResponseMsgOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseMsg) {
		return nil, false
	}
	return o.ResponseMsg, true
}

// HasResponseMsg returns a boolean if a field has been set.
func (o *DetectAddress) HasResponseMsg() bool {
	if o != nil && !IsNil(o.ResponseMsg) {
		return true
	}

	return false
}

// SetResponseMsg gets a reference to the given string and assigns it to the ResponseMsg field.
func (o *DetectAddress) SetResponseMsg(v string) {
	o.ResponseMsg = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *DetectAddress) GetData() DetectAddressData {
	if o == nil || IsNil(o.Data) {
		var ret DetectAddressData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetectAddress) GetDataOk() (*DetectAddressData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *DetectAddress) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given DetectAddressData and assigns it to the Data field.
func (o *DetectAddress) SetData(v DetectAddressData) {
	o.Data = &v
}

func (o DetectAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DetectAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HttpCode) {
		toSerialize["http_code"] = o.HttpCode
	}
	if !IsNil(o.ResponseCode) {
		toSerialize["response_code"] = o.ResponseCode
	}
	if !IsNil(o.ResponseMsg) {
		toSerialize["response_msg"] = o.ResponseMsg
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableDetectAddress struct {
	value *DetectAddress
	isSet bool
}

func (v NullableDetectAddress) Get() *DetectAddress {
	return v.value
}

func (v *NullableDetectAddress) Set(val *DetectAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableDetectAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableDetectAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetectAddress(val *DetectAddress) *NullableDetectAddress {
	return &NullableDetectAddress{value: val, isSet: true}
}

func (v NullableDetectAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetectAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


