/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the CalculateSmsPriceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalculateSmsPriceRequest{}

// CalculateSmsPriceRequest struct for CalculateSmsPriceRequest
type CalculateSmsPriceRequest struct {
	// The `senders` property specifies sender IDs for each recipient country. - **Want to leverage the default sender settings:**   - If the `senders` property is missing or left empty, the system uses the default sender settings configured for each recipient country.  - **Want to override the default sender settings:**   - When the `senders` property is provided, it should contain valid sender IDs for each recipient country listed under recipients. These IDs will override the default sender settings for the specified countries.   - If an invalid sender ID is provided, or a sender ID for a specific recipient country is missing, the system will revert to using the default sender settings for that country. 
	Senders []SendersInner `json:"senders,omitempty"`
	// This controls whether URLs are automatically shortened. This affects all messages in the request. You can either specify:  - **True** - Automatically detects and shortens one URL on each message. - **False** - Leaves all URLs in their original form. This is the default value.  You will be able to retrieve the open rates and statistics for the link from this <a href=\"/messaging/url-shortening/other/short-url-get-statistics\">link</a>.  More info about shortening URLs <a href=\"/messaging/url-shortening/\"> here</a>. 
	ShortenUrls *bool `json:"shorten_urls,omitempty"`
	// Messages to send to customers.
	Messages []CalculateSmsPriceRequestMessagesInner `json:"messages,omitempty"`
}

// NewCalculateSmsPriceRequest instantiates a new CalculateSmsPriceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalculateSmsPriceRequest() *CalculateSmsPriceRequest {
	this := CalculateSmsPriceRequest{}
	return &this
}

// NewCalculateSmsPriceRequestWithDefaults instantiates a new CalculateSmsPriceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalculateSmsPriceRequestWithDefaults() *CalculateSmsPriceRequest {
	this := CalculateSmsPriceRequest{}
	return &this
}

// GetSenders returns the Senders field value if set, zero value otherwise.
func (o *CalculateSmsPriceRequest) GetSenders() []SendersInner {
	if o == nil || IsNil(o.Senders) {
		var ret []SendersInner
		return ret
	}
	return o.Senders
}

// GetSendersOk returns a tuple with the Senders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceRequest) GetSendersOk() ([]SendersInner, bool) {
	if o == nil || IsNil(o.Senders) {
		return nil, false
	}
	return o.Senders, true
}

// HasSenders returns a boolean if a field has been set.
func (o *CalculateSmsPriceRequest) HasSenders() bool {
	if o != nil && !IsNil(o.Senders) {
		return true
	}

	return false
}

// SetSenders gets a reference to the given []SendersInner and assigns it to the Senders field.
func (o *CalculateSmsPriceRequest) SetSenders(v []SendersInner) {
	o.Senders = v
}

// GetShortenUrls returns the ShortenUrls field value if set, zero value otherwise.
func (o *CalculateSmsPriceRequest) GetShortenUrls() bool {
	if o == nil || IsNil(o.ShortenUrls) {
		var ret bool
		return ret
	}
	return *o.ShortenUrls
}

// GetShortenUrlsOk returns a tuple with the ShortenUrls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceRequest) GetShortenUrlsOk() (*bool, bool) {
	if o == nil || IsNil(o.ShortenUrls) {
		return nil, false
	}
	return o.ShortenUrls, true
}

// HasShortenUrls returns a boolean if a field has been set.
func (o *CalculateSmsPriceRequest) HasShortenUrls() bool {
	if o != nil && !IsNil(o.ShortenUrls) {
		return true
	}

	return false
}

// SetShortenUrls gets a reference to the given bool and assigns it to the ShortenUrls field.
func (o *CalculateSmsPriceRequest) SetShortenUrls(v bool) {
	o.ShortenUrls = &v
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *CalculateSmsPriceRequest) GetMessages() []CalculateSmsPriceRequestMessagesInner {
	if o == nil || IsNil(o.Messages) {
		var ret []CalculateSmsPriceRequestMessagesInner
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceRequest) GetMessagesOk() ([]CalculateSmsPriceRequestMessagesInner, bool) {
	if o == nil || IsNil(o.Messages) {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *CalculateSmsPriceRequest) HasMessages() bool {
	if o != nil && !IsNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []CalculateSmsPriceRequestMessagesInner and assigns it to the Messages field.
func (o *CalculateSmsPriceRequest) SetMessages(v []CalculateSmsPriceRequestMessagesInner) {
	o.Messages = v
}

func (o CalculateSmsPriceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalculateSmsPriceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Senders) {
		toSerialize["senders"] = o.Senders
	}
	if !IsNil(o.ShortenUrls) {
		toSerialize["shorten_urls"] = o.ShortenUrls
	}
	if !IsNil(o.Messages) {
		toSerialize["messages"] = o.Messages
	}
	return toSerialize, nil
}

type NullableCalculateSmsPriceRequest struct {
	value *CalculateSmsPriceRequest
	isSet bool
}

func (v NullableCalculateSmsPriceRequest) Get() *CalculateSmsPriceRequest {
	return v.value
}

func (v *NullableCalculateSmsPriceRequest) Set(val *CalculateSmsPriceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCalculateSmsPriceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCalculateSmsPriceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalculateSmsPriceRequest(val *CalculateSmsPriceRequest) *NullableCalculateSmsPriceRequest {
	return &NullableCalculateSmsPriceRequest{value: val, isSet: true}
}

func (v NullableCalculateSmsPriceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalculateSmsPriceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


