/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the SendEmailVerificationTokenRequestToInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendEmailVerificationTokenRequestToInner{}

// SendEmailVerificationTokenRequestToInner struct for SendEmailVerificationTokenRequestToInner
type SendEmailVerificationTokenRequestToInner struct {
	Email *string `json:"email,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewSendEmailVerificationTokenRequestToInner instantiates a new SendEmailVerificationTokenRequestToInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendEmailVerificationTokenRequestToInner() *SendEmailVerificationTokenRequestToInner {
	this := SendEmailVerificationTokenRequestToInner{}
	return &this
}

// NewSendEmailVerificationTokenRequestToInnerWithDefaults instantiates a new SendEmailVerificationTokenRequestToInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendEmailVerificationTokenRequestToInnerWithDefaults() *SendEmailVerificationTokenRequestToInner {
	this := SendEmailVerificationTokenRequestToInner{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *SendEmailVerificationTokenRequestToInner) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEmailVerificationTokenRequestToInner) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *SendEmailVerificationTokenRequestToInner) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *SendEmailVerificationTokenRequestToInner) SetEmail(v string) {
	o.Email = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SendEmailVerificationTokenRequestToInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEmailVerificationTokenRequestToInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SendEmailVerificationTokenRequestToInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SendEmailVerificationTokenRequestToInner) SetName(v string) {
	o.Name = &v
}

func (o SendEmailVerificationTokenRequestToInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendEmailVerificationTokenRequestToInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableSendEmailVerificationTokenRequestToInner struct {
	value *SendEmailVerificationTokenRequestToInner
	isSet bool
}

func (v NullableSendEmailVerificationTokenRequestToInner) Get() *SendEmailVerificationTokenRequestToInner {
	return v.value
}

func (v *NullableSendEmailVerificationTokenRequestToInner) Set(val *SendEmailVerificationTokenRequestToInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSendEmailVerificationTokenRequestToInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSendEmailVerificationTokenRequestToInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendEmailVerificationTokenRequestToInner(val *SendEmailVerificationTokenRequestToInner) *NullableSendEmailVerificationTokenRequestToInner {
	return &NullableSendEmailVerificationTokenRequestToInner{value: val, isSet: true}
}

func (v NullableSendEmailVerificationTokenRequestToInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendEmailVerificationTokenRequestToInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


