/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the CalculateMmsCampaignPriceData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalculateMmsCampaignPriceData{}

// CalculateMmsCampaignPriceData struct for CalculateMmsCampaignPriceData
type CalculateMmsCampaignPriceData struct {
	// The total number of records.
	TotalCount *int32 `json:"total_count,omitempty"`
	// The total price of the MMS campaign.
	TotalPrice *string `json:"total_price,omitempty"`
	Data *CalculateMmsCampaignPriceDataData `json:"data,omitempty"`
	Currency *Currency `json:"_currency,omitempty"`
}

// NewCalculateMmsCampaignPriceData instantiates a new CalculateMmsCampaignPriceData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalculateMmsCampaignPriceData() *CalculateMmsCampaignPriceData {
	this := CalculateMmsCampaignPriceData{}
	return &this
}

// NewCalculateMmsCampaignPriceDataWithDefaults instantiates a new CalculateMmsCampaignPriceData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalculateMmsCampaignPriceDataWithDefaults() *CalculateMmsCampaignPriceData {
	this := CalculateMmsCampaignPriceData{}
	return &this
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *CalculateMmsCampaignPriceData) GetTotalCount() int32 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateMmsCampaignPriceData) GetTotalCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *CalculateMmsCampaignPriceData) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *CalculateMmsCampaignPriceData) SetTotalCount(v int32) {
	o.TotalCount = &v
}

// GetTotalPrice returns the TotalPrice field value if set, zero value otherwise.
func (o *CalculateMmsCampaignPriceData) GetTotalPrice() string {
	if o == nil || IsNil(o.TotalPrice) {
		var ret string
		return ret
	}
	return *o.TotalPrice
}

// GetTotalPriceOk returns a tuple with the TotalPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateMmsCampaignPriceData) GetTotalPriceOk() (*string, bool) {
	if o == nil || IsNil(o.TotalPrice) {
		return nil, false
	}
	return o.TotalPrice, true
}

// HasTotalPrice returns a boolean if a field has been set.
func (o *CalculateMmsCampaignPriceData) HasTotalPrice() bool {
	if o != nil && !IsNil(o.TotalPrice) {
		return true
	}

	return false
}

// SetTotalPrice gets a reference to the given string and assigns it to the TotalPrice field.
func (o *CalculateMmsCampaignPriceData) SetTotalPrice(v string) {
	o.TotalPrice = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CalculateMmsCampaignPriceData) GetData() CalculateMmsCampaignPriceDataData {
	if o == nil || IsNil(o.Data) {
		var ret CalculateMmsCampaignPriceDataData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateMmsCampaignPriceData) GetDataOk() (*CalculateMmsCampaignPriceDataData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CalculateMmsCampaignPriceData) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CalculateMmsCampaignPriceDataData and assigns it to the Data field.
func (o *CalculateMmsCampaignPriceData) SetData(v CalculateMmsCampaignPriceDataData) {
	o.Data = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *CalculateMmsCampaignPriceData) GetCurrency() Currency {
	if o == nil || IsNil(o.Currency) {
		var ret Currency
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateMmsCampaignPriceData) GetCurrencyOk() (*Currency, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *CalculateMmsCampaignPriceData) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given Currency and assigns it to the Currency field.
func (o *CalculateMmsCampaignPriceData) SetCurrency(v Currency) {
	o.Currency = &v
}

func (o CalculateMmsCampaignPriceData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalculateMmsCampaignPriceData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalCount) {
		toSerialize["total_count"] = o.TotalCount
	}
	if !IsNil(o.TotalPrice) {
		toSerialize["total_price"] = o.TotalPrice
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Currency) {
		toSerialize["_currency"] = o.Currency
	}
	return toSerialize, nil
}

type NullableCalculateMmsCampaignPriceData struct {
	value *CalculateMmsCampaignPriceData
	isSet bool
}

func (v NullableCalculateMmsCampaignPriceData) Get() *CalculateMmsCampaignPriceData {
	return v.value
}

func (v *NullableCalculateMmsCampaignPriceData) Set(val *CalculateMmsCampaignPriceData) {
	v.value = val
	v.isSet = true
}

func (v NullableCalculateMmsCampaignPriceData) IsSet() bool {
	return v.isSet
}

func (v *NullableCalculateMmsCampaignPriceData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalculateMmsCampaignPriceData(val *CalculateMmsCampaignPriceData) *NullableCalculateMmsCampaignPriceData {
	return &NullableCalculateMmsCampaignPriceData{value: val, isSet: true}
}

func (v NullableCalculateMmsCampaignPriceData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalculateMmsCampaignPriceData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


