/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateTestInboundSmsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTestInboundSmsRequest{}

// CreateTestInboundSmsRequest struct for CreateTestInboundSmsRequest
type CreateTestInboundSmsRequest struct {
	// The webhook URL where the inbound SMS will be sent to.  <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note:</h4>   <p>You can create a webhook URL in <em>Pipedream</em> to test receiving the inbound SMS. Follow the instructions <a href=\"https://help.clicksend.com/en/articles/43703-integration-guide-pipedream\" target=\"_blank\">here.</a></p> </div>  
	Url string `json:"url"`
	// Specifies the HTTP method used when the webhook sends a request to the URL. The available options are:  - **post** (Default): Sends the event data using an HTTP POST request.      - **get**: Sends the event data as query parameters in an HTTP GET request.      - **json**: Sends the event data using a custom JSON format (via a POST request).      This parameter is used to determine how the data will be transmitted, depending on your preferred method and how the receiving system is designed to process incoming requests.
	WebhookType *string `json:"webhook_type,omitempty"`
}

type _CreateTestInboundSmsRequest CreateTestInboundSmsRequest

// NewCreateTestInboundSmsRequest instantiates a new CreateTestInboundSmsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTestInboundSmsRequest(url string) *CreateTestInboundSmsRequest {
	this := CreateTestInboundSmsRequest{}
	this.Url = url
	return &this
}

// NewCreateTestInboundSmsRequestWithDefaults instantiates a new CreateTestInboundSmsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTestInboundSmsRequestWithDefaults() *CreateTestInboundSmsRequest {
	this := CreateTestInboundSmsRequest{}
	return &this
}

// GetUrl returns the Url field value
func (o *CreateTestInboundSmsRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateTestInboundSmsRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateTestInboundSmsRequest) SetUrl(v string) {
	o.Url = v
}

// GetWebhookType returns the WebhookType field value if set, zero value otherwise.
func (o *CreateTestInboundSmsRequest) GetWebhookType() string {
	if o == nil || IsNil(o.WebhookType) {
		var ret string
		return ret
	}
	return *o.WebhookType
}

// GetWebhookTypeOk returns a tuple with the WebhookType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestInboundSmsRequest) GetWebhookTypeOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookType) {
		return nil, false
	}
	return o.WebhookType, true
}

// HasWebhookType returns a boolean if a field has been set.
func (o *CreateTestInboundSmsRequest) HasWebhookType() bool {
	if o != nil && !IsNil(o.WebhookType) {
		return true
	}

	return false
}

// SetWebhookType gets a reference to the given string and assigns it to the WebhookType field.
func (o *CreateTestInboundSmsRequest) SetWebhookType(v string) {
	o.WebhookType = &v
}

func (o CreateTestInboundSmsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTestInboundSmsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	if !IsNil(o.WebhookType) {
		toSerialize["webhook_type"] = o.WebhookType
	}
	return toSerialize, nil
}

func (o *CreateTestInboundSmsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTestInboundSmsRequest := _CreateTestInboundSmsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTestInboundSmsRequest)

	if err != nil {
		return err
	}

	*o = CreateTestInboundSmsRequest(varCreateTestInboundSmsRequest)

	return err
}

type NullableCreateTestInboundSmsRequest struct {
	value *CreateTestInboundSmsRequest
	isSet bool
}

func (v NullableCreateTestInboundSmsRequest) Get() *CreateTestInboundSmsRequest {
	return v.value
}

func (v *NullableCreateTestInboundSmsRequest) Set(val *CreateTestInboundSmsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTestInboundSmsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTestInboundSmsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTestInboundSmsRequest(val *CreateTestInboundSmsRequest) *NullableCreateTestInboundSmsRequest {
	return &NullableCreateTestInboundSmsRequest{value: val, isSet: true}
}

func (v NullableCreateTestInboundSmsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTestInboundSmsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


