/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListCompliantSenderTypes200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCompliantSenderTypes200ResponseData{}

// ListCompliantSenderTypes200ResponseData struct for ListCompliantSenderTypes200ResponseData
type ListCompliantSenderTypes200ResponseData struct {
	Data []ListCompliantSenderTypes200ResponseDataDataInner `json:"data"`
}

type _ListCompliantSenderTypes200ResponseData ListCompliantSenderTypes200ResponseData

// NewListCompliantSenderTypes200ResponseData instantiates a new ListCompliantSenderTypes200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCompliantSenderTypes200ResponseData(data []ListCompliantSenderTypes200ResponseDataDataInner) *ListCompliantSenderTypes200ResponseData {
	this := ListCompliantSenderTypes200ResponseData{}
	this.Data = data
	return &this
}

// NewListCompliantSenderTypes200ResponseDataWithDefaults instantiates a new ListCompliantSenderTypes200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCompliantSenderTypes200ResponseDataWithDefaults() *ListCompliantSenderTypes200ResponseData {
	this := ListCompliantSenderTypes200ResponseData{}
	return &this
}

// GetData returns the Data field value
func (o *ListCompliantSenderTypes200ResponseData) GetData() []ListCompliantSenderTypes200ResponseDataDataInner {
	if o == nil {
		var ret []ListCompliantSenderTypes200ResponseDataDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListCompliantSenderTypes200ResponseData) GetDataOk() ([]ListCompliantSenderTypes200ResponseDataDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListCompliantSenderTypes200ResponseData) SetData(v []ListCompliantSenderTypes200ResponseDataDataInner) {
	o.Data = v
}

func (o ListCompliantSenderTypes200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCompliantSenderTypes200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ListCompliantSenderTypes200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListCompliantSenderTypes200ResponseData := _ListCompliantSenderTypes200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListCompliantSenderTypes200ResponseData)

	if err != nil {
		return err
	}

	*o = ListCompliantSenderTypes200ResponseData(varListCompliantSenderTypes200ResponseData)

	return err
}

type NullableListCompliantSenderTypes200ResponseData struct {
	value *ListCompliantSenderTypes200ResponseData
	isSet bool
}

func (v NullableListCompliantSenderTypes200ResponseData) Get() *ListCompliantSenderTypes200ResponseData {
	return v.value
}

func (v *NullableListCompliantSenderTypes200ResponseData) Set(val *ListCompliantSenderTypes200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableListCompliantSenderTypes200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableListCompliantSenderTypes200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCompliantSenderTypes200ResponseData(val *ListCompliantSenderTypes200ResponseData) *NullableListCompliantSenderTypes200ResponseData {
	return &NullableListCompliantSenderTypes200ResponseData{value: val, isSet: true}
}

func (v NullableListCompliantSenderTypes200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCompliantSenderTypes200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


