/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateTestSmsReceiptRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTestSmsReceiptRequest{}

// CreateTestSmsReceiptRequest struct for CreateTestSmsReceiptRequest
type CreateTestSmsReceiptRequest struct {
	// The webhook URL where the delivery receipt will be sent to. You can set the value to **poll** to send it to the ClickSend   system, and then retrieve it with the **View SMS Receipt** endpoint  <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note:</h4>   <p>You can create a webhook URL in Pipedream to test receiving the SMS receipt. Follow the instructions <a target=\"_blank\" href=\"https://help.clicksend.com/en/articles/43703-integration-guide-pipedream\">here</a>.</p> </div>
	Url string `json:"url"`
}

type _CreateTestSmsReceiptRequest CreateTestSmsReceiptRequest

// NewCreateTestSmsReceiptRequest instantiates a new CreateTestSmsReceiptRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTestSmsReceiptRequest(url string) *CreateTestSmsReceiptRequest {
	this := CreateTestSmsReceiptRequest{}
	this.Url = url
	return &this
}

// NewCreateTestSmsReceiptRequestWithDefaults instantiates a new CreateTestSmsReceiptRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTestSmsReceiptRequestWithDefaults() *CreateTestSmsReceiptRequest {
	this := CreateTestSmsReceiptRequest{}
	return &this
}

// GetUrl returns the Url field value
func (o *CreateTestSmsReceiptRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateTestSmsReceiptRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateTestSmsReceiptRequest) SetUrl(v string) {
	o.Url = v
}

func (o CreateTestSmsReceiptRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTestSmsReceiptRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *CreateTestSmsReceiptRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTestSmsReceiptRequest := _CreateTestSmsReceiptRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateTestSmsReceiptRequest)

	if err != nil {
		return err
	}

	*o = CreateTestSmsReceiptRequest(varCreateTestSmsReceiptRequest)

	return err
}

type NullableCreateTestSmsReceiptRequest struct {
	value *CreateTestSmsReceiptRequest
	isSet bool
}

func (v NullableCreateTestSmsReceiptRequest) Get() *CreateTestSmsReceiptRequest {
	return v.value
}

func (v *NullableCreateTestSmsReceiptRequest) Set(val *CreateTestSmsReceiptRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTestSmsReceiptRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTestSmsReceiptRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTestSmsReceiptRequest(val *CreateTestSmsReceiptRequest) *NullableCreateTestSmsReceiptRequest {
	return &NullableCreateTestSmsReceiptRequest{value: val, isSet: true}
}

func (v NullableCreateTestSmsReceiptRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTestSmsReceiptRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


