/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the EmailCampaign type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailCampaign{}

// EmailCampaign struct for EmailCampaign
type EmailCampaign struct {
	// The ID of the email campaign.
	EmailCampaignId *int32 `json:"email_campaign_id,omitempty"`
	// The name of the email campaign.
	Name *string `json:"name,omitempty"`
	// The ID of the user who created the email campaign.
	UserId *int32 `json:"user_id,omitempty"`
	// The ID of the subaccount associated with the email campaign.
	SubaccountId *int32 `json:"subaccount_id,omitempty"`
	// The subject of the email campaign.
	Subject *string `json:"subject,omitempty"`
	// The ID of the email list associated with the campaign.
	ListId *int32 `json:"list_id,omitempty"`
	// The ID of the sender's email address.
	FromEmailAddressId *int32 `json:"from_email_address_id,omitempty"`
	// The name of the sender.
	FromName *string `json:"from_name,omitempty"`
	// The ID of the email template used in the campaign.
	TemplateId *int32 `json:"template_id,omitempty"`
	// The schedule for sending the email campaign.
	Schedule *string `json:"schedule,omitempty"`
	// The status of the email campaign (e.g., Sent, Scheduled, Draft).
	Status *string `json:"status,omitempty"`
	// The date when the email campaign was added.
	DateAdded *string `json:"date_added,omitempty"`
	// A custom string associated with the email campaign.
	CustomString *string `json:"custom_string,omitempty"`
	// The count of emails sent in the campaign.
	SendCount *int32 `json:"send_count,omitempty"`
	// The count of emails opened in the campaign.
	OpenCount *int32 `json:"open_count,omitempty"`
	// The count of links clicked in the campaign.
	ClickCount *int32 `json:"click_count,omitempty"`
	// The count of hard bounces in the campaign.
	HardBounceCount *int32 `json:"hard_bounce_count,omitempty"`
	// The count of soft bounces in the campaign.
	SoftBounceCount *int32 `json:"soft_bounce_count,omitempty"`
	// The count of abuse complaints in the campaign.
	AbuseCount *int32 `json:"abuse_count,omitempty"`
	// The count of unsubscribes in the campaign.
	UnsubscribeCount *int32 `json:"unsubscribe_count,omitempty"`
	// The body of the email campaign.
	Body *string `json:"body,omitempty"`
	// The plain text body of the email campaign.
	BodyPlainText *string `json:"body_plain_text,omitempty"`
}

// NewEmailCampaign instantiates a new EmailCampaign object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailCampaign() *EmailCampaign {
	this := EmailCampaign{}
	return &this
}

// NewEmailCampaignWithDefaults instantiates a new EmailCampaign object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailCampaignWithDefaults() *EmailCampaign {
	this := EmailCampaign{}
	return &this
}

// GetEmailCampaignId returns the EmailCampaignId field value if set, zero value otherwise.
func (o *EmailCampaign) GetEmailCampaignId() int32 {
	if o == nil || IsNil(o.EmailCampaignId) {
		var ret int32
		return ret
	}
	return *o.EmailCampaignId
}

// GetEmailCampaignIdOk returns a tuple with the EmailCampaignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetEmailCampaignIdOk() (*int32, bool) {
	if o == nil || IsNil(o.EmailCampaignId) {
		return nil, false
	}
	return o.EmailCampaignId, true
}

// HasEmailCampaignId returns a boolean if a field has been set.
func (o *EmailCampaign) HasEmailCampaignId() bool {
	if o != nil && !IsNil(o.EmailCampaignId) {
		return true
	}

	return false
}

// SetEmailCampaignId gets a reference to the given int32 and assigns it to the EmailCampaignId field.
func (o *EmailCampaign) SetEmailCampaignId(v int32) {
	o.EmailCampaignId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EmailCampaign) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EmailCampaign) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EmailCampaign) SetName(v string) {
	o.Name = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *EmailCampaign) GetUserId() int32 {
	if o == nil || IsNil(o.UserId) {
		var ret int32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *EmailCampaign) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int32 and assigns it to the UserId field.
func (o *EmailCampaign) SetUserId(v int32) {
	o.UserId = &v
}

// GetSubaccountId returns the SubaccountId field value if set, zero value otherwise.
func (o *EmailCampaign) GetSubaccountId() int32 {
	if o == nil || IsNil(o.SubaccountId) {
		var ret int32
		return ret
	}
	return *o.SubaccountId
}

// GetSubaccountIdOk returns a tuple with the SubaccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetSubaccountIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SubaccountId) {
		return nil, false
	}
	return o.SubaccountId, true
}

// HasSubaccountId returns a boolean if a field has been set.
func (o *EmailCampaign) HasSubaccountId() bool {
	if o != nil && !IsNil(o.SubaccountId) {
		return true
	}

	return false
}

// SetSubaccountId gets a reference to the given int32 and assigns it to the SubaccountId field.
func (o *EmailCampaign) SetSubaccountId(v int32) {
	o.SubaccountId = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *EmailCampaign) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *EmailCampaign) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *EmailCampaign) SetSubject(v string) {
	o.Subject = &v
}

// GetListId returns the ListId field value if set, zero value otherwise.
func (o *EmailCampaign) GetListId() int32 {
	if o == nil || IsNil(o.ListId) {
		var ret int32
		return ret
	}
	return *o.ListId
}

// GetListIdOk returns a tuple with the ListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetListIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ListId) {
		return nil, false
	}
	return o.ListId, true
}

// HasListId returns a boolean if a field has been set.
func (o *EmailCampaign) HasListId() bool {
	if o != nil && !IsNil(o.ListId) {
		return true
	}

	return false
}

// SetListId gets a reference to the given int32 and assigns it to the ListId field.
func (o *EmailCampaign) SetListId(v int32) {
	o.ListId = &v
}

// GetFromEmailAddressId returns the FromEmailAddressId field value if set, zero value otherwise.
func (o *EmailCampaign) GetFromEmailAddressId() int32 {
	if o == nil || IsNil(o.FromEmailAddressId) {
		var ret int32
		return ret
	}
	return *o.FromEmailAddressId
}

// GetFromEmailAddressIdOk returns a tuple with the FromEmailAddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetFromEmailAddressIdOk() (*int32, bool) {
	if o == nil || IsNil(o.FromEmailAddressId) {
		return nil, false
	}
	return o.FromEmailAddressId, true
}

// HasFromEmailAddressId returns a boolean if a field has been set.
func (o *EmailCampaign) HasFromEmailAddressId() bool {
	if o != nil && !IsNil(o.FromEmailAddressId) {
		return true
	}

	return false
}

// SetFromEmailAddressId gets a reference to the given int32 and assigns it to the FromEmailAddressId field.
func (o *EmailCampaign) SetFromEmailAddressId(v int32) {
	o.FromEmailAddressId = &v
}

// GetFromName returns the FromName field value if set, zero value otherwise.
func (o *EmailCampaign) GetFromName() string {
	if o == nil || IsNil(o.FromName) {
		var ret string
		return ret
	}
	return *o.FromName
}

// GetFromNameOk returns a tuple with the FromName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetFromNameOk() (*string, bool) {
	if o == nil || IsNil(o.FromName) {
		return nil, false
	}
	return o.FromName, true
}

// HasFromName returns a boolean if a field has been set.
func (o *EmailCampaign) HasFromName() bool {
	if o != nil && !IsNil(o.FromName) {
		return true
	}

	return false
}

// SetFromName gets a reference to the given string and assigns it to the FromName field.
func (o *EmailCampaign) SetFromName(v string) {
	o.FromName = &v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *EmailCampaign) GetTemplateId() int32 {
	if o == nil || IsNil(o.TemplateId) {
		var ret int32
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetTemplateIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TemplateId) {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *EmailCampaign) HasTemplateId() bool {
	if o != nil && !IsNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given int32 and assigns it to the TemplateId field.
func (o *EmailCampaign) SetTemplateId(v int32) {
	o.TemplateId = &v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *EmailCampaign) GetSchedule() string {
	if o == nil || IsNil(o.Schedule) {
		var ret string
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetScheduleOk() (*string, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *EmailCampaign) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given string and assigns it to the Schedule field.
func (o *EmailCampaign) SetSchedule(v string) {
	o.Schedule = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EmailCampaign) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EmailCampaign) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *EmailCampaign) SetStatus(v string) {
	o.Status = &v
}

// GetDateAdded returns the DateAdded field value if set, zero value otherwise.
func (o *EmailCampaign) GetDateAdded() string {
	if o == nil || IsNil(o.DateAdded) {
		var ret string
		return ret
	}
	return *o.DateAdded
}

// GetDateAddedOk returns a tuple with the DateAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetDateAddedOk() (*string, bool) {
	if o == nil || IsNil(o.DateAdded) {
		return nil, false
	}
	return o.DateAdded, true
}

// HasDateAdded returns a boolean if a field has been set.
func (o *EmailCampaign) HasDateAdded() bool {
	if o != nil && !IsNil(o.DateAdded) {
		return true
	}

	return false
}

// SetDateAdded gets a reference to the given string and assigns it to the DateAdded field.
func (o *EmailCampaign) SetDateAdded(v string) {
	o.DateAdded = &v
}

// GetCustomString returns the CustomString field value if set, zero value otherwise.
func (o *EmailCampaign) GetCustomString() string {
	if o == nil || IsNil(o.CustomString) {
		var ret string
		return ret
	}
	return *o.CustomString
}

// GetCustomStringOk returns a tuple with the CustomString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetCustomStringOk() (*string, bool) {
	if o == nil || IsNil(o.CustomString) {
		return nil, false
	}
	return o.CustomString, true
}

// HasCustomString returns a boolean if a field has been set.
func (o *EmailCampaign) HasCustomString() bool {
	if o != nil && !IsNil(o.CustomString) {
		return true
	}

	return false
}

// SetCustomString gets a reference to the given string and assigns it to the CustomString field.
func (o *EmailCampaign) SetCustomString(v string) {
	o.CustomString = &v
}

// GetSendCount returns the SendCount field value if set, zero value otherwise.
func (o *EmailCampaign) GetSendCount() int32 {
	if o == nil || IsNil(o.SendCount) {
		var ret int32
		return ret
	}
	return *o.SendCount
}

// GetSendCountOk returns a tuple with the SendCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetSendCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SendCount) {
		return nil, false
	}
	return o.SendCount, true
}

// HasSendCount returns a boolean if a field has been set.
func (o *EmailCampaign) HasSendCount() bool {
	if o != nil && !IsNil(o.SendCount) {
		return true
	}

	return false
}

// SetSendCount gets a reference to the given int32 and assigns it to the SendCount field.
func (o *EmailCampaign) SetSendCount(v int32) {
	o.SendCount = &v
}

// GetOpenCount returns the OpenCount field value if set, zero value otherwise.
func (o *EmailCampaign) GetOpenCount() int32 {
	if o == nil || IsNil(o.OpenCount) {
		var ret int32
		return ret
	}
	return *o.OpenCount
}

// GetOpenCountOk returns a tuple with the OpenCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetOpenCountOk() (*int32, bool) {
	if o == nil || IsNil(o.OpenCount) {
		return nil, false
	}
	return o.OpenCount, true
}

// HasOpenCount returns a boolean if a field has been set.
func (o *EmailCampaign) HasOpenCount() bool {
	if o != nil && !IsNil(o.OpenCount) {
		return true
	}

	return false
}

// SetOpenCount gets a reference to the given int32 and assigns it to the OpenCount field.
func (o *EmailCampaign) SetOpenCount(v int32) {
	o.OpenCount = &v
}

// GetClickCount returns the ClickCount field value if set, zero value otherwise.
func (o *EmailCampaign) GetClickCount() int32 {
	if o == nil || IsNil(o.ClickCount) {
		var ret int32
		return ret
	}
	return *o.ClickCount
}

// GetClickCountOk returns a tuple with the ClickCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetClickCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ClickCount) {
		return nil, false
	}
	return o.ClickCount, true
}

// HasClickCount returns a boolean if a field has been set.
func (o *EmailCampaign) HasClickCount() bool {
	if o != nil && !IsNil(o.ClickCount) {
		return true
	}

	return false
}

// SetClickCount gets a reference to the given int32 and assigns it to the ClickCount field.
func (o *EmailCampaign) SetClickCount(v int32) {
	o.ClickCount = &v
}

// GetHardBounceCount returns the HardBounceCount field value if set, zero value otherwise.
func (o *EmailCampaign) GetHardBounceCount() int32 {
	if o == nil || IsNil(o.HardBounceCount) {
		var ret int32
		return ret
	}
	return *o.HardBounceCount
}

// GetHardBounceCountOk returns a tuple with the HardBounceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetHardBounceCountOk() (*int32, bool) {
	if o == nil || IsNil(o.HardBounceCount) {
		return nil, false
	}
	return o.HardBounceCount, true
}

// HasHardBounceCount returns a boolean if a field has been set.
func (o *EmailCampaign) HasHardBounceCount() bool {
	if o != nil && !IsNil(o.HardBounceCount) {
		return true
	}

	return false
}

// SetHardBounceCount gets a reference to the given int32 and assigns it to the HardBounceCount field.
func (o *EmailCampaign) SetHardBounceCount(v int32) {
	o.HardBounceCount = &v
}

// GetSoftBounceCount returns the SoftBounceCount field value if set, zero value otherwise.
func (o *EmailCampaign) GetSoftBounceCount() int32 {
	if o == nil || IsNil(o.SoftBounceCount) {
		var ret int32
		return ret
	}
	return *o.SoftBounceCount
}

// GetSoftBounceCountOk returns a tuple with the SoftBounceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetSoftBounceCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SoftBounceCount) {
		return nil, false
	}
	return o.SoftBounceCount, true
}

// HasSoftBounceCount returns a boolean if a field has been set.
func (o *EmailCampaign) HasSoftBounceCount() bool {
	if o != nil && !IsNil(o.SoftBounceCount) {
		return true
	}

	return false
}

// SetSoftBounceCount gets a reference to the given int32 and assigns it to the SoftBounceCount field.
func (o *EmailCampaign) SetSoftBounceCount(v int32) {
	o.SoftBounceCount = &v
}

// GetAbuseCount returns the AbuseCount field value if set, zero value otherwise.
func (o *EmailCampaign) GetAbuseCount() int32 {
	if o == nil || IsNil(o.AbuseCount) {
		var ret int32
		return ret
	}
	return *o.AbuseCount
}

// GetAbuseCountOk returns a tuple with the AbuseCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetAbuseCountOk() (*int32, bool) {
	if o == nil || IsNil(o.AbuseCount) {
		return nil, false
	}
	return o.AbuseCount, true
}

// HasAbuseCount returns a boolean if a field has been set.
func (o *EmailCampaign) HasAbuseCount() bool {
	if o != nil && !IsNil(o.AbuseCount) {
		return true
	}

	return false
}

// SetAbuseCount gets a reference to the given int32 and assigns it to the AbuseCount field.
func (o *EmailCampaign) SetAbuseCount(v int32) {
	o.AbuseCount = &v
}

// GetUnsubscribeCount returns the UnsubscribeCount field value if set, zero value otherwise.
func (o *EmailCampaign) GetUnsubscribeCount() int32 {
	if o == nil || IsNil(o.UnsubscribeCount) {
		var ret int32
		return ret
	}
	return *o.UnsubscribeCount
}

// GetUnsubscribeCountOk returns a tuple with the UnsubscribeCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetUnsubscribeCountOk() (*int32, bool) {
	if o == nil || IsNil(o.UnsubscribeCount) {
		return nil, false
	}
	return o.UnsubscribeCount, true
}

// HasUnsubscribeCount returns a boolean if a field has been set.
func (o *EmailCampaign) HasUnsubscribeCount() bool {
	if o != nil && !IsNil(o.UnsubscribeCount) {
		return true
	}

	return false
}

// SetUnsubscribeCount gets a reference to the given int32 and assigns it to the UnsubscribeCount field.
func (o *EmailCampaign) SetUnsubscribeCount(v int32) {
	o.UnsubscribeCount = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *EmailCampaign) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *EmailCampaign) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *EmailCampaign) SetBody(v string) {
	o.Body = &v
}

// GetBodyPlainText returns the BodyPlainText field value if set, zero value otherwise.
func (o *EmailCampaign) GetBodyPlainText() string {
	if o == nil || IsNil(o.BodyPlainText) {
		var ret string
		return ret
	}
	return *o.BodyPlainText
}

// GetBodyPlainTextOk returns a tuple with the BodyPlainText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailCampaign) GetBodyPlainTextOk() (*string, bool) {
	if o == nil || IsNil(o.BodyPlainText) {
		return nil, false
	}
	return o.BodyPlainText, true
}

// HasBodyPlainText returns a boolean if a field has been set.
func (o *EmailCampaign) HasBodyPlainText() bool {
	if o != nil && !IsNil(o.BodyPlainText) {
		return true
	}

	return false
}

// SetBodyPlainText gets a reference to the given string and assigns it to the BodyPlainText field.
func (o *EmailCampaign) SetBodyPlainText(v string) {
	o.BodyPlainText = &v
}

func (o EmailCampaign) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailCampaign) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EmailCampaignId) {
		toSerialize["email_campaign_id"] = o.EmailCampaignId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.SubaccountId) {
		toSerialize["subaccount_id"] = o.SubaccountId
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.ListId) {
		toSerialize["list_id"] = o.ListId
	}
	if !IsNil(o.FromEmailAddressId) {
		toSerialize["from_email_address_id"] = o.FromEmailAddressId
	}
	if !IsNil(o.FromName) {
		toSerialize["from_name"] = o.FromName
	}
	if !IsNil(o.TemplateId) {
		toSerialize["template_id"] = o.TemplateId
	}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.DateAdded) {
		toSerialize["date_added"] = o.DateAdded
	}
	if !IsNil(o.CustomString) {
		toSerialize["custom_string"] = o.CustomString
	}
	if !IsNil(o.SendCount) {
		toSerialize["send_count"] = o.SendCount
	}
	if !IsNil(o.OpenCount) {
		toSerialize["open_count"] = o.OpenCount
	}
	if !IsNil(o.ClickCount) {
		toSerialize["click_count"] = o.ClickCount
	}
	if !IsNil(o.HardBounceCount) {
		toSerialize["hard_bounce_count"] = o.HardBounceCount
	}
	if !IsNil(o.SoftBounceCount) {
		toSerialize["soft_bounce_count"] = o.SoftBounceCount
	}
	if !IsNil(o.AbuseCount) {
		toSerialize["abuse_count"] = o.AbuseCount
	}
	if !IsNil(o.UnsubscribeCount) {
		toSerialize["unsubscribe_count"] = o.UnsubscribeCount
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.BodyPlainText) {
		toSerialize["body_plain_text"] = o.BodyPlainText
	}
	return toSerialize, nil
}

type NullableEmailCampaign struct {
	value *EmailCampaign
	isSet bool
}

func (v NullableEmailCampaign) Get() *EmailCampaign {
	return v.value
}

func (v *NullableEmailCampaign) Set(val *EmailCampaign) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailCampaign) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailCampaign) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailCampaign(val *EmailCampaign) *NullableEmailCampaign {
	return &NullableEmailCampaign{value: val, isSet: true}
}

func (v NullableEmailCampaign) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailCampaign) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


