/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the TransactionalEmail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionalEmail{}

// TransactionalEmail struct for TransactionalEmail
type TransactionalEmail struct {
	// The ID of the user.
	UserId *int32 `json:"user_id,omitempty"`
	// The ID of the subaccount.
	SubaccountId *int32 `json:"subaccount_id,omitempty"`
	// The ID of the from email address.
	FromEmailAddressId *int32 `json:"from_email_address_id,omitempty"`
	// The name of the sender.
	FromName *string `json:"from_name,omitempty"`
	To []SendEmailRequestToInner `json:"to,omitempty"`
	Cc []SendEmailRequestToInner `json:"cc,omitempty"`
	Bcc []SendEmailRequestToInner `json:"bcc,omitempty"`
	// The subject of the email.
	Subject *string `json:"subject,omitempty"`
	// The HTML body of the email.
	Body *string `json:"body,omitempty"`
	// The plain text body of the email.
	BodyPlainText *string `json:"body_plain_text,omitempty"`
	// The timestamp indicating the scheduled time of the email.
	Schedule *int32 `json:"schedule,omitempty"`
	// The ID of the email message.
	MessageId *string `json:"message_id,omitempty"`
	// The status of the email.
	Status *string `json:"status,omitempty"`
	// The text description of the email status.
	StatusText *string `json:"status_text,omitempty"`
	// The count of soft bounces.
	SoftBounceCount *int32 `json:"soft_bounce_count,omitempty"`
	// The count of hard bounces.
	HardBounceCount *int32 `json:"hard_bounce_count,omitempty"`
	// The price of the email.
	Price *string `json:"price,omitempty"`
	// The timestamp indicating when the email was added.
	DateAdded *int32 `json:"date_added,omitempty"`
	// A custom string.
	CustomString NullableString `json:"custom_string,omitempty"`
	Attachments []Attachment `json:"_attachments,omitempty"`
	Currency *Currency `json:"_currency,omitempty"`
}

// NewTransactionalEmail instantiates a new TransactionalEmail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionalEmail() *TransactionalEmail {
	this := TransactionalEmail{}
	return &this
}

// NewTransactionalEmailWithDefaults instantiates a new TransactionalEmail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionalEmailWithDefaults() *TransactionalEmail {
	this := TransactionalEmail{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *TransactionalEmail) GetUserId() int32 {
	if o == nil || IsNil(o.UserId) {
		var ret int32
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetUserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *TransactionalEmail) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int32 and assigns it to the UserId field.
func (o *TransactionalEmail) SetUserId(v int32) {
	o.UserId = &v
}

// GetSubaccountId returns the SubaccountId field value if set, zero value otherwise.
func (o *TransactionalEmail) GetSubaccountId() int32 {
	if o == nil || IsNil(o.SubaccountId) {
		var ret int32
		return ret
	}
	return *o.SubaccountId
}

// GetSubaccountIdOk returns a tuple with the SubaccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetSubaccountIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SubaccountId) {
		return nil, false
	}
	return o.SubaccountId, true
}

// HasSubaccountId returns a boolean if a field has been set.
func (o *TransactionalEmail) HasSubaccountId() bool {
	if o != nil && !IsNil(o.SubaccountId) {
		return true
	}

	return false
}

// SetSubaccountId gets a reference to the given int32 and assigns it to the SubaccountId field.
func (o *TransactionalEmail) SetSubaccountId(v int32) {
	o.SubaccountId = &v
}

// GetFromEmailAddressId returns the FromEmailAddressId field value if set, zero value otherwise.
func (o *TransactionalEmail) GetFromEmailAddressId() int32 {
	if o == nil || IsNil(o.FromEmailAddressId) {
		var ret int32
		return ret
	}
	return *o.FromEmailAddressId
}

// GetFromEmailAddressIdOk returns a tuple with the FromEmailAddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetFromEmailAddressIdOk() (*int32, bool) {
	if o == nil || IsNil(o.FromEmailAddressId) {
		return nil, false
	}
	return o.FromEmailAddressId, true
}

// HasFromEmailAddressId returns a boolean if a field has been set.
func (o *TransactionalEmail) HasFromEmailAddressId() bool {
	if o != nil && !IsNil(o.FromEmailAddressId) {
		return true
	}

	return false
}

// SetFromEmailAddressId gets a reference to the given int32 and assigns it to the FromEmailAddressId field.
func (o *TransactionalEmail) SetFromEmailAddressId(v int32) {
	o.FromEmailAddressId = &v
}

// GetFromName returns the FromName field value if set, zero value otherwise.
func (o *TransactionalEmail) GetFromName() string {
	if o == nil || IsNil(o.FromName) {
		var ret string
		return ret
	}
	return *o.FromName
}

// GetFromNameOk returns a tuple with the FromName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetFromNameOk() (*string, bool) {
	if o == nil || IsNil(o.FromName) {
		return nil, false
	}
	return o.FromName, true
}

// HasFromName returns a boolean if a field has been set.
func (o *TransactionalEmail) HasFromName() bool {
	if o != nil && !IsNil(o.FromName) {
		return true
	}

	return false
}

// SetFromName gets a reference to the given string and assigns it to the FromName field.
func (o *TransactionalEmail) SetFromName(v string) {
	o.FromName = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *TransactionalEmail) GetTo() []SendEmailRequestToInner {
	if o == nil || IsNil(o.To) {
		var ret []SendEmailRequestToInner
		return ret
	}
	return o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetToOk() ([]SendEmailRequestToInner, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *TransactionalEmail) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given []SendEmailRequestToInner and assigns it to the To field.
func (o *TransactionalEmail) SetTo(v []SendEmailRequestToInner) {
	o.To = v
}

// GetCc returns the Cc field value if set, zero value otherwise.
func (o *TransactionalEmail) GetCc() []SendEmailRequestToInner {
	if o == nil || IsNil(o.Cc) {
		var ret []SendEmailRequestToInner
		return ret
	}
	return o.Cc
}

// GetCcOk returns a tuple with the Cc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetCcOk() ([]SendEmailRequestToInner, bool) {
	if o == nil || IsNil(o.Cc) {
		return nil, false
	}
	return o.Cc, true
}

// HasCc returns a boolean if a field has been set.
func (o *TransactionalEmail) HasCc() bool {
	if o != nil && !IsNil(o.Cc) {
		return true
	}

	return false
}

// SetCc gets a reference to the given []SendEmailRequestToInner and assigns it to the Cc field.
func (o *TransactionalEmail) SetCc(v []SendEmailRequestToInner) {
	o.Cc = v
}

// GetBcc returns the Bcc field value if set, zero value otherwise.
func (o *TransactionalEmail) GetBcc() []SendEmailRequestToInner {
	if o == nil || IsNil(o.Bcc) {
		var ret []SendEmailRequestToInner
		return ret
	}
	return o.Bcc
}

// GetBccOk returns a tuple with the Bcc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetBccOk() ([]SendEmailRequestToInner, bool) {
	if o == nil || IsNil(o.Bcc) {
		return nil, false
	}
	return o.Bcc, true
}

// HasBcc returns a boolean if a field has been set.
func (o *TransactionalEmail) HasBcc() bool {
	if o != nil && !IsNil(o.Bcc) {
		return true
	}

	return false
}

// SetBcc gets a reference to the given []SendEmailRequestToInner and assigns it to the Bcc field.
func (o *TransactionalEmail) SetBcc(v []SendEmailRequestToInner) {
	o.Bcc = v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *TransactionalEmail) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *TransactionalEmail) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *TransactionalEmail) SetSubject(v string) {
	o.Subject = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *TransactionalEmail) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *TransactionalEmail) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *TransactionalEmail) SetBody(v string) {
	o.Body = &v
}

// GetBodyPlainText returns the BodyPlainText field value if set, zero value otherwise.
func (o *TransactionalEmail) GetBodyPlainText() string {
	if o == nil || IsNil(o.BodyPlainText) {
		var ret string
		return ret
	}
	return *o.BodyPlainText
}

// GetBodyPlainTextOk returns a tuple with the BodyPlainText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetBodyPlainTextOk() (*string, bool) {
	if o == nil || IsNil(o.BodyPlainText) {
		return nil, false
	}
	return o.BodyPlainText, true
}

// HasBodyPlainText returns a boolean if a field has been set.
func (o *TransactionalEmail) HasBodyPlainText() bool {
	if o != nil && !IsNil(o.BodyPlainText) {
		return true
	}

	return false
}

// SetBodyPlainText gets a reference to the given string and assigns it to the BodyPlainText field.
func (o *TransactionalEmail) SetBodyPlainText(v string) {
	o.BodyPlainText = &v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *TransactionalEmail) GetSchedule() int32 {
	if o == nil || IsNil(o.Schedule) {
		var ret int32
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetScheduleOk() (*int32, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *TransactionalEmail) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given int32 and assigns it to the Schedule field.
func (o *TransactionalEmail) SetSchedule(v int32) {
	o.Schedule = &v
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *TransactionalEmail) GetMessageId() string {
	if o == nil || IsNil(o.MessageId) {
		var ret string
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetMessageIdOk() (*string, bool) {
	if o == nil || IsNil(o.MessageId) {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *TransactionalEmail) HasMessageId() bool {
	if o != nil && !IsNil(o.MessageId) {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given string and assigns it to the MessageId field.
func (o *TransactionalEmail) SetMessageId(v string) {
	o.MessageId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TransactionalEmail) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TransactionalEmail) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TransactionalEmail) SetStatus(v string) {
	o.Status = &v
}

// GetStatusText returns the StatusText field value if set, zero value otherwise.
func (o *TransactionalEmail) GetStatusText() string {
	if o == nil || IsNil(o.StatusText) {
		var ret string
		return ret
	}
	return *o.StatusText
}

// GetStatusTextOk returns a tuple with the StatusText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetStatusTextOk() (*string, bool) {
	if o == nil || IsNil(o.StatusText) {
		return nil, false
	}
	return o.StatusText, true
}

// HasStatusText returns a boolean if a field has been set.
func (o *TransactionalEmail) HasStatusText() bool {
	if o != nil && !IsNil(o.StatusText) {
		return true
	}

	return false
}

// SetStatusText gets a reference to the given string and assigns it to the StatusText field.
func (o *TransactionalEmail) SetStatusText(v string) {
	o.StatusText = &v
}

// GetSoftBounceCount returns the SoftBounceCount field value if set, zero value otherwise.
func (o *TransactionalEmail) GetSoftBounceCount() int32 {
	if o == nil || IsNil(o.SoftBounceCount) {
		var ret int32
		return ret
	}
	return *o.SoftBounceCount
}

// GetSoftBounceCountOk returns a tuple with the SoftBounceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetSoftBounceCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SoftBounceCount) {
		return nil, false
	}
	return o.SoftBounceCount, true
}

// HasSoftBounceCount returns a boolean if a field has been set.
func (o *TransactionalEmail) HasSoftBounceCount() bool {
	if o != nil && !IsNil(o.SoftBounceCount) {
		return true
	}

	return false
}

// SetSoftBounceCount gets a reference to the given int32 and assigns it to the SoftBounceCount field.
func (o *TransactionalEmail) SetSoftBounceCount(v int32) {
	o.SoftBounceCount = &v
}

// GetHardBounceCount returns the HardBounceCount field value if set, zero value otherwise.
func (o *TransactionalEmail) GetHardBounceCount() int32 {
	if o == nil || IsNil(o.HardBounceCount) {
		var ret int32
		return ret
	}
	return *o.HardBounceCount
}

// GetHardBounceCountOk returns a tuple with the HardBounceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetHardBounceCountOk() (*int32, bool) {
	if o == nil || IsNil(o.HardBounceCount) {
		return nil, false
	}
	return o.HardBounceCount, true
}

// HasHardBounceCount returns a boolean if a field has been set.
func (o *TransactionalEmail) HasHardBounceCount() bool {
	if o != nil && !IsNil(o.HardBounceCount) {
		return true
	}

	return false
}

// SetHardBounceCount gets a reference to the given int32 and assigns it to the HardBounceCount field.
func (o *TransactionalEmail) SetHardBounceCount(v int32) {
	o.HardBounceCount = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *TransactionalEmail) GetPrice() string {
	if o == nil || IsNil(o.Price) {
		var ret string
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetPriceOk() (*string, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *TransactionalEmail) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given string and assigns it to the Price field.
func (o *TransactionalEmail) SetPrice(v string) {
	o.Price = &v
}

// GetDateAdded returns the DateAdded field value if set, zero value otherwise.
func (o *TransactionalEmail) GetDateAdded() int32 {
	if o == nil || IsNil(o.DateAdded) {
		var ret int32
		return ret
	}
	return *o.DateAdded
}

// GetDateAddedOk returns a tuple with the DateAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetDateAddedOk() (*int32, bool) {
	if o == nil || IsNil(o.DateAdded) {
		return nil, false
	}
	return o.DateAdded, true
}

// HasDateAdded returns a boolean if a field has been set.
func (o *TransactionalEmail) HasDateAdded() bool {
	if o != nil && !IsNil(o.DateAdded) {
		return true
	}

	return false
}

// SetDateAdded gets a reference to the given int32 and assigns it to the DateAdded field.
func (o *TransactionalEmail) SetDateAdded(v int32) {
	o.DateAdded = &v
}

// GetCustomString returns the CustomString field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TransactionalEmail) GetCustomString() string {
	if o == nil || IsNil(o.CustomString.Get()) {
		var ret string
		return ret
	}
	return *o.CustomString.Get()
}

// GetCustomStringOk returns a tuple with the CustomString field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransactionalEmail) GetCustomStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomString.Get(), o.CustomString.IsSet()
}

// HasCustomString returns a boolean if a field has been set.
func (o *TransactionalEmail) HasCustomString() bool {
	if o != nil && o.CustomString.IsSet() {
		return true
	}

	return false
}

// SetCustomString gets a reference to the given NullableString and assigns it to the CustomString field.
func (o *TransactionalEmail) SetCustomString(v string) {
	o.CustomString.Set(&v)
}
// SetCustomStringNil sets the value for CustomString to be an explicit nil
func (o *TransactionalEmail) SetCustomStringNil() {
	o.CustomString.Set(nil)
}

// UnsetCustomString ensures that no value is present for CustomString, not even an explicit nil
func (o *TransactionalEmail) UnsetCustomString() {
	o.CustomString.Unset()
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *TransactionalEmail) GetAttachments() []Attachment {
	if o == nil || IsNil(o.Attachments) {
		var ret []Attachment
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetAttachmentsOk() ([]Attachment, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *TransactionalEmail) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []Attachment and assigns it to the Attachments field.
func (o *TransactionalEmail) SetAttachments(v []Attachment) {
	o.Attachments = v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *TransactionalEmail) GetCurrency() Currency {
	if o == nil || IsNil(o.Currency) {
		var ret Currency
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalEmail) GetCurrencyOk() (*Currency, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *TransactionalEmail) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given Currency and assigns it to the Currency field.
func (o *TransactionalEmail) SetCurrency(v Currency) {
	o.Currency = &v
}

func (o TransactionalEmail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionalEmail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.SubaccountId) {
		toSerialize["subaccount_id"] = o.SubaccountId
	}
	if !IsNil(o.FromEmailAddressId) {
		toSerialize["from_email_address_id"] = o.FromEmailAddressId
	}
	if !IsNil(o.FromName) {
		toSerialize["from_name"] = o.FromName
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.Cc) {
		toSerialize["cc"] = o.Cc
	}
	if !IsNil(o.Bcc) {
		toSerialize["bcc"] = o.Bcc
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.BodyPlainText) {
		toSerialize["body_plain_text"] = o.BodyPlainText
	}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	if !IsNil(o.MessageId) {
		toSerialize["message_id"] = o.MessageId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusText) {
		toSerialize["status_text"] = o.StatusText
	}
	if !IsNil(o.SoftBounceCount) {
		toSerialize["soft_bounce_count"] = o.SoftBounceCount
	}
	if !IsNil(o.HardBounceCount) {
		toSerialize["hard_bounce_count"] = o.HardBounceCount
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.DateAdded) {
		toSerialize["date_added"] = o.DateAdded
	}
	if o.CustomString.IsSet() {
		toSerialize["custom_string"] = o.CustomString.Get()
	}
	if !IsNil(o.Attachments) {
		toSerialize["_attachments"] = o.Attachments
	}
	if !IsNil(o.Currency) {
		toSerialize["_currency"] = o.Currency
	}
	return toSerialize, nil
}

type NullableTransactionalEmail struct {
	value *TransactionalEmail
	isSet bool
}

func (v NullableTransactionalEmail) Get() *TransactionalEmail {
	return v.value
}

func (v *NullableTransactionalEmail) Set(val *TransactionalEmail) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionalEmail) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionalEmail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionalEmail(val *TransactionalEmail) *NullableTransactionalEmail {
	return &NullableTransactionalEmail{value: val, isSet: true}
}

func (v NullableTransactionalEmail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionalEmail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


