/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the CalculateSmsPriceData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalculateSmsPriceData{}

// CalculateSmsPriceData The parameters related to the messages price.
type CalculateSmsPriceData struct {
	// The total price of sending the messages. Visit [this page](/#status-codes) for more information.
	TotalPrice *float32 `json:"total_price,omitempty"`
	// The total number of messages sent from the request.
	TotalCount *int32 `json:"total_count,omitempty"`
	// The messages will be put in a queue if it goes through the validation process. The validation process checks whether the **Sender ID** is registered or not. Some countries don't require messages to go through the validation process.  Messages scheduled to be sent right away will be sent immediately. If not, it will be queued.
	QueuedCount *int32 `json:"queued_count,omitempty"`
	// The parameters related to messages.
	Messages []Sms `json:"messages,omitempty"`
	Currency *Currency `json:"_currency,omitempty"`
	Summary *CalculateSmsPriceDataSummary `json:"_summary,omitempty"`
	// The number of messages unable to be sent. This is often caused by:  - Receipient’s country not enabled for global sending.      - Sender ID resitriction.      - Number registration restrcition.
	BlockedCount *int32 `json:"blocked_count,omitempty"`
}

// NewCalculateSmsPriceData instantiates a new CalculateSmsPriceData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalculateSmsPriceData() *CalculateSmsPriceData {
	this := CalculateSmsPriceData{}
	return &this
}

// NewCalculateSmsPriceDataWithDefaults instantiates a new CalculateSmsPriceData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalculateSmsPriceDataWithDefaults() *CalculateSmsPriceData {
	this := CalculateSmsPriceData{}
	return &this
}

// GetTotalPrice returns the TotalPrice field value if set, zero value otherwise.
func (o *CalculateSmsPriceData) GetTotalPrice() float32 {
	if o == nil || IsNil(o.TotalPrice) {
		var ret float32
		return ret
	}
	return *o.TotalPrice
}

// GetTotalPriceOk returns a tuple with the TotalPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceData) GetTotalPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalPrice) {
		return nil, false
	}
	return o.TotalPrice, true
}

// HasTotalPrice returns a boolean if a field has been set.
func (o *CalculateSmsPriceData) HasTotalPrice() bool {
	if o != nil && !IsNil(o.TotalPrice) {
		return true
	}

	return false
}

// SetTotalPrice gets a reference to the given float32 and assigns it to the TotalPrice field.
func (o *CalculateSmsPriceData) SetTotalPrice(v float32) {
	o.TotalPrice = &v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *CalculateSmsPriceData) GetTotalCount() int32 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceData) GetTotalCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *CalculateSmsPriceData) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *CalculateSmsPriceData) SetTotalCount(v int32) {
	o.TotalCount = &v
}

// GetQueuedCount returns the QueuedCount field value if set, zero value otherwise.
func (o *CalculateSmsPriceData) GetQueuedCount() int32 {
	if o == nil || IsNil(o.QueuedCount) {
		var ret int32
		return ret
	}
	return *o.QueuedCount
}

// GetQueuedCountOk returns a tuple with the QueuedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceData) GetQueuedCountOk() (*int32, bool) {
	if o == nil || IsNil(o.QueuedCount) {
		return nil, false
	}
	return o.QueuedCount, true
}

// HasQueuedCount returns a boolean if a field has been set.
func (o *CalculateSmsPriceData) HasQueuedCount() bool {
	if o != nil && !IsNil(o.QueuedCount) {
		return true
	}

	return false
}

// SetQueuedCount gets a reference to the given int32 and assigns it to the QueuedCount field.
func (o *CalculateSmsPriceData) SetQueuedCount(v int32) {
	o.QueuedCount = &v
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *CalculateSmsPriceData) GetMessages() []Sms {
	if o == nil || IsNil(o.Messages) {
		var ret []Sms
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceData) GetMessagesOk() ([]Sms, bool) {
	if o == nil || IsNil(o.Messages) {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *CalculateSmsPriceData) HasMessages() bool {
	if o != nil && !IsNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []Sms and assigns it to the Messages field.
func (o *CalculateSmsPriceData) SetMessages(v []Sms) {
	o.Messages = v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *CalculateSmsPriceData) GetCurrency() Currency {
	if o == nil || IsNil(o.Currency) {
		var ret Currency
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceData) GetCurrencyOk() (*Currency, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *CalculateSmsPriceData) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given Currency and assigns it to the Currency field.
func (o *CalculateSmsPriceData) SetCurrency(v Currency) {
	o.Currency = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *CalculateSmsPriceData) GetSummary() CalculateSmsPriceDataSummary {
	if o == nil || IsNil(o.Summary) {
		var ret CalculateSmsPriceDataSummary
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceData) GetSummaryOk() (*CalculateSmsPriceDataSummary, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *CalculateSmsPriceData) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given CalculateSmsPriceDataSummary and assigns it to the Summary field.
func (o *CalculateSmsPriceData) SetSummary(v CalculateSmsPriceDataSummary) {
	o.Summary = &v
}

// GetBlockedCount returns the BlockedCount field value if set, zero value otherwise.
func (o *CalculateSmsPriceData) GetBlockedCount() int32 {
	if o == nil || IsNil(o.BlockedCount) {
		var ret int32
		return ret
	}
	return *o.BlockedCount
}

// GetBlockedCountOk returns a tuple with the BlockedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateSmsPriceData) GetBlockedCountOk() (*int32, bool) {
	if o == nil || IsNil(o.BlockedCount) {
		return nil, false
	}
	return o.BlockedCount, true
}

// HasBlockedCount returns a boolean if a field has been set.
func (o *CalculateSmsPriceData) HasBlockedCount() bool {
	if o != nil && !IsNil(o.BlockedCount) {
		return true
	}

	return false
}

// SetBlockedCount gets a reference to the given int32 and assigns it to the BlockedCount field.
func (o *CalculateSmsPriceData) SetBlockedCount(v int32) {
	o.BlockedCount = &v
}

func (o CalculateSmsPriceData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalculateSmsPriceData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalPrice) {
		toSerialize["total_price"] = o.TotalPrice
	}
	if !IsNil(o.TotalCount) {
		toSerialize["total_count"] = o.TotalCount
	}
	if !IsNil(o.QueuedCount) {
		toSerialize["queued_count"] = o.QueuedCount
	}
	if !IsNil(o.Messages) {
		toSerialize["messages"] = o.Messages
	}
	if !IsNil(o.Currency) {
		toSerialize["_currency"] = o.Currency
	}
	if !IsNil(o.Summary) {
		toSerialize["_summary"] = o.Summary
	}
	if !IsNil(o.BlockedCount) {
		toSerialize["blocked_count"] = o.BlockedCount
	}
	return toSerialize, nil
}

type NullableCalculateSmsPriceData struct {
	value *CalculateSmsPriceData
	isSet bool
}

func (v NullableCalculateSmsPriceData) Get() *CalculateSmsPriceData {
	return v.value
}

func (v *NullableCalculateSmsPriceData) Set(val *CalculateSmsPriceData) {
	v.value = val
	v.isSet = true
}

func (v NullableCalculateSmsPriceData) IsSet() bool {
	return v.isSet
}

func (v *NullableCalculateSmsPriceData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalculateSmsPriceData(val *CalculateSmsPriceData) *NullableCalculateSmsPriceData {
	return &NullableCalculateSmsPriceData{value: val, isSet: true}
}

func (v NullableCalculateSmsPriceData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalculateSmsPriceData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


