/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DefaultSenderDefaultSenderStrategiesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultSenderDefaultSenderStrategiesInner{}

// DefaultSenderDefaultSenderStrategiesInner struct for DefaultSenderDefaultSenderStrategiesInner
type DefaultSenderDefaultSenderStrategiesInner struct {
	// Type of the sender.
	SenderType string `json:"sender_type"`
	// Identifier for the sender. Must be between 3-20 characters.
	SenderId string `json:"sender_id"`
	// ISO 3166-1 alpha-2 formatted country code.
	SenderCountryCode *string `json:"sender_country_code,omitempty"`
	// Priority level of the sender in the strategy. Must be a positive integer.
	Priority int32 `json:"priority"`
	// Status of the sender in the strategy.
	Status string `json:"status"`
	// Note providing additional context about the sender. Maximum length of 200 characters. Optional.
	Note *string `json:"note,omitempty"`
}

type _DefaultSenderDefaultSenderStrategiesInner DefaultSenderDefaultSenderStrategiesInner

// NewDefaultSenderDefaultSenderStrategiesInner instantiates a new DefaultSenderDefaultSenderStrategiesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultSenderDefaultSenderStrategiesInner(senderType string, senderId string, priority int32, status string) *DefaultSenderDefaultSenderStrategiesInner {
	this := DefaultSenderDefaultSenderStrategiesInner{}
	this.SenderType = senderType
	this.SenderId = senderId
	this.Priority = priority
	this.Status = status
	return &this
}

// NewDefaultSenderDefaultSenderStrategiesInnerWithDefaults instantiates a new DefaultSenderDefaultSenderStrategiesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultSenderDefaultSenderStrategiesInnerWithDefaults() *DefaultSenderDefaultSenderStrategiesInner {
	this := DefaultSenderDefaultSenderStrategiesInner{}
	return &this
}

// GetSenderType returns the SenderType field value
func (o *DefaultSenderDefaultSenderStrategiesInner) GetSenderType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SenderType
}

// GetSenderTypeOk returns a tuple with the SenderType field value
// and a boolean to check if the value has been set.
func (o *DefaultSenderDefaultSenderStrategiesInner) GetSenderTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SenderType, true
}

// SetSenderType sets field value
func (o *DefaultSenderDefaultSenderStrategiesInner) SetSenderType(v string) {
	o.SenderType = v
}

// GetSenderId returns the SenderId field value
func (o *DefaultSenderDefaultSenderStrategiesInner) GetSenderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SenderId
}

// GetSenderIdOk returns a tuple with the SenderId field value
// and a boolean to check if the value has been set.
func (o *DefaultSenderDefaultSenderStrategiesInner) GetSenderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SenderId, true
}

// SetSenderId sets field value
func (o *DefaultSenderDefaultSenderStrategiesInner) SetSenderId(v string) {
	o.SenderId = v
}

// GetSenderCountryCode returns the SenderCountryCode field value if set, zero value otherwise.
func (o *DefaultSenderDefaultSenderStrategiesInner) GetSenderCountryCode() string {
	if o == nil || IsNil(o.SenderCountryCode) {
		var ret string
		return ret
	}
	return *o.SenderCountryCode
}

// GetSenderCountryCodeOk returns a tuple with the SenderCountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultSenderDefaultSenderStrategiesInner) GetSenderCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.SenderCountryCode) {
		return nil, false
	}
	return o.SenderCountryCode, true
}

// HasSenderCountryCode returns a boolean if a field has been set.
func (o *DefaultSenderDefaultSenderStrategiesInner) HasSenderCountryCode() bool {
	if o != nil && !IsNil(o.SenderCountryCode) {
		return true
	}

	return false
}

// SetSenderCountryCode gets a reference to the given string and assigns it to the SenderCountryCode field.
func (o *DefaultSenderDefaultSenderStrategiesInner) SetSenderCountryCode(v string) {
	o.SenderCountryCode = &v
}

// GetPriority returns the Priority field value
func (o *DefaultSenderDefaultSenderStrategiesInner) GetPriority() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *DefaultSenderDefaultSenderStrategiesInner) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *DefaultSenderDefaultSenderStrategiesInner) SetPriority(v int32) {
	o.Priority = v
}

// GetStatus returns the Status field value
func (o *DefaultSenderDefaultSenderStrategiesInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DefaultSenderDefaultSenderStrategiesInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DefaultSenderDefaultSenderStrategiesInner) SetStatus(v string) {
	o.Status = v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *DefaultSenderDefaultSenderStrategiesInner) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultSenderDefaultSenderStrategiesInner) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *DefaultSenderDefaultSenderStrategiesInner) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *DefaultSenderDefaultSenderStrategiesInner) SetNote(v string) {
	o.Note = &v
}

func (o DefaultSenderDefaultSenderStrategiesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultSenderDefaultSenderStrategiesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sender_type"] = o.SenderType
	toSerialize["sender_id"] = o.SenderId
	if !IsNil(o.SenderCountryCode) {
		toSerialize["sender_country_code"] = o.SenderCountryCode
	}
	toSerialize["priority"] = o.Priority
	toSerialize["status"] = o.Status
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	return toSerialize, nil
}

func (o *DefaultSenderDefaultSenderStrategiesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sender_type",
		"sender_id",
		"priority",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefaultSenderDefaultSenderStrategiesInner := _DefaultSenderDefaultSenderStrategiesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefaultSenderDefaultSenderStrategiesInner)

	if err != nil {
		return err
	}

	*o = DefaultSenderDefaultSenderStrategiesInner(varDefaultSenderDefaultSenderStrategiesInner)

	return err
}

type NullableDefaultSenderDefaultSenderStrategiesInner struct {
	value *DefaultSenderDefaultSenderStrategiesInner
	isSet bool
}

func (v NullableDefaultSenderDefaultSenderStrategiesInner) Get() *DefaultSenderDefaultSenderStrategiesInner {
	return v.value
}

func (v *NullableDefaultSenderDefaultSenderStrategiesInner) Set(val *DefaultSenderDefaultSenderStrategiesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultSenderDefaultSenderStrategiesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultSenderDefaultSenderStrategiesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultSenderDefaultSenderStrategiesInner(val *DefaultSenderDefaultSenderStrategiesInner) *NullableDefaultSenderDefaultSenderStrategiesInner {
	return &NullableDefaultSenderDefaultSenderStrategiesInner{value: val, isSet: true}
}

func (v NullableDefaultSenderDefaultSenderStrategiesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultSenderDefaultSenderStrategiesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


