/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListCompliantSenderTypes200ResponseDataDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCompliantSenderTypes200ResponseDataDataInner{}

// ListCompliantSenderTypes200ResponseDataDataInner struct for ListCompliantSenderTypes200ResponseDataDataInner
type ListCompliantSenderTypes200ResponseDataDataInner struct {
	// ISO 3166-1 alpha-2 formatted country code
	RecipientCountryCode string `json:"recipient_country_code" validate:"regexp=^[A-Z]{2}$"`
	// List of blocked sender types in recipient country
	BlockedSenderTypes []string `json:"blocked_sender_types"`
	AllowedSenderTypes []ListCompliantSenderTypes200ResponseDataDataInnerAllowedSenderTypesInner `json:"allowed_sender_types"`
}

type _ListCompliantSenderTypes200ResponseDataDataInner ListCompliantSenderTypes200ResponseDataDataInner

// NewListCompliantSenderTypes200ResponseDataDataInner instantiates a new ListCompliantSenderTypes200ResponseDataDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCompliantSenderTypes200ResponseDataDataInner(recipientCountryCode string, blockedSenderTypes []string, allowedSenderTypes []ListCompliantSenderTypes200ResponseDataDataInnerAllowedSenderTypesInner) *ListCompliantSenderTypes200ResponseDataDataInner {
	this := ListCompliantSenderTypes200ResponseDataDataInner{}
	this.RecipientCountryCode = recipientCountryCode
	this.BlockedSenderTypes = blockedSenderTypes
	this.AllowedSenderTypes = allowedSenderTypes
	return &this
}

// NewListCompliantSenderTypes200ResponseDataDataInnerWithDefaults instantiates a new ListCompliantSenderTypes200ResponseDataDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCompliantSenderTypes200ResponseDataDataInnerWithDefaults() *ListCompliantSenderTypes200ResponseDataDataInner {
	this := ListCompliantSenderTypes200ResponseDataDataInner{}
	return &this
}

// GetRecipientCountryCode returns the RecipientCountryCode field value
func (o *ListCompliantSenderTypes200ResponseDataDataInner) GetRecipientCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecipientCountryCode
}

// GetRecipientCountryCodeOk returns a tuple with the RecipientCountryCode field value
// and a boolean to check if the value has been set.
func (o *ListCompliantSenderTypes200ResponseDataDataInner) GetRecipientCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecipientCountryCode, true
}

// SetRecipientCountryCode sets field value
func (o *ListCompliantSenderTypes200ResponseDataDataInner) SetRecipientCountryCode(v string) {
	o.RecipientCountryCode = v
}

// GetBlockedSenderTypes returns the BlockedSenderTypes field value
func (o *ListCompliantSenderTypes200ResponseDataDataInner) GetBlockedSenderTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.BlockedSenderTypes
}

// GetBlockedSenderTypesOk returns a tuple with the BlockedSenderTypes field value
// and a boolean to check if the value has been set.
func (o *ListCompliantSenderTypes200ResponseDataDataInner) GetBlockedSenderTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BlockedSenderTypes, true
}

// SetBlockedSenderTypes sets field value
func (o *ListCompliantSenderTypes200ResponseDataDataInner) SetBlockedSenderTypes(v []string) {
	o.BlockedSenderTypes = v
}

// GetAllowedSenderTypes returns the AllowedSenderTypes field value
func (o *ListCompliantSenderTypes200ResponseDataDataInner) GetAllowedSenderTypes() []ListCompliantSenderTypes200ResponseDataDataInnerAllowedSenderTypesInner {
	if o == nil {
		var ret []ListCompliantSenderTypes200ResponseDataDataInnerAllowedSenderTypesInner
		return ret
	}

	return o.AllowedSenderTypes
}

// GetAllowedSenderTypesOk returns a tuple with the AllowedSenderTypes field value
// and a boolean to check if the value has been set.
func (o *ListCompliantSenderTypes200ResponseDataDataInner) GetAllowedSenderTypesOk() ([]ListCompliantSenderTypes200ResponseDataDataInnerAllowedSenderTypesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.AllowedSenderTypes, true
}

// SetAllowedSenderTypes sets field value
func (o *ListCompliantSenderTypes200ResponseDataDataInner) SetAllowedSenderTypes(v []ListCompliantSenderTypes200ResponseDataDataInnerAllowedSenderTypesInner) {
	o.AllowedSenderTypes = v
}

func (o ListCompliantSenderTypes200ResponseDataDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCompliantSenderTypes200ResponseDataDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["recipient_country_code"] = o.RecipientCountryCode
	toSerialize["blocked_sender_types"] = o.BlockedSenderTypes
	toSerialize["allowed_sender_types"] = o.AllowedSenderTypes
	return toSerialize, nil
}

func (o *ListCompliantSenderTypes200ResponseDataDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"recipient_country_code",
		"blocked_sender_types",
		"allowed_sender_types",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListCompliantSenderTypes200ResponseDataDataInner := _ListCompliantSenderTypes200ResponseDataDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListCompliantSenderTypes200ResponseDataDataInner)

	if err != nil {
		return err
	}

	*o = ListCompliantSenderTypes200ResponseDataDataInner(varListCompliantSenderTypes200ResponseDataDataInner)

	return err
}

type NullableListCompliantSenderTypes200ResponseDataDataInner struct {
	value *ListCompliantSenderTypes200ResponseDataDataInner
	isSet bool
}

func (v NullableListCompliantSenderTypes200ResponseDataDataInner) Get() *ListCompliantSenderTypes200ResponseDataDataInner {
	return v.value
}

func (v *NullableListCompliantSenderTypes200ResponseDataDataInner) Set(val *ListCompliantSenderTypes200ResponseDataDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListCompliantSenderTypes200ResponseDataDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListCompliantSenderTypes200ResponseDataDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCompliantSenderTypes200ResponseDataDataInner(val *ListCompliantSenderTypes200ResponseDataDataInner) *NullableListCompliantSenderTypes200ResponseDataDataInner {
	return &NullableListCompliantSenderTypes200ResponseDataDataInner{value: val, isSet: true}
}

func (v NullableListCompliantSenderTypes200ResponseDataDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCompliantSenderTypes200ResponseDataDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


