/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the ViewRechargePackagesDataPackagesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewRechargePackagesDataPackagesInner{}

// ViewRechargePackagesDataPackagesInner struct for ViewRechargePackagesDataPackagesInner
type ViewRechargePackagesDataPackagesInner struct {
	// The ID of the package.
	PackageId *float32 `json:"package_id,omitempty"`
	// The price of the package.
	PackagePrice *string `json:"package_price,omitempty"`
	// The pricing tier used to determine the cost per message.
	PriceRate *int32 `json:"price_rate,omitempty"`
	// The price of the SMS.
	SmsPrice *float32 `json:"sms_price,omitempty"`
	// The quantity of the SMS.
	SmsQuantity *float32 `json:"sms_quantity,omitempty"`
	// The price of the voice mobile.
	VoiceMobilePrice *float32 `json:"voice_mobile_price,omitempty"`
	// The quantity of the voice mobile.
	VoiceMobileQuantity *float32 `json:"voice_mobile_quantity,omitempty"`
	// The price of the voice landline.
	VoiceLandlinePrice *float32 `json:"voice_landline_price,omitempty"`
	// The quantity of the voice landline.
	VoiceLandlineQuantity *float32 `json:"voice_landline_quantity,omitempty"`
	// The price of the fax.
	FaxPrice *float32 `json:"fax_price,omitempty"`
	// The quantity of the fax.
	FaxQuantity *float32 `json:"fax_quantity,omitempty"`
	// The price of the email.
	EmailPrice *float32 `json:"email_price,omitempty"`
	// The quantity of the email.
	EmailQuantity *float32 `json:"email_quantity,omitempty"`
	// The price of the post letter black.
	PostLetterBlackPrice *float32 `json:"post_letter_black_price,omitempty"`
	// The price of the post letter colour.
	PostLetterColourPrice *float32 `json:"post_letter_colour_price,omitempty"`
	// The price of the post page black.
	PostPageBlackPrice *float32 `json:"post_page_black_price,omitempty"`
	// The price of the post page colour.
	PostPageColourPrice *float32 `json:"post_page_colour_price,omitempty"`
	// The quantity of the post letter black.
	PostLetterBlackQuantity *float32 `json:"post_letter_black_quantity,omitempty"`
	// The quantity of the post letter colour.
	PostLetterColourQuantity *float32 `json:"post_letter_colour_quantity,omitempty"`
	// The price of the post direct mail dl.
	PostDirectMailDlPrice *float32 `json:"post_direct_mail_dl_price,omitempty"`
	// The price of the post direct mail a5.
	PostDirectMailA5Price *float32 `json:"post_direct_mail_a5_price,omitempty"`
	// The quantity of the post direct mail min.
	PostDirectMailMinQuantity *float32 `json:"post_direct_mail_min_quantity,omitempty"`
	// The price of the postcard.
	PostcardPrice *float32 `json:"postcard_price,omitempty"`
	// The quantity of the postcard.
	PostcardQuantity *float32 `json:"postcard_quantity,omitempty"`
	// The price of the automation.
	AutomationPrice *float32 `json:"automation_price,omitempty"`
}

// NewViewRechargePackagesDataPackagesInner instantiates a new ViewRechargePackagesDataPackagesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewRechargePackagesDataPackagesInner() *ViewRechargePackagesDataPackagesInner {
	this := ViewRechargePackagesDataPackagesInner{}
	return &this
}

// NewViewRechargePackagesDataPackagesInnerWithDefaults instantiates a new ViewRechargePackagesDataPackagesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewRechargePackagesDataPackagesInnerWithDefaults() *ViewRechargePackagesDataPackagesInner {
	this := ViewRechargePackagesDataPackagesInner{}
	return &this
}

// GetPackageId returns the PackageId field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetPackageId() float32 {
	if o == nil || IsNil(o.PackageId) {
		var ret float32
		return ret
	}
	return *o.PackageId
}

// GetPackageIdOk returns a tuple with the PackageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetPackageIdOk() (*float32, bool) {
	if o == nil || IsNil(o.PackageId) {
		return nil, false
	}
	return o.PackageId, true
}

// HasPackageId returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasPackageId() bool {
	if o != nil && !IsNil(o.PackageId) {
		return true
	}

	return false
}

// SetPackageId gets a reference to the given float32 and assigns it to the PackageId field.
func (o *ViewRechargePackagesDataPackagesInner) SetPackageId(v float32) {
	o.PackageId = &v
}

// GetPackagePrice returns the PackagePrice field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetPackagePrice() string {
	if o == nil || IsNil(o.PackagePrice) {
		var ret string
		return ret
	}
	return *o.PackagePrice
}

// GetPackagePriceOk returns a tuple with the PackagePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetPackagePriceOk() (*string, bool) {
	if o == nil || IsNil(o.PackagePrice) {
		return nil, false
	}
	return o.PackagePrice, true
}

// HasPackagePrice returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasPackagePrice() bool {
	if o != nil && !IsNil(o.PackagePrice) {
		return true
	}

	return false
}

// SetPackagePrice gets a reference to the given string and assigns it to the PackagePrice field.
func (o *ViewRechargePackagesDataPackagesInner) SetPackagePrice(v string) {
	o.PackagePrice = &v
}

// GetPriceRate returns the PriceRate field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetPriceRate() int32 {
	if o == nil || IsNil(o.PriceRate) {
		var ret int32
		return ret
	}
	return *o.PriceRate
}

// GetPriceRateOk returns a tuple with the PriceRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetPriceRateOk() (*int32, bool) {
	if o == nil || IsNil(o.PriceRate) {
		return nil, false
	}
	return o.PriceRate, true
}

// HasPriceRate returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasPriceRate() bool {
	if o != nil && !IsNil(o.PriceRate) {
		return true
	}

	return false
}

// SetPriceRate gets a reference to the given int32 and assigns it to the PriceRate field.
func (o *ViewRechargePackagesDataPackagesInner) SetPriceRate(v int32) {
	o.PriceRate = &v
}

// GetSmsPrice returns the SmsPrice field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetSmsPrice() float32 {
	if o == nil || IsNil(o.SmsPrice) {
		var ret float32
		return ret
	}
	return *o.SmsPrice
}

// GetSmsPriceOk returns a tuple with the SmsPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetSmsPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.SmsPrice) {
		return nil, false
	}
	return o.SmsPrice, true
}

// HasSmsPrice returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasSmsPrice() bool {
	if o != nil && !IsNil(o.SmsPrice) {
		return true
	}

	return false
}

// SetSmsPrice gets a reference to the given float32 and assigns it to the SmsPrice field.
func (o *ViewRechargePackagesDataPackagesInner) SetSmsPrice(v float32) {
	o.SmsPrice = &v
}

// GetSmsQuantity returns the SmsQuantity field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetSmsQuantity() float32 {
	if o == nil || IsNil(o.SmsQuantity) {
		var ret float32
		return ret
	}
	return *o.SmsQuantity
}

// GetSmsQuantityOk returns a tuple with the SmsQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetSmsQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.SmsQuantity) {
		return nil, false
	}
	return o.SmsQuantity, true
}

// HasSmsQuantity returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasSmsQuantity() bool {
	if o != nil && !IsNil(o.SmsQuantity) {
		return true
	}

	return false
}

// SetSmsQuantity gets a reference to the given float32 and assigns it to the SmsQuantity field.
func (o *ViewRechargePackagesDataPackagesInner) SetSmsQuantity(v float32) {
	o.SmsQuantity = &v
}

// GetVoiceMobilePrice returns the VoiceMobilePrice field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetVoiceMobilePrice() float32 {
	if o == nil || IsNil(o.VoiceMobilePrice) {
		var ret float32
		return ret
	}
	return *o.VoiceMobilePrice
}

// GetVoiceMobilePriceOk returns a tuple with the VoiceMobilePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetVoiceMobilePriceOk() (*float32, bool) {
	if o == nil || IsNil(o.VoiceMobilePrice) {
		return nil, false
	}
	return o.VoiceMobilePrice, true
}

// HasVoiceMobilePrice returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasVoiceMobilePrice() bool {
	if o != nil && !IsNil(o.VoiceMobilePrice) {
		return true
	}

	return false
}

// SetVoiceMobilePrice gets a reference to the given float32 and assigns it to the VoiceMobilePrice field.
func (o *ViewRechargePackagesDataPackagesInner) SetVoiceMobilePrice(v float32) {
	o.VoiceMobilePrice = &v
}

// GetVoiceMobileQuantity returns the VoiceMobileQuantity field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetVoiceMobileQuantity() float32 {
	if o == nil || IsNil(o.VoiceMobileQuantity) {
		var ret float32
		return ret
	}
	return *o.VoiceMobileQuantity
}

// GetVoiceMobileQuantityOk returns a tuple with the VoiceMobileQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetVoiceMobileQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.VoiceMobileQuantity) {
		return nil, false
	}
	return o.VoiceMobileQuantity, true
}

// HasVoiceMobileQuantity returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasVoiceMobileQuantity() bool {
	if o != nil && !IsNil(o.VoiceMobileQuantity) {
		return true
	}

	return false
}

// SetVoiceMobileQuantity gets a reference to the given float32 and assigns it to the VoiceMobileQuantity field.
func (o *ViewRechargePackagesDataPackagesInner) SetVoiceMobileQuantity(v float32) {
	o.VoiceMobileQuantity = &v
}

// GetVoiceLandlinePrice returns the VoiceLandlinePrice field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetVoiceLandlinePrice() float32 {
	if o == nil || IsNil(o.VoiceLandlinePrice) {
		var ret float32
		return ret
	}
	return *o.VoiceLandlinePrice
}

// GetVoiceLandlinePriceOk returns a tuple with the VoiceLandlinePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetVoiceLandlinePriceOk() (*float32, bool) {
	if o == nil || IsNil(o.VoiceLandlinePrice) {
		return nil, false
	}
	return o.VoiceLandlinePrice, true
}

// HasVoiceLandlinePrice returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasVoiceLandlinePrice() bool {
	if o != nil && !IsNil(o.VoiceLandlinePrice) {
		return true
	}

	return false
}

// SetVoiceLandlinePrice gets a reference to the given float32 and assigns it to the VoiceLandlinePrice field.
func (o *ViewRechargePackagesDataPackagesInner) SetVoiceLandlinePrice(v float32) {
	o.VoiceLandlinePrice = &v
}

// GetVoiceLandlineQuantity returns the VoiceLandlineQuantity field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetVoiceLandlineQuantity() float32 {
	if o == nil || IsNil(o.VoiceLandlineQuantity) {
		var ret float32
		return ret
	}
	return *o.VoiceLandlineQuantity
}

// GetVoiceLandlineQuantityOk returns a tuple with the VoiceLandlineQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetVoiceLandlineQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.VoiceLandlineQuantity) {
		return nil, false
	}
	return o.VoiceLandlineQuantity, true
}

// HasVoiceLandlineQuantity returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasVoiceLandlineQuantity() bool {
	if o != nil && !IsNil(o.VoiceLandlineQuantity) {
		return true
	}

	return false
}

// SetVoiceLandlineQuantity gets a reference to the given float32 and assigns it to the VoiceLandlineQuantity field.
func (o *ViewRechargePackagesDataPackagesInner) SetVoiceLandlineQuantity(v float32) {
	o.VoiceLandlineQuantity = &v
}

// GetFaxPrice returns the FaxPrice field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetFaxPrice() float32 {
	if o == nil || IsNil(o.FaxPrice) {
		var ret float32
		return ret
	}
	return *o.FaxPrice
}

// GetFaxPriceOk returns a tuple with the FaxPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetFaxPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.FaxPrice) {
		return nil, false
	}
	return o.FaxPrice, true
}

// HasFaxPrice returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasFaxPrice() bool {
	if o != nil && !IsNil(o.FaxPrice) {
		return true
	}

	return false
}

// SetFaxPrice gets a reference to the given float32 and assigns it to the FaxPrice field.
func (o *ViewRechargePackagesDataPackagesInner) SetFaxPrice(v float32) {
	o.FaxPrice = &v
}

// GetFaxQuantity returns the FaxQuantity field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetFaxQuantity() float32 {
	if o == nil || IsNil(o.FaxQuantity) {
		var ret float32
		return ret
	}
	return *o.FaxQuantity
}

// GetFaxQuantityOk returns a tuple with the FaxQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetFaxQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.FaxQuantity) {
		return nil, false
	}
	return o.FaxQuantity, true
}

// HasFaxQuantity returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasFaxQuantity() bool {
	if o != nil && !IsNil(o.FaxQuantity) {
		return true
	}

	return false
}

// SetFaxQuantity gets a reference to the given float32 and assigns it to the FaxQuantity field.
func (o *ViewRechargePackagesDataPackagesInner) SetFaxQuantity(v float32) {
	o.FaxQuantity = &v
}

// GetEmailPrice returns the EmailPrice field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetEmailPrice() float32 {
	if o == nil || IsNil(o.EmailPrice) {
		var ret float32
		return ret
	}
	return *o.EmailPrice
}

// GetEmailPriceOk returns a tuple with the EmailPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetEmailPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.EmailPrice) {
		return nil, false
	}
	return o.EmailPrice, true
}

// HasEmailPrice returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasEmailPrice() bool {
	if o != nil && !IsNil(o.EmailPrice) {
		return true
	}

	return false
}

// SetEmailPrice gets a reference to the given float32 and assigns it to the EmailPrice field.
func (o *ViewRechargePackagesDataPackagesInner) SetEmailPrice(v float32) {
	o.EmailPrice = &v
}

// GetEmailQuantity returns the EmailQuantity field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetEmailQuantity() float32 {
	if o == nil || IsNil(o.EmailQuantity) {
		var ret float32
		return ret
	}
	return *o.EmailQuantity
}

// GetEmailQuantityOk returns a tuple with the EmailQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetEmailQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.EmailQuantity) {
		return nil, false
	}
	return o.EmailQuantity, true
}

// HasEmailQuantity returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasEmailQuantity() bool {
	if o != nil && !IsNil(o.EmailQuantity) {
		return true
	}

	return false
}

// SetEmailQuantity gets a reference to the given float32 and assigns it to the EmailQuantity field.
func (o *ViewRechargePackagesDataPackagesInner) SetEmailQuantity(v float32) {
	o.EmailQuantity = &v
}

// GetPostLetterBlackPrice returns the PostLetterBlackPrice field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetPostLetterBlackPrice() float32 {
	if o == nil || IsNil(o.PostLetterBlackPrice) {
		var ret float32
		return ret
	}
	return *o.PostLetterBlackPrice
}

// GetPostLetterBlackPriceOk returns a tuple with the PostLetterBlackPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetPostLetterBlackPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.PostLetterBlackPrice) {
		return nil, false
	}
	return o.PostLetterBlackPrice, true
}

// HasPostLetterBlackPrice returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasPostLetterBlackPrice() bool {
	if o != nil && !IsNil(o.PostLetterBlackPrice) {
		return true
	}

	return false
}

// SetPostLetterBlackPrice gets a reference to the given float32 and assigns it to the PostLetterBlackPrice field.
func (o *ViewRechargePackagesDataPackagesInner) SetPostLetterBlackPrice(v float32) {
	o.PostLetterBlackPrice = &v
}

// GetPostLetterColourPrice returns the PostLetterColourPrice field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetPostLetterColourPrice() float32 {
	if o == nil || IsNil(o.PostLetterColourPrice) {
		var ret float32
		return ret
	}
	return *o.PostLetterColourPrice
}

// GetPostLetterColourPriceOk returns a tuple with the PostLetterColourPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetPostLetterColourPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.PostLetterColourPrice) {
		return nil, false
	}
	return o.PostLetterColourPrice, true
}

// HasPostLetterColourPrice returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasPostLetterColourPrice() bool {
	if o != nil && !IsNil(o.PostLetterColourPrice) {
		return true
	}

	return false
}

// SetPostLetterColourPrice gets a reference to the given float32 and assigns it to the PostLetterColourPrice field.
func (o *ViewRechargePackagesDataPackagesInner) SetPostLetterColourPrice(v float32) {
	o.PostLetterColourPrice = &v
}

// GetPostPageBlackPrice returns the PostPageBlackPrice field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetPostPageBlackPrice() float32 {
	if o == nil || IsNil(o.PostPageBlackPrice) {
		var ret float32
		return ret
	}
	return *o.PostPageBlackPrice
}

// GetPostPageBlackPriceOk returns a tuple with the PostPageBlackPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetPostPageBlackPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.PostPageBlackPrice) {
		return nil, false
	}
	return o.PostPageBlackPrice, true
}

// HasPostPageBlackPrice returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasPostPageBlackPrice() bool {
	if o != nil && !IsNil(o.PostPageBlackPrice) {
		return true
	}

	return false
}

// SetPostPageBlackPrice gets a reference to the given float32 and assigns it to the PostPageBlackPrice field.
func (o *ViewRechargePackagesDataPackagesInner) SetPostPageBlackPrice(v float32) {
	o.PostPageBlackPrice = &v
}

// GetPostPageColourPrice returns the PostPageColourPrice field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetPostPageColourPrice() float32 {
	if o == nil || IsNil(o.PostPageColourPrice) {
		var ret float32
		return ret
	}
	return *o.PostPageColourPrice
}

// GetPostPageColourPriceOk returns a tuple with the PostPageColourPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetPostPageColourPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.PostPageColourPrice) {
		return nil, false
	}
	return o.PostPageColourPrice, true
}

// HasPostPageColourPrice returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasPostPageColourPrice() bool {
	if o != nil && !IsNil(o.PostPageColourPrice) {
		return true
	}

	return false
}

// SetPostPageColourPrice gets a reference to the given float32 and assigns it to the PostPageColourPrice field.
func (o *ViewRechargePackagesDataPackagesInner) SetPostPageColourPrice(v float32) {
	o.PostPageColourPrice = &v
}

// GetPostLetterBlackQuantity returns the PostLetterBlackQuantity field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetPostLetterBlackQuantity() float32 {
	if o == nil || IsNil(o.PostLetterBlackQuantity) {
		var ret float32
		return ret
	}
	return *o.PostLetterBlackQuantity
}

// GetPostLetterBlackQuantityOk returns a tuple with the PostLetterBlackQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetPostLetterBlackQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.PostLetterBlackQuantity) {
		return nil, false
	}
	return o.PostLetterBlackQuantity, true
}

// HasPostLetterBlackQuantity returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasPostLetterBlackQuantity() bool {
	if o != nil && !IsNil(o.PostLetterBlackQuantity) {
		return true
	}

	return false
}

// SetPostLetterBlackQuantity gets a reference to the given float32 and assigns it to the PostLetterBlackQuantity field.
func (o *ViewRechargePackagesDataPackagesInner) SetPostLetterBlackQuantity(v float32) {
	o.PostLetterBlackQuantity = &v
}

// GetPostLetterColourQuantity returns the PostLetterColourQuantity field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetPostLetterColourQuantity() float32 {
	if o == nil || IsNil(o.PostLetterColourQuantity) {
		var ret float32
		return ret
	}
	return *o.PostLetterColourQuantity
}

// GetPostLetterColourQuantityOk returns a tuple with the PostLetterColourQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetPostLetterColourQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.PostLetterColourQuantity) {
		return nil, false
	}
	return o.PostLetterColourQuantity, true
}

// HasPostLetterColourQuantity returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasPostLetterColourQuantity() bool {
	if o != nil && !IsNil(o.PostLetterColourQuantity) {
		return true
	}

	return false
}

// SetPostLetterColourQuantity gets a reference to the given float32 and assigns it to the PostLetterColourQuantity field.
func (o *ViewRechargePackagesDataPackagesInner) SetPostLetterColourQuantity(v float32) {
	o.PostLetterColourQuantity = &v
}

// GetPostDirectMailDlPrice returns the PostDirectMailDlPrice field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetPostDirectMailDlPrice() float32 {
	if o == nil || IsNil(o.PostDirectMailDlPrice) {
		var ret float32
		return ret
	}
	return *o.PostDirectMailDlPrice
}

// GetPostDirectMailDlPriceOk returns a tuple with the PostDirectMailDlPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetPostDirectMailDlPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.PostDirectMailDlPrice) {
		return nil, false
	}
	return o.PostDirectMailDlPrice, true
}

// HasPostDirectMailDlPrice returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasPostDirectMailDlPrice() bool {
	if o != nil && !IsNil(o.PostDirectMailDlPrice) {
		return true
	}

	return false
}

// SetPostDirectMailDlPrice gets a reference to the given float32 and assigns it to the PostDirectMailDlPrice field.
func (o *ViewRechargePackagesDataPackagesInner) SetPostDirectMailDlPrice(v float32) {
	o.PostDirectMailDlPrice = &v
}

// GetPostDirectMailA5Price returns the PostDirectMailA5Price field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetPostDirectMailA5Price() float32 {
	if o == nil || IsNil(o.PostDirectMailA5Price) {
		var ret float32
		return ret
	}
	return *o.PostDirectMailA5Price
}

// GetPostDirectMailA5PriceOk returns a tuple with the PostDirectMailA5Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetPostDirectMailA5PriceOk() (*float32, bool) {
	if o == nil || IsNil(o.PostDirectMailA5Price) {
		return nil, false
	}
	return o.PostDirectMailA5Price, true
}

// HasPostDirectMailA5Price returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasPostDirectMailA5Price() bool {
	if o != nil && !IsNil(o.PostDirectMailA5Price) {
		return true
	}

	return false
}

// SetPostDirectMailA5Price gets a reference to the given float32 and assigns it to the PostDirectMailA5Price field.
func (o *ViewRechargePackagesDataPackagesInner) SetPostDirectMailA5Price(v float32) {
	o.PostDirectMailA5Price = &v
}

// GetPostDirectMailMinQuantity returns the PostDirectMailMinQuantity field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetPostDirectMailMinQuantity() float32 {
	if o == nil || IsNil(o.PostDirectMailMinQuantity) {
		var ret float32
		return ret
	}
	return *o.PostDirectMailMinQuantity
}

// GetPostDirectMailMinQuantityOk returns a tuple with the PostDirectMailMinQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetPostDirectMailMinQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.PostDirectMailMinQuantity) {
		return nil, false
	}
	return o.PostDirectMailMinQuantity, true
}

// HasPostDirectMailMinQuantity returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasPostDirectMailMinQuantity() bool {
	if o != nil && !IsNil(o.PostDirectMailMinQuantity) {
		return true
	}

	return false
}

// SetPostDirectMailMinQuantity gets a reference to the given float32 and assigns it to the PostDirectMailMinQuantity field.
func (o *ViewRechargePackagesDataPackagesInner) SetPostDirectMailMinQuantity(v float32) {
	o.PostDirectMailMinQuantity = &v
}

// GetPostcardPrice returns the PostcardPrice field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetPostcardPrice() float32 {
	if o == nil || IsNil(o.PostcardPrice) {
		var ret float32
		return ret
	}
	return *o.PostcardPrice
}

// GetPostcardPriceOk returns a tuple with the PostcardPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetPostcardPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.PostcardPrice) {
		return nil, false
	}
	return o.PostcardPrice, true
}

// HasPostcardPrice returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasPostcardPrice() bool {
	if o != nil && !IsNil(o.PostcardPrice) {
		return true
	}

	return false
}

// SetPostcardPrice gets a reference to the given float32 and assigns it to the PostcardPrice field.
func (o *ViewRechargePackagesDataPackagesInner) SetPostcardPrice(v float32) {
	o.PostcardPrice = &v
}

// GetPostcardQuantity returns the PostcardQuantity field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetPostcardQuantity() float32 {
	if o == nil || IsNil(o.PostcardQuantity) {
		var ret float32
		return ret
	}
	return *o.PostcardQuantity
}

// GetPostcardQuantityOk returns a tuple with the PostcardQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetPostcardQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.PostcardQuantity) {
		return nil, false
	}
	return o.PostcardQuantity, true
}

// HasPostcardQuantity returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasPostcardQuantity() bool {
	if o != nil && !IsNil(o.PostcardQuantity) {
		return true
	}

	return false
}

// SetPostcardQuantity gets a reference to the given float32 and assigns it to the PostcardQuantity field.
func (o *ViewRechargePackagesDataPackagesInner) SetPostcardQuantity(v float32) {
	o.PostcardQuantity = &v
}

// GetAutomationPrice returns the AutomationPrice field value if set, zero value otherwise.
func (o *ViewRechargePackagesDataPackagesInner) GetAutomationPrice() float32 {
	if o == nil || IsNil(o.AutomationPrice) {
		var ret float32
		return ret
	}
	return *o.AutomationPrice
}

// GetAutomationPriceOk returns a tuple with the AutomationPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewRechargePackagesDataPackagesInner) GetAutomationPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.AutomationPrice) {
		return nil, false
	}
	return o.AutomationPrice, true
}

// HasAutomationPrice returns a boolean if a field has been set.
func (o *ViewRechargePackagesDataPackagesInner) HasAutomationPrice() bool {
	if o != nil && !IsNil(o.AutomationPrice) {
		return true
	}

	return false
}

// SetAutomationPrice gets a reference to the given float32 and assigns it to the AutomationPrice field.
func (o *ViewRechargePackagesDataPackagesInner) SetAutomationPrice(v float32) {
	o.AutomationPrice = &v
}

func (o ViewRechargePackagesDataPackagesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewRechargePackagesDataPackagesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PackageId) {
		toSerialize["package_id"] = o.PackageId
	}
	if !IsNil(o.PackagePrice) {
		toSerialize["package_price"] = o.PackagePrice
	}
	if !IsNil(o.PriceRate) {
		toSerialize["price_rate"] = o.PriceRate
	}
	if !IsNil(o.SmsPrice) {
		toSerialize["sms_price"] = o.SmsPrice
	}
	if !IsNil(o.SmsQuantity) {
		toSerialize["sms_quantity"] = o.SmsQuantity
	}
	if !IsNil(o.VoiceMobilePrice) {
		toSerialize["voice_mobile_price"] = o.VoiceMobilePrice
	}
	if !IsNil(o.VoiceMobileQuantity) {
		toSerialize["voice_mobile_quantity"] = o.VoiceMobileQuantity
	}
	if !IsNil(o.VoiceLandlinePrice) {
		toSerialize["voice_landline_price"] = o.VoiceLandlinePrice
	}
	if !IsNil(o.VoiceLandlineQuantity) {
		toSerialize["voice_landline_quantity"] = o.VoiceLandlineQuantity
	}
	if !IsNil(o.FaxPrice) {
		toSerialize["fax_price"] = o.FaxPrice
	}
	if !IsNil(o.FaxQuantity) {
		toSerialize["fax_quantity"] = o.FaxQuantity
	}
	if !IsNil(o.EmailPrice) {
		toSerialize["email_price"] = o.EmailPrice
	}
	if !IsNil(o.EmailQuantity) {
		toSerialize["email_quantity"] = o.EmailQuantity
	}
	if !IsNil(o.PostLetterBlackPrice) {
		toSerialize["post_letter_black_price"] = o.PostLetterBlackPrice
	}
	if !IsNil(o.PostLetterColourPrice) {
		toSerialize["post_letter_colour_price"] = o.PostLetterColourPrice
	}
	if !IsNil(o.PostPageBlackPrice) {
		toSerialize["post_page_black_price"] = o.PostPageBlackPrice
	}
	if !IsNil(o.PostPageColourPrice) {
		toSerialize["post_page_colour_price"] = o.PostPageColourPrice
	}
	if !IsNil(o.PostLetterBlackQuantity) {
		toSerialize["post_letter_black_quantity"] = o.PostLetterBlackQuantity
	}
	if !IsNil(o.PostLetterColourQuantity) {
		toSerialize["post_letter_colour_quantity"] = o.PostLetterColourQuantity
	}
	if !IsNil(o.PostDirectMailDlPrice) {
		toSerialize["post_direct_mail_dl_price"] = o.PostDirectMailDlPrice
	}
	if !IsNil(o.PostDirectMailA5Price) {
		toSerialize["post_direct_mail_a5_price"] = o.PostDirectMailA5Price
	}
	if !IsNil(o.PostDirectMailMinQuantity) {
		toSerialize["post_direct_mail_min_quantity"] = o.PostDirectMailMinQuantity
	}
	if !IsNil(o.PostcardPrice) {
		toSerialize["postcard_price"] = o.PostcardPrice
	}
	if !IsNil(o.PostcardQuantity) {
		toSerialize["postcard_quantity"] = o.PostcardQuantity
	}
	if !IsNil(o.AutomationPrice) {
		toSerialize["automation_price"] = o.AutomationPrice
	}
	return toSerialize, nil
}

type NullableViewRechargePackagesDataPackagesInner struct {
	value *ViewRechargePackagesDataPackagesInner
	isSet bool
}

func (v NullableViewRechargePackagesDataPackagesInner) Get() *ViewRechargePackagesDataPackagesInner {
	return v.value
}

func (v *NullableViewRechargePackagesDataPackagesInner) Set(val *ViewRechargePackagesDataPackagesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableViewRechargePackagesDataPackagesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableViewRechargePackagesDataPackagesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewRechargePackagesDataPackagesInner(val *ViewRechargePackagesDataPackagesInner) *NullableViewRechargePackagesDataPackagesInner {
	return &NullableViewRechargePackagesDataPackagesInner{value: val, isSet: true}
}

func (v NullableViewRechargePackagesDataPackagesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewRechargePackagesDataPackagesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


