/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the GetDefaultSendersListData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDefaultSendersListData{}

// GetDefaultSendersListData struct for GetDefaultSendersListData
type GetDefaultSendersListData struct {
	// List of default senders.
	Data []DefaultSender `json:"data,omitempty"`
	// Number of items per page.
	PerPage *int32 `json:"per_page,omitempty"`
	// URL for the current page.
	SelfPageUrl *string `json:"self_page_url,omitempty"`
	// URL for the next page.
	NextPageUrl *string `json:"next_page_url,omitempty"`
}

// NewGetDefaultSendersListData instantiates a new GetDefaultSendersListData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDefaultSendersListData() *GetDefaultSendersListData {
	this := GetDefaultSendersListData{}
	return &this
}

// NewGetDefaultSendersListDataWithDefaults instantiates a new GetDefaultSendersListData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDefaultSendersListDataWithDefaults() *GetDefaultSendersListData {
	this := GetDefaultSendersListData{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetDefaultSendersListData) GetData() []DefaultSender {
	if o == nil || IsNil(o.Data) {
		var ret []DefaultSender
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDefaultSendersListData) GetDataOk() ([]DefaultSender, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetDefaultSendersListData) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []DefaultSender and assigns it to the Data field.
func (o *GetDefaultSendersListData) SetData(v []DefaultSender) {
	o.Data = v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *GetDefaultSendersListData) GetPerPage() int32 {
	if o == nil || IsNil(o.PerPage) {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDefaultSendersListData) GetPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *GetDefaultSendersListData) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *GetDefaultSendersListData) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetSelfPageUrl returns the SelfPageUrl field value if set, zero value otherwise.
func (o *GetDefaultSendersListData) GetSelfPageUrl() string {
	if o == nil || IsNil(o.SelfPageUrl) {
		var ret string
		return ret
	}
	return *o.SelfPageUrl
}

// GetSelfPageUrlOk returns a tuple with the SelfPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDefaultSendersListData) GetSelfPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SelfPageUrl) {
		return nil, false
	}
	return o.SelfPageUrl, true
}

// HasSelfPageUrl returns a boolean if a field has been set.
func (o *GetDefaultSendersListData) HasSelfPageUrl() bool {
	if o != nil && !IsNil(o.SelfPageUrl) {
		return true
	}

	return false
}

// SetSelfPageUrl gets a reference to the given string and assigns it to the SelfPageUrl field.
func (o *GetDefaultSendersListData) SetSelfPageUrl(v string) {
	o.SelfPageUrl = &v
}

// GetNextPageUrl returns the NextPageUrl field value if set, zero value otherwise.
func (o *GetDefaultSendersListData) GetNextPageUrl() string {
	if o == nil || IsNil(o.NextPageUrl) {
		var ret string
		return ret
	}
	return *o.NextPageUrl
}

// GetNextPageUrlOk returns a tuple with the NextPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDefaultSendersListData) GetNextPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageUrl) {
		return nil, false
	}
	return o.NextPageUrl, true
}

// HasNextPageUrl returns a boolean if a field has been set.
func (o *GetDefaultSendersListData) HasNextPageUrl() bool {
	if o != nil && !IsNil(o.NextPageUrl) {
		return true
	}

	return false
}

// SetNextPageUrl gets a reference to the given string and assigns it to the NextPageUrl field.
func (o *GetDefaultSendersListData) SetNextPageUrl(v string) {
	o.NextPageUrl = &v
}

func (o GetDefaultSendersListData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDefaultSendersListData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	if !IsNil(o.SelfPageUrl) {
		toSerialize["self_page_url"] = o.SelfPageUrl
	}
	if !IsNil(o.NextPageUrl) {
		toSerialize["next_page_url"] = o.NextPageUrl
	}
	return toSerialize, nil
}

type NullableGetDefaultSendersListData struct {
	value *GetDefaultSendersListData
	isSet bool
}

func (v NullableGetDefaultSendersListData) Get() *GetDefaultSendersListData {
	return v.value
}

func (v *NullableGetDefaultSendersListData) Set(val *GetDefaultSendersListData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDefaultSendersListData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDefaultSendersListData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDefaultSendersListData(val *GetDefaultSendersListData) *NullableGetDefaultSendersListData {
	return &NullableGetDefaultSendersListData{value: val, isSet: true}
}

func (v NullableGetDefaultSendersListData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDefaultSendersListData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


