/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the ViewEmailTemplatesDataDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewEmailTemplatesDataDataInner{}

// ViewEmailTemplatesDataDataInner struct for ViewEmailTemplatesDataDataInner
type ViewEmailTemplatesDataDataInner struct {
	// The ID of the email template.
	TemplateId *int32 `json:"template_id,omitempty"`
	// The name of the email template.
	TemplateName *string `json:"template_name,omitempty"`
}

// NewViewEmailTemplatesDataDataInner instantiates a new ViewEmailTemplatesDataDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewEmailTemplatesDataDataInner() *ViewEmailTemplatesDataDataInner {
	this := ViewEmailTemplatesDataDataInner{}
	return &this
}

// NewViewEmailTemplatesDataDataInnerWithDefaults instantiates a new ViewEmailTemplatesDataDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewEmailTemplatesDataDataInnerWithDefaults() *ViewEmailTemplatesDataDataInner {
	this := ViewEmailTemplatesDataDataInner{}
	return &this
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *ViewEmailTemplatesDataDataInner) GetTemplateId() int32 {
	if o == nil || IsNil(o.TemplateId) {
		var ret int32
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewEmailTemplatesDataDataInner) GetTemplateIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TemplateId) {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *ViewEmailTemplatesDataDataInner) HasTemplateId() bool {
	if o != nil && !IsNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given int32 and assigns it to the TemplateId field.
func (o *ViewEmailTemplatesDataDataInner) SetTemplateId(v int32) {
	o.TemplateId = &v
}

// GetTemplateName returns the TemplateName field value if set, zero value otherwise.
func (o *ViewEmailTemplatesDataDataInner) GetTemplateName() string {
	if o == nil || IsNil(o.TemplateName) {
		var ret string
		return ret
	}
	return *o.TemplateName
}

// GetTemplateNameOk returns a tuple with the TemplateName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewEmailTemplatesDataDataInner) GetTemplateNameOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateName) {
		return nil, false
	}
	return o.TemplateName, true
}

// HasTemplateName returns a boolean if a field has been set.
func (o *ViewEmailTemplatesDataDataInner) HasTemplateName() bool {
	if o != nil && !IsNil(o.TemplateName) {
		return true
	}

	return false
}

// SetTemplateName gets a reference to the given string and assigns it to the TemplateName field.
func (o *ViewEmailTemplatesDataDataInner) SetTemplateName(v string) {
	o.TemplateName = &v
}

func (o ViewEmailTemplatesDataDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewEmailTemplatesDataDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TemplateId) {
		toSerialize["template_id"] = o.TemplateId
	}
	if !IsNil(o.TemplateName) {
		toSerialize["template_name"] = o.TemplateName
	}
	return toSerialize, nil
}

type NullableViewEmailTemplatesDataDataInner struct {
	value *ViewEmailTemplatesDataDataInner
	isSet bool
}

func (v NullableViewEmailTemplatesDataDataInner) Get() *ViewEmailTemplatesDataDataInner {
	return v.value
}

func (v *NullableViewEmailTemplatesDataDataInner) Set(val *ViewEmailTemplatesDataDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableViewEmailTemplatesDataDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableViewEmailTemplatesDataDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewEmailTemplatesDataDataInner(val *ViewEmailTemplatesDataDataInner) *NullableViewEmailTemplatesDataDataInner {
	return &NullableViewEmailTemplatesDataDataInner{value: val, isSet: true}
}

func (v NullableViewEmailTemplatesDataDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewEmailTemplatesDataDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


