/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the ViewVoiceLanguagesDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewVoiceLanguagesDataInner{}

// ViewVoiceLanguagesDataInner struct for ViewVoiceLanguagesDataInner
type ViewVoiceLanguagesDataInner struct {
	// The code of the language.
	Code *string `json:"code,omitempty"`
	// The country of the language.
	Country *string `json:"country,omitempty"`
	// The gender of the language.
	Gender *string `json:"gender,omitempty"`
}

// NewViewVoiceLanguagesDataInner instantiates a new ViewVoiceLanguagesDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewVoiceLanguagesDataInner() *ViewVoiceLanguagesDataInner {
	this := ViewVoiceLanguagesDataInner{}
	return &this
}

// NewViewVoiceLanguagesDataInnerWithDefaults instantiates a new ViewVoiceLanguagesDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewVoiceLanguagesDataInnerWithDefaults() *ViewVoiceLanguagesDataInner {
	this := ViewVoiceLanguagesDataInner{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ViewVoiceLanguagesDataInner) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewVoiceLanguagesDataInner) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ViewVoiceLanguagesDataInner) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ViewVoiceLanguagesDataInner) SetCode(v string) {
	o.Code = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *ViewVoiceLanguagesDataInner) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewVoiceLanguagesDataInner) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *ViewVoiceLanguagesDataInner) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *ViewVoiceLanguagesDataInner) SetCountry(v string) {
	o.Country = &v
}

// GetGender returns the Gender field value if set, zero value otherwise.
func (o *ViewVoiceLanguagesDataInner) GetGender() string {
	if o == nil || IsNil(o.Gender) {
		var ret string
		return ret
	}
	return *o.Gender
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewVoiceLanguagesDataInner) GetGenderOk() (*string, bool) {
	if o == nil || IsNil(o.Gender) {
		return nil, false
	}
	return o.Gender, true
}

// HasGender returns a boolean if a field has been set.
func (o *ViewVoiceLanguagesDataInner) HasGender() bool {
	if o != nil && !IsNil(o.Gender) {
		return true
	}

	return false
}

// SetGender gets a reference to the given string and assigns it to the Gender field.
func (o *ViewVoiceLanguagesDataInner) SetGender(v string) {
	o.Gender = &v
}

func (o ViewVoiceLanguagesDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewVoiceLanguagesDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Gender) {
		toSerialize["gender"] = o.Gender
	}
	return toSerialize, nil
}

type NullableViewVoiceLanguagesDataInner struct {
	value *ViewVoiceLanguagesDataInner
	isSet bool
}

func (v NullableViewVoiceLanguagesDataInner) Get() *ViewVoiceLanguagesDataInner {
	return v.value
}

func (v *NullableViewVoiceLanguagesDataInner) Set(val *ViewVoiceLanguagesDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableViewVoiceLanguagesDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableViewVoiceLanguagesDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewVoiceLanguagesDataInner(val *ViewVoiceLanguagesDataInner) *NullableViewVoiceLanguagesDataInner {
	return &NullableViewVoiceLanguagesDataInner{value: val, isSet: true}
}

func (v NullableViewVoiceLanguagesDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewVoiceLanguagesDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


