/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the CalculateFaxPriceRequestMessagesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalculateFaxPriceRequestMessagesInner{}

// CalculateFaxPriceRequestMessagesInner struct for CalculateFaxPriceRequestMessagesInner
type CalculateFaxPriceRequestMessagesInner struct {
	Source *string `json:"source,omitempty"`
	From *string `json:"from,omitempty"`
	To *string `json:"to,omitempty"`
	FromEmail *string `json:"from_email,omitempty"`
	Schedule *string `json:"schedule,omitempty"`
	CustomString *string `json:"custom_string,omitempty"`
}

// NewCalculateFaxPriceRequestMessagesInner instantiates a new CalculateFaxPriceRequestMessagesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalculateFaxPriceRequestMessagesInner() *CalculateFaxPriceRequestMessagesInner {
	this := CalculateFaxPriceRequestMessagesInner{}
	return &this
}

// NewCalculateFaxPriceRequestMessagesInnerWithDefaults instantiates a new CalculateFaxPriceRequestMessagesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalculateFaxPriceRequestMessagesInnerWithDefaults() *CalculateFaxPriceRequestMessagesInner {
	this := CalculateFaxPriceRequestMessagesInner{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *CalculateFaxPriceRequestMessagesInner) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateFaxPriceRequestMessagesInner) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *CalculateFaxPriceRequestMessagesInner) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *CalculateFaxPriceRequestMessagesInner) SetSource(v string) {
	o.Source = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *CalculateFaxPriceRequestMessagesInner) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateFaxPriceRequestMessagesInner) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *CalculateFaxPriceRequestMessagesInner) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *CalculateFaxPriceRequestMessagesInner) SetFrom(v string) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *CalculateFaxPriceRequestMessagesInner) GetTo() string {
	if o == nil || IsNil(o.To) {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateFaxPriceRequestMessagesInner) GetToOk() (*string, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *CalculateFaxPriceRequestMessagesInner) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *CalculateFaxPriceRequestMessagesInner) SetTo(v string) {
	o.To = &v
}

// GetFromEmail returns the FromEmail field value if set, zero value otherwise.
func (o *CalculateFaxPriceRequestMessagesInner) GetFromEmail() string {
	if o == nil || IsNil(o.FromEmail) {
		var ret string
		return ret
	}
	return *o.FromEmail
}

// GetFromEmailOk returns a tuple with the FromEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateFaxPriceRequestMessagesInner) GetFromEmailOk() (*string, bool) {
	if o == nil || IsNil(o.FromEmail) {
		return nil, false
	}
	return o.FromEmail, true
}

// HasFromEmail returns a boolean if a field has been set.
func (o *CalculateFaxPriceRequestMessagesInner) HasFromEmail() bool {
	if o != nil && !IsNil(o.FromEmail) {
		return true
	}

	return false
}

// SetFromEmail gets a reference to the given string and assigns it to the FromEmail field.
func (o *CalculateFaxPriceRequestMessagesInner) SetFromEmail(v string) {
	o.FromEmail = &v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *CalculateFaxPriceRequestMessagesInner) GetSchedule() string {
	if o == nil || IsNil(o.Schedule) {
		var ret string
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateFaxPriceRequestMessagesInner) GetScheduleOk() (*string, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *CalculateFaxPriceRequestMessagesInner) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given string and assigns it to the Schedule field.
func (o *CalculateFaxPriceRequestMessagesInner) SetSchedule(v string) {
	o.Schedule = &v
}

// GetCustomString returns the CustomString field value if set, zero value otherwise.
func (o *CalculateFaxPriceRequestMessagesInner) GetCustomString() string {
	if o == nil || IsNil(o.CustomString) {
		var ret string
		return ret
	}
	return *o.CustomString
}

// GetCustomStringOk returns a tuple with the CustomString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculateFaxPriceRequestMessagesInner) GetCustomStringOk() (*string, bool) {
	if o == nil || IsNil(o.CustomString) {
		return nil, false
	}
	return o.CustomString, true
}

// HasCustomString returns a boolean if a field has been set.
func (o *CalculateFaxPriceRequestMessagesInner) HasCustomString() bool {
	if o != nil && !IsNil(o.CustomString) {
		return true
	}

	return false
}

// SetCustomString gets a reference to the given string and assigns it to the CustomString field.
func (o *CalculateFaxPriceRequestMessagesInner) SetCustomString(v string) {
	o.CustomString = &v
}

func (o CalculateFaxPriceRequestMessagesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalculateFaxPriceRequestMessagesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.FromEmail) {
		toSerialize["from_email"] = o.FromEmail
	}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	if !IsNil(o.CustomString) {
		toSerialize["custom_string"] = o.CustomString
	}
	return toSerialize, nil
}

type NullableCalculateFaxPriceRequestMessagesInner struct {
	value *CalculateFaxPriceRequestMessagesInner
	isSet bool
}

func (v NullableCalculateFaxPriceRequestMessagesInner) Get() *CalculateFaxPriceRequestMessagesInner {
	return v.value
}

func (v *NullableCalculateFaxPriceRequestMessagesInner) Set(val *CalculateFaxPriceRequestMessagesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCalculateFaxPriceRequestMessagesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCalculateFaxPriceRequestMessagesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalculateFaxPriceRequestMessagesInner(val *CalculateFaxPriceRequestMessagesInner) *NullableCalculateFaxPriceRequestMessagesInner {
	return &NullableCalculateFaxPriceRequestMessagesInner{value: val, isSet: true}
}

func (v NullableCalculateFaxPriceRequestMessagesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalculateFaxPriceRequestMessagesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


