/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the GetStatisticsDataInnerLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetStatisticsDataInnerLinks{}

// GetStatisticsDataInnerLinks Link statistics
type GetStatisticsDataInnerLinks struct {
	// Total number of recipients
	Total *float32 `json:"total,omitempty"`
	// Total number of recipients that clicked the short URL
	OpenedUnique *float32 `json:"opened_unique,omitempty"`
	// Total number of clicks on the short URL (e.g. when a recipient clicked the short URL twice, then it will add 2 here)
	OpenedTotal *float32 `json:"opened_total,omitempty"`
	// Total number of recipients that did not click the short URL (i.e. `total` - `opened_unique`)
	Unopened *float32 `json:"unopened,omitempty"`
}

// NewGetStatisticsDataInnerLinks instantiates a new GetStatisticsDataInnerLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStatisticsDataInnerLinks() *GetStatisticsDataInnerLinks {
	this := GetStatisticsDataInnerLinks{}
	return &this
}

// NewGetStatisticsDataInnerLinksWithDefaults instantiates a new GetStatisticsDataInnerLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStatisticsDataInnerLinksWithDefaults() *GetStatisticsDataInnerLinks {
	this := GetStatisticsDataInnerLinks{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetStatisticsDataInnerLinks) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStatisticsDataInnerLinks) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetStatisticsDataInnerLinks) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *GetStatisticsDataInnerLinks) SetTotal(v float32) {
	o.Total = &v
}

// GetOpenedUnique returns the OpenedUnique field value if set, zero value otherwise.
func (o *GetStatisticsDataInnerLinks) GetOpenedUnique() float32 {
	if o == nil || IsNil(o.OpenedUnique) {
		var ret float32
		return ret
	}
	return *o.OpenedUnique
}

// GetOpenedUniqueOk returns a tuple with the OpenedUnique field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStatisticsDataInnerLinks) GetOpenedUniqueOk() (*float32, bool) {
	if o == nil || IsNil(o.OpenedUnique) {
		return nil, false
	}
	return o.OpenedUnique, true
}

// HasOpenedUnique returns a boolean if a field has been set.
func (o *GetStatisticsDataInnerLinks) HasOpenedUnique() bool {
	if o != nil && !IsNil(o.OpenedUnique) {
		return true
	}

	return false
}

// SetOpenedUnique gets a reference to the given float32 and assigns it to the OpenedUnique field.
func (o *GetStatisticsDataInnerLinks) SetOpenedUnique(v float32) {
	o.OpenedUnique = &v
}

// GetOpenedTotal returns the OpenedTotal field value if set, zero value otherwise.
func (o *GetStatisticsDataInnerLinks) GetOpenedTotal() float32 {
	if o == nil || IsNil(o.OpenedTotal) {
		var ret float32
		return ret
	}
	return *o.OpenedTotal
}

// GetOpenedTotalOk returns a tuple with the OpenedTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStatisticsDataInnerLinks) GetOpenedTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.OpenedTotal) {
		return nil, false
	}
	return o.OpenedTotal, true
}

// HasOpenedTotal returns a boolean if a field has been set.
func (o *GetStatisticsDataInnerLinks) HasOpenedTotal() bool {
	if o != nil && !IsNil(o.OpenedTotal) {
		return true
	}

	return false
}

// SetOpenedTotal gets a reference to the given float32 and assigns it to the OpenedTotal field.
func (o *GetStatisticsDataInnerLinks) SetOpenedTotal(v float32) {
	o.OpenedTotal = &v
}

// GetUnopened returns the Unopened field value if set, zero value otherwise.
func (o *GetStatisticsDataInnerLinks) GetUnopened() float32 {
	if o == nil || IsNil(o.Unopened) {
		var ret float32
		return ret
	}
	return *o.Unopened
}

// GetUnopenedOk returns a tuple with the Unopened field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStatisticsDataInnerLinks) GetUnopenedOk() (*float32, bool) {
	if o == nil || IsNil(o.Unopened) {
		return nil, false
	}
	return o.Unopened, true
}

// HasUnopened returns a boolean if a field has been set.
func (o *GetStatisticsDataInnerLinks) HasUnopened() bool {
	if o != nil && !IsNil(o.Unopened) {
		return true
	}

	return false
}

// SetUnopened gets a reference to the given float32 and assigns it to the Unopened field.
func (o *GetStatisticsDataInnerLinks) SetUnopened(v float32) {
	o.Unopened = &v
}

func (o GetStatisticsDataInnerLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetStatisticsDataInnerLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.OpenedUnique) {
		toSerialize["opened_unique"] = o.OpenedUnique
	}
	if !IsNil(o.OpenedTotal) {
		toSerialize["opened_total"] = o.OpenedTotal
	}
	if !IsNil(o.Unopened) {
		toSerialize["unopened"] = o.Unopened
	}
	return toSerialize, nil
}

type NullableGetStatisticsDataInnerLinks struct {
	value *GetStatisticsDataInnerLinks
	isSet bool
}

func (v NullableGetStatisticsDataInnerLinks) Get() *GetStatisticsDataInnerLinks {
	return v.value
}

func (v *NullableGetStatisticsDataInnerLinks) Set(val *GetStatisticsDataInnerLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStatisticsDataInnerLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStatisticsDataInnerLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStatisticsDataInnerLinks(val *GetStatisticsDataInnerLinks) *NullableGetStatisticsDataInnerLinks {
	return &NullableGetStatisticsDataInnerLinks{value: val, isSet: true}
}

func (v NullableGetStatisticsDataInnerLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStatisticsDataInnerLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


