/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the ForgotPasswordRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForgotPasswordRequest{}

// ForgotPasswordRequest struct for ForgotPasswordRequest
type ForgotPasswordRequest struct {
	Username *string `json:"username,omitempty"`
}

// NewForgotPasswordRequest instantiates a new ForgotPasswordRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForgotPasswordRequest() *ForgotPasswordRequest {
	this := ForgotPasswordRequest{}
	return &this
}

// NewForgotPasswordRequestWithDefaults instantiates a new ForgotPasswordRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForgotPasswordRequestWithDefaults() *ForgotPasswordRequest {
	this := ForgotPasswordRequest{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *ForgotPasswordRequest) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForgotPasswordRequest) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *ForgotPasswordRequest) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *ForgotPasswordRequest) SetUsername(v string) {
	o.Username = &v
}

func (o ForgotPasswordRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForgotPasswordRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

type NullableForgotPasswordRequest struct {
	value *ForgotPasswordRequest
	isSet bool
}

func (v NullableForgotPasswordRequest) Get() *ForgotPasswordRequest {
	return v.value
}

func (v *NullableForgotPasswordRequest) Set(val *ForgotPasswordRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableForgotPasswordRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableForgotPasswordRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForgotPasswordRequest(val *ForgotPasswordRequest) *NullableForgotPasswordRequest {
	return &NullableForgotPasswordRequest{value: val, isSet: true}
}

func (v NullableForgotPasswordRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForgotPasswordRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


