/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the UpdateEmailCampaignRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEmailCampaignRequest{}

// UpdateEmailCampaignRequest struct for UpdateEmailCampaignRequest
type UpdateEmailCampaignRequest struct {
	Schedule *int32 `json:"schedule,omitempty"`
	ListId *int32 `json:"list_id,omitempty"`
	Subject *string `json:"subject,omitempty"`
	FromEmailAddressId *int32 `json:"from_email_address_id,omitempty"`
	Name *string `json:"name,omitempty"`
	TemplateId *int32 `json:"template_id,omitempty"`
	Body *string `json:"body,omitempty"`
	FromName *string `json:"from_name,omitempty"`
}

// NewUpdateEmailCampaignRequest instantiates a new UpdateEmailCampaignRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEmailCampaignRequest() *UpdateEmailCampaignRequest {
	this := UpdateEmailCampaignRequest{}
	return &this
}

// NewUpdateEmailCampaignRequestWithDefaults instantiates a new UpdateEmailCampaignRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEmailCampaignRequestWithDefaults() *UpdateEmailCampaignRequest {
	this := UpdateEmailCampaignRequest{}
	return &this
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *UpdateEmailCampaignRequest) GetSchedule() int32 {
	if o == nil || IsNil(o.Schedule) {
		var ret int32
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmailCampaignRequest) GetScheduleOk() (*int32, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *UpdateEmailCampaignRequest) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given int32 and assigns it to the Schedule field.
func (o *UpdateEmailCampaignRequest) SetSchedule(v int32) {
	o.Schedule = &v
}

// GetListId returns the ListId field value if set, zero value otherwise.
func (o *UpdateEmailCampaignRequest) GetListId() int32 {
	if o == nil || IsNil(o.ListId) {
		var ret int32
		return ret
	}
	return *o.ListId
}

// GetListIdOk returns a tuple with the ListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmailCampaignRequest) GetListIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ListId) {
		return nil, false
	}
	return o.ListId, true
}

// HasListId returns a boolean if a field has been set.
func (o *UpdateEmailCampaignRequest) HasListId() bool {
	if o != nil && !IsNil(o.ListId) {
		return true
	}

	return false
}

// SetListId gets a reference to the given int32 and assigns it to the ListId field.
func (o *UpdateEmailCampaignRequest) SetListId(v int32) {
	o.ListId = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *UpdateEmailCampaignRequest) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmailCampaignRequest) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *UpdateEmailCampaignRequest) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *UpdateEmailCampaignRequest) SetSubject(v string) {
	o.Subject = &v
}

// GetFromEmailAddressId returns the FromEmailAddressId field value if set, zero value otherwise.
func (o *UpdateEmailCampaignRequest) GetFromEmailAddressId() int32 {
	if o == nil || IsNil(o.FromEmailAddressId) {
		var ret int32
		return ret
	}
	return *o.FromEmailAddressId
}

// GetFromEmailAddressIdOk returns a tuple with the FromEmailAddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmailCampaignRequest) GetFromEmailAddressIdOk() (*int32, bool) {
	if o == nil || IsNil(o.FromEmailAddressId) {
		return nil, false
	}
	return o.FromEmailAddressId, true
}

// HasFromEmailAddressId returns a boolean if a field has been set.
func (o *UpdateEmailCampaignRequest) HasFromEmailAddressId() bool {
	if o != nil && !IsNil(o.FromEmailAddressId) {
		return true
	}

	return false
}

// SetFromEmailAddressId gets a reference to the given int32 and assigns it to the FromEmailAddressId field.
func (o *UpdateEmailCampaignRequest) SetFromEmailAddressId(v int32) {
	o.FromEmailAddressId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateEmailCampaignRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmailCampaignRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateEmailCampaignRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateEmailCampaignRequest) SetName(v string) {
	o.Name = &v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *UpdateEmailCampaignRequest) GetTemplateId() int32 {
	if o == nil || IsNil(o.TemplateId) {
		var ret int32
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmailCampaignRequest) GetTemplateIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TemplateId) {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *UpdateEmailCampaignRequest) HasTemplateId() bool {
	if o != nil && !IsNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given int32 and assigns it to the TemplateId field.
func (o *UpdateEmailCampaignRequest) SetTemplateId(v int32) {
	o.TemplateId = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *UpdateEmailCampaignRequest) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmailCampaignRequest) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *UpdateEmailCampaignRequest) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *UpdateEmailCampaignRequest) SetBody(v string) {
	o.Body = &v
}

// GetFromName returns the FromName field value if set, zero value otherwise.
func (o *UpdateEmailCampaignRequest) GetFromName() string {
	if o == nil || IsNil(o.FromName) {
		var ret string
		return ret
	}
	return *o.FromName
}

// GetFromNameOk returns a tuple with the FromName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmailCampaignRequest) GetFromNameOk() (*string, bool) {
	if o == nil || IsNil(o.FromName) {
		return nil, false
	}
	return o.FromName, true
}

// HasFromName returns a boolean if a field has been set.
func (o *UpdateEmailCampaignRequest) HasFromName() bool {
	if o != nil && !IsNil(o.FromName) {
		return true
	}

	return false
}

// SetFromName gets a reference to the given string and assigns it to the FromName field.
func (o *UpdateEmailCampaignRequest) SetFromName(v string) {
	o.FromName = &v
}

func (o UpdateEmailCampaignRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEmailCampaignRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	if !IsNil(o.ListId) {
		toSerialize["list_id"] = o.ListId
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.FromEmailAddressId) {
		toSerialize["from_email_address_id"] = o.FromEmailAddressId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.TemplateId) {
		toSerialize["template_id"] = o.TemplateId
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.FromName) {
		toSerialize["from_name"] = o.FromName
	}
	return toSerialize, nil
}

type NullableUpdateEmailCampaignRequest struct {
	value *UpdateEmailCampaignRequest
	isSet bool
}

func (v NullableUpdateEmailCampaignRequest) Get() *UpdateEmailCampaignRequest {
	return v.value
}

func (v *NullableUpdateEmailCampaignRequest) Set(val *UpdateEmailCampaignRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEmailCampaignRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEmailCampaignRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEmailCampaignRequest(val *UpdateEmailCampaignRequest) *NullableUpdateEmailCampaignRequest {
	return &NullableUpdateEmailCampaignRequest{value: val, isSet: true}
}

func (v NullableUpdateEmailCampaignRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEmailCampaignRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


