/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the ViewVoiceStatisticsDataTotal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewVoiceStatisticsDataTotal{}

// ViewVoiceStatisticsDataTotal struct for ViewVoiceStatisticsDataTotal
type ViewVoiceStatisticsDataTotal struct {
	Outbound *ViewVoiceStatisticsDataTotalOutbound `json:"outbound,omitempty"`
	Bounced *ViewVoiceStatisticsDataTotalOutbound `json:"bounced,omitempty"`
}

// NewViewVoiceStatisticsDataTotal instantiates a new ViewVoiceStatisticsDataTotal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewVoiceStatisticsDataTotal() *ViewVoiceStatisticsDataTotal {
	this := ViewVoiceStatisticsDataTotal{}
	return &this
}

// NewViewVoiceStatisticsDataTotalWithDefaults instantiates a new ViewVoiceStatisticsDataTotal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewVoiceStatisticsDataTotalWithDefaults() *ViewVoiceStatisticsDataTotal {
	this := ViewVoiceStatisticsDataTotal{}
	return &this
}

// GetOutbound returns the Outbound field value if set, zero value otherwise.
func (o *ViewVoiceStatisticsDataTotal) GetOutbound() ViewVoiceStatisticsDataTotalOutbound {
	if o == nil || IsNil(o.Outbound) {
		var ret ViewVoiceStatisticsDataTotalOutbound
		return ret
	}
	return *o.Outbound
}

// GetOutboundOk returns a tuple with the Outbound field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewVoiceStatisticsDataTotal) GetOutboundOk() (*ViewVoiceStatisticsDataTotalOutbound, bool) {
	if o == nil || IsNil(o.Outbound) {
		return nil, false
	}
	return o.Outbound, true
}

// HasOutbound returns a boolean if a field has been set.
func (o *ViewVoiceStatisticsDataTotal) HasOutbound() bool {
	if o != nil && !IsNil(o.Outbound) {
		return true
	}

	return false
}

// SetOutbound gets a reference to the given ViewVoiceStatisticsDataTotalOutbound and assigns it to the Outbound field.
func (o *ViewVoiceStatisticsDataTotal) SetOutbound(v ViewVoiceStatisticsDataTotalOutbound) {
	o.Outbound = &v
}

// GetBounced returns the Bounced field value if set, zero value otherwise.
func (o *ViewVoiceStatisticsDataTotal) GetBounced() ViewVoiceStatisticsDataTotalOutbound {
	if o == nil || IsNil(o.Bounced) {
		var ret ViewVoiceStatisticsDataTotalOutbound
		return ret
	}
	return *o.Bounced
}

// GetBouncedOk returns a tuple with the Bounced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewVoiceStatisticsDataTotal) GetBouncedOk() (*ViewVoiceStatisticsDataTotalOutbound, bool) {
	if o == nil || IsNil(o.Bounced) {
		return nil, false
	}
	return o.Bounced, true
}

// HasBounced returns a boolean if a field has been set.
func (o *ViewVoiceStatisticsDataTotal) HasBounced() bool {
	if o != nil && !IsNil(o.Bounced) {
		return true
	}

	return false
}

// SetBounced gets a reference to the given ViewVoiceStatisticsDataTotalOutbound and assigns it to the Bounced field.
func (o *ViewVoiceStatisticsDataTotal) SetBounced(v ViewVoiceStatisticsDataTotalOutbound) {
	o.Bounced = &v
}

func (o ViewVoiceStatisticsDataTotal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewVoiceStatisticsDataTotal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Outbound) {
		toSerialize["outbound"] = o.Outbound
	}
	if !IsNil(o.Bounced) {
		toSerialize["bounced"] = o.Bounced
	}
	return toSerialize, nil
}

type NullableViewVoiceStatisticsDataTotal struct {
	value *ViewVoiceStatisticsDataTotal
	isSet bool
}

func (v NullableViewVoiceStatisticsDataTotal) Get() *ViewVoiceStatisticsDataTotal {
	return v.value
}

func (v *NullableViewVoiceStatisticsDataTotal) Set(val *ViewVoiceStatisticsDataTotal) {
	v.value = val
	v.isSet = true
}

func (v NullableViewVoiceStatisticsDataTotal) IsSet() bool {
	return v.isSet
}

func (v *NullableViewVoiceStatisticsDataTotal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewVoiceStatisticsDataTotal(val *ViewVoiceStatisticsDataTotal) *NullableViewVoiceStatisticsDataTotal {
	return &NullableViewVoiceStatisticsDataTotal{value: val, isSet: true}
}

func (v NullableViewVoiceStatisticsDataTotal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewVoiceStatisticsDataTotal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


