/*
SMS

You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clicksend

import (
	"encoding/json"
)

// checks if the ViewVoiceStatisticsDataStatsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewVoiceStatisticsDataStatsInner{}

// ViewVoiceStatisticsDataStatsInner struct for ViewVoiceStatisticsDataStatsInner
type ViewVoiceStatisticsDataStatsInner struct {
	// The date.
	Date *float32 `json:"date,omitempty"`
	Outbound *ViewVoiceStatisticsDataTotalOutbound `json:"outbound,omitempty"`
	Bounced *CancelAllSmsData `json:"bounced,omitempty"`
}

// NewViewVoiceStatisticsDataStatsInner instantiates a new ViewVoiceStatisticsDataStatsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewVoiceStatisticsDataStatsInner() *ViewVoiceStatisticsDataStatsInner {
	this := ViewVoiceStatisticsDataStatsInner{}
	return &this
}

// NewViewVoiceStatisticsDataStatsInnerWithDefaults instantiates a new ViewVoiceStatisticsDataStatsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewVoiceStatisticsDataStatsInnerWithDefaults() *ViewVoiceStatisticsDataStatsInner {
	this := ViewVoiceStatisticsDataStatsInner{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *ViewVoiceStatisticsDataStatsInner) GetDate() float32 {
	if o == nil || IsNil(o.Date) {
		var ret float32
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewVoiceStatisticsDataStatsInner) GetDateOk() (*float32, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *ViewVoiceStatisticsDataStatsInner) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given float32 and assigns it to the Date field.
func (o *ViewVoiceStatisticsDataStatsInner) SetDate(v float32) {
	o.Date = &v
}

// GetOutbound returns the Outbound field value if set, zero value otherwise.
func (o *ViewVoiceStatisticsDataStatsInner) GetOutbound() ViewVoiceStatisticsDataTotalOutbound {
	if o == nil || IsNil(o.Outbound) {
		var ret ViewVoiceStatisticsDataTotalOutbound
		return ret
	}
	return *o.Outbound
}

// GetOutboundOk returns a tuple with the Outbound field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewVoiceStatisticsDataStatsInner) GetOutboundOk() (*ViewVoiceStatisticsDataTotalOutbound, bool) {
	if o == nil || IsNil(o.Outbound) {
		return nil, false
	}
	return o.Outbound, true
}

// HasOutbound returns a boolean if a field has been set.
func (o *ViewVoiceStatisticsDataStatsInner) HasOutbound() bool {
	if o != nil && !IsNil(o.Outbound) {
		return true
	}

	return false
}

// SetOutbound gets a reference to the given ViewVoiceStatisticsDataTotalOutbound and assigns it to the Outbound field.
func (o *ViewVoiceStatisticsDataStatsInner) SetOutbound(v ViewVoiceStatisticsDataTotalOutbound) {
	o.Outbound = &v
}

// GetBounced returns the Bounced field value if set, zero value otherwise.
func (o *ViewVoiceStatisticsDataStatsInner) GetBounced() CancelAllSmsData {
	if o == nil || IsNil(o.Bounced) {
		var ret CancelAllSmsData
		return ret
	}
	return *o.Bounced
}

// GetBouncedOk returns a tuple with the Bounced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewVoiceStatisticsDataStatsInner) GetBouncedOk() (*CancelAllSmsData, bool) {
	if o == nil || IsNil(o.Bounced) {
		return nil, false
	}
	return o.Bounced, true
}

// HasBounced returns a boolean if a field has been set.
func (o *ViewVoiceStatisticsDataStatsInner) HasBounced() bool {
	if o != nil && !IsNil(o.Bounced) {
		return true
	}

	return false
}

// SetBounced gets a reference to the given CancelAllSmsData and assigns it to the Bounced field.
func (o *ViewVoiceStatisticsDataStatsInner) SetBounced(v CancelAllSmsData) {
	o.Bounced = &v
}

func (o ViewVoiceStatisticsDataStatsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewVoiceStatisticsDataStatsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Outbound) {
		toSerialize["outbound"] = o.Outbound
	}
	if !IsNil(o.Bounced) {
		toSerialize["bounced"] = o.Bounced
	}
	return toSerialize, nil
}

type NullableViewVoiceStatisticsDataStatsInner struct {
	value *ViewVoiceStatisticsDataStatsInner
	isSet bool
}

func (v NullableViewVoiceStatisticsDataStatsInner) Get() *ViewVoiceStatisticsDataStatsInner {
	return v.value
}

func (v *NullableViewVoiceStatisticsDataStatsInner) Set(val *ViewVoiceStatisticsDataStatsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableViewVoiceStatisticsDataStatsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableViewVoiceStatisticsDataStatsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewVoiceStatisticsDataStatsInner(val *ViewVoiceStatisticsDataStatsInner) *NullableViewVoiceStatisticsDataStatsInner {
	return &NullableViewVoiceStatisticsDataStatsInner{value: val, isSet: true}
}

func (v NullableViewVoiceStatisticsDataStatsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewVoiceStatisticsDataStatsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


